### ISSUE TITLE
The "TypescriptPlugin" test unexpectedly fails on the nightly CI job

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse/che#20472]
### Is your task related to a problem? Please describe

The "TypescriptPlugin" test unexpectedly fails on the nightly CI job

**Test log:**
```
...
      ✓ Open application in the new editor window (278ms)
          ▼ BrowserTabsUtil.switchToWindow
          ▼ Ide.waitAndSwitchToIdeFrame
      ✓ Switch back to the IDE window (113ms)
          ▼ ProjectTree.expandPathAndOpenFile "nodejs-web-app/app" filename: app.js
          ▼ ProjectTree.expandPath "nodejs-web-app/app"
          ▼ ProjectTree.expandItem "nodejs-web-app"
      1) Activate breakpoint
  [ERROR] CheReporter runner.on.fail: The 'TypescriptPlugin and Node-debug' tests The 'Node-debug' plugin test Activate breakpoint failed after 30233ms


  11 passing (3m)
  1 failing

  1) The 'TypescriptPlugin and Node-debug' tests
       The 'Node-debug' plugin test
         Activate breakpoint:
     TimeoutError: Exceeded maximum gettin of the 'class' attribute attempts, from the 'By(css selector, div[data-node-id='/projects/nodejs-web-app'])' element
      at DriverHelper.waitAndGetElementAttribute (/tmp/e2e/utils/DriverHelper.ts:345:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: <anonymous>
      at pollCondition (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2195:19)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2191:7
      at new ManagedPromise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at ControlFlow.promise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2505:12)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2190:22
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at ProjectTree.expandItem (/tmp/e2e/pageobjects/ide/ProjectTree.ts:147:45)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Screenshot:**
![screenshot-Activate_breakpoint](https://user-images.githubusercontent.com/22724619/133566230-34228e09-2295-4cc0-a97a-977365ff5287.png)

### Describe the solution you'd like

Investigate reason and resolve it

**Comment by Ohrimenko1988** [comment]
Done: https://github.com/eclipse/che/pull/20484
