### ISSUE TITLE
DevWorkspace Factory flow is broken from github

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20490]
### Describe the bug

DevWorkspace Factory flow is broken from github

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che with DevWorkspace enabled (`chectl server:deploy --installer=operator --platform=openshift --workspace-engine=dev-workspace`)
2. Try to create a workspace from java spring sample, or accept factory: `${CHE_HOST}##https://github.com/che-samples/java-spring-petclinic/tree/devfilev2`

### Expected behavior

Workspace is created and started

### Runtime

OpenShift

### Screenshots

![Screenshot_20210920_152721](https://user-images.githubusercontent.com/5887312/134002380-bfbb6ba0-eedb-4cdd-ad75-ecab6adabc9b.png)

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
2021-09-20 11:45:56,420[nio-8080-exec-7]  [WARN ] [o.e.c.s.oauth.EmbeddedOAuthAPI 159]  - Unsupported OAuth provider github 
2021-09-20 11:45:56,424[nio-8080-exec-7]  [ERROR] [thubPersonalAccessTokenFetcher 187]  - Unsupported OAuth provider github
org.eclipse.che.api.core.NotFoundException: Unsupported OAuth provider github
	at org.eclipse.che.security.oauth.EmbeddedOAuthAPI.getAuthenticator(EmbeddedOAuthAPI.java:160)
	at org.eclipse.che.security.oauth.EmbeddedOAuthAPI.getToken(EmbeddedOAuthAPI.java:124)
	at org.eclipse.che.api.factory.server.github.GithubPersonalAccessTokenFetcher.fetchPersonalAccessToken(GithubPersonalAccessTokenFetcher.java:145)
```

### Additional context

It breaks DevWorkspace Happy path tests on multiple repos, like Dashboard, Che Operator and DWO

**Comment by skabashnyuk** [comment]
Works for me on latest main of che-server
![Знімок екрана 2021-09-21 о 10 54 41](https://user-images.githubusercontent.com/1614429/134133315-780c4f64-a3f3-4e97-88ce-684430bf1ce6.png)
