### ISSUE TITLE
Che-operator pod is getting OOMkilled on GKE

### ISSUE THREAD

**Issue by coutantal** [eclipse/che#20529]
### Describe the bug

che-operator pod is getting OOMKilled when installed with chectl on GKE.

```
NAME                           READY   STATUS      RESTARTS   AGE
che-operator-9fc88fc85-hzrlj   0/1     OOMKilled   0          42s
```

### Che version

7.36@latest

### Steps to reproduce

1. Install eclipse-che on GKE with chectl
```
chectl server:deploy --platform=k8s --domain=************
```

### Expected behavior

che-operator should boots fine to let chectl continue with the installation

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
2021-09-23T16:17:02.095Z Cause: Error: Timeout: there are no pods in the namespace: eclipse-che, selector: app=che,component=postgres. Check Eclipse Che logs for details. Consider increasing error recheck timeout with --k8spoderrorrechecktimeout flag.
2021-09-23T16:17:02.095Z     at KubeTasks.<anonymous> (~/.local/share/chectl/client/7.36.1/lib/tasks/kube.js:155:23)
2021-09-23T16:17:02.095Z     at Generator.next (<anonymous>)
2021-09-23T16:17:02.095Z     at fulfilled (~/.local/share/chectl/client/7.36.1/node_modules/tslib/tslib.js:114:62)
2021-09-23T16:17:02.095Z     at runMicrotasks (<anonymous>)
```

### Additional context

Here's the resources definition of che-operator's deployment  :

```
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
```

Actually I can get around the issue by modifying these limits values.

**Comment by tolusha** [comment]
@coutantal 
Could you provide working limits?

**Comment by coutantal** [comment]
@tolusha what do you mean by working limits ?

I have no namespace or cluster-wide limitation for pod's resources.

**Comment by tolusha** [comment]
We were able to reproduce the issue and working on it
https://github.com/eclipse/che/issues/20647

**Comment by tolusha** [comment]
Fixed in 
- https://github.com/eclipse-che/che-operator/pull/1190 
- https://github.com/eclipse-che/che-operator/pull/1189 
- https://github.com/eclipse-che/che-operator/pull/1188 
- https://github.com/eclipse-che/che-operator/pull/1166

**Comment by coutantal** [comment]
Thanks for you work !
