### ISSUE TITLE
Failed to debug java spring sample with devworkspace engine

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20536]
### Describe the bug

Failed to debug java spring sample with devworkspace engine.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che with devworkspace engine.
2. Create workspace with https://github.com/musienko-maxim/java-spring-petclinic/tree/devfilev2
3. Build and try to debug app

### Expected behavior

It works

### Runtime

OpenShift, minikube

### Screenshots

![Screenshot_20210924_141005](https://user-images.githubusercontent.com/5887312/134665280-58f7f5ef-e055-4097-908b-9d20b666c7df.png)

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
2021-09-24 11:05:06.576 root ERROR Error starting the debug session Params: Error: It is not possible to provide debug adapter executable.
    at DebugExtImpl.<anonymous> (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:723:39)
    at step (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:33:23)
    at Object.next (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:14:53)
    at fulfilled (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
```


### Additional context

_No response_

**Comment by svor** [comment]
To start java debug need to have vscode-java in standard mode, it should be activate automatically by this preference in plugin's [meta.yaml](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-theia-plugins.yaml#L417):
`java.server.launchMode: Standard`
 currently we have a problem with it: [Preferences from the plugin are not applied for the workspace](https://github.com/eclipse/che/issues/20559).

**Comment by svor** [comment]
blocked by https://github.com/eclipse/che/issues/20559
