### ISSUE TITLE
E2E DevfileSmoke test is failing on "Stopping and deleting the workspace" step

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20533]
### Describe the bug

Che Dashboard happy path test pipeline, which is using `DevfileSmoke` E2E test is failing on `Stopping and deleting the workspace` step:
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-dashboard-pr-check/346/artifact/che/tests/e2e/report/Java_Maven_test_Stopping_and_deleting_the_workspace_Stop_and_remowe_workspace/screenshot-Stop_and_remowe_workspace.png

```
15:22:26            ▼ PreferencesHandler.setConfirmExit to never
15:22:26              ‣ PreferencesHandler.setPreferences application.confirmExit to never
15:22:26  
15:22:26    Login test
15:22:26            ▼ BrowserTabsUtil.navigateTo https://che-eclipse-che.10.0.208.64.nip.io
15:22:26              ‣ DriverHelper.getDriver
15:22:26  Can not get bearer token. URL used: https://keycloak-eclipse-che.10.0.208.64.nip.io/auth/realms/che/protocol/openid-connect/token
15:22:26    [ERROR] PreferencesHandler.setPreferences failed to get user preferences
15:22:26  (node:208) UnhandledPromiseRejectionWarning: Error: unable to verify the first certificate
15:22:26      at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
15:22:26      at TLSSocket.emit (events.js:198:13)
15:22:26      at TLSSocket._finishInit (_tls_wrap.js:636:8)
15:22:26  (node:208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
15:22:26  (node:208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
15:22:38            ▼ MultiUserLoginPage.login
15:22:38            ▼ CheLoginPage.waitEclipseCheLoginFormPage
15:22:38              ‣ DriverHelper.waitVisibility By(css selector, *[id="kc-form-login"])
15:22:43              ‣ DriverHelper.waitVisibility - Element is located and is visible.
15:22:43            ▼ CheLoginPage.inputUserNameEclipseCheLoginPage username: "admin"
15:22:43              ‣ DriverHelper.enterValue By(css selector, *[id="username"]) text: admin
15:22:43              ‣ DriverHelper.waitVisibility By(css selector, *[id="username"])
...
15:25:28        ✓ Wait for workspace readiness (156523ms)
15:25:28      Stopping and deleting the workspace
15:25:28            ▼ Dashboard.stopAndRemoveWorkspaceByUI "java-maven-aga7"
15:25:28            ▼ Dashboard.openDashboard
15:25:28              ‣ DriverHelper.getDriver
15:25:28            ▼ Dashboard.waitPage
15:25:28              ‣ DriverHelper.waitVisibility By(xpath, //div[@id='page-sidebar']//a[contains(text(), 'Workspaces (')])
15:25:28    [ERROR] DriverHelper.waitVisibility - failed with an unexpected exception - UnexpectedAlertOpenError: unexpected alert open: {Alert text : }
15:25:28      (Session info: chrome=89.0.4389.114): {Alert text : 
15:25:28    Build info: version: '4.0.0-beta-3', revision: 'fcfbc6ba25'
15:25:28    System info: host: 'minikube-rhel7-8gb-680', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.el7.x86_64', java.version: '1.8.0_282'
15:25:28    Driver info: driver.version: unknown
15:25:28        1) Stop and remowe workspace
15:25:28    [ERROR] CheReporter runner.on.fail: Java Maven test Stopping and deleting the workspace Stop and remowe workspace failed after 61ms
15:25:28              ‣ FullTitle:Java Maven test Stopping and deleting the workspace Stop and remowe workspace
15:25:28              ‣ FullTitleSanitized:Java_Maven_test_Stopping_and_deleting_the_workspace_Stop_and_remowe_workspace
15:25:28              ‣ TestTitle:Stop and remowe workspace
15:25:28              ‣ TestTitleSanitized:Stop_and_remowe_workspace
```

![screenshot-Stop_and_remowe_workspace](https://user-images.githubusercontent.com/1197777/134731583-2d8b7e81-16f2-417a-ba9a-919b390e5c23.png)

Root cause: problem with setting up user preferences "application.confirmExit" to `never`.

### Che version

next (development version)

### Steps to reproduce

Check what is done on Che Dashboard happy path test https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-dashboard-pr-check/

### Expected behavior

Path fully passes and job success

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

**Comment by dmytro-ndp** [comment]
che-dashboard PR check on CRW Jenkins has been fixed: https://github.com/eclipse-che/che-dashboard/pull/365#issuecomment-929285457
