### ISSUE TITLE
Got module not found error when using @eclipse-che/plugin

### ISSUE THREAD

**Issue by william-xiang** [eclipse/che#20556]
### Summary

I am trying to create a VS Code extension used in Che-Theia. In the extension, @eclipse-che/plugin is used to get workspace user and settings. I followed the instructions: https://www.eclipse.org/che/docs/che-7/contributor-guide/che-theia-plug-in-api/. But it gives the error below. The sample extension: https://github.com/william-xiang/che_api_ext1
```typescript
import * as vscode from 'vscode';
import * as che from "@eclipse-che/plugin";

export async function activate(context: vscode.ExtensionContext) {
	const user = await che.user.getCurrentUser();
	vscode.window.showInformationMessage(`User is: ${user.name}`);
}
```
```
Activating extension 'che-api-test' failed: Error: Cannot find module '@eclipse-che/plugin'
Require stack:
- /tmp/vscode-unpacked/che.api.test.latest.etnxjvkyql.-1.0.0-20210930.000934-56.vsix/extension/out/extension.js
- /remote-endpoint/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js
- /remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote-init.js
- /remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.module._load (/remote-endpoint/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:67:33)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/vscode-unpacked/che.api.test.latest.etnxjvkyql.-1.0.0-20210930.000934-56.vsix/extension/out/extension.js:14:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/vscode-unpacked/che.api.test.latest.etnxjvkyql.-1.0.0-20210930.000934-56.vsix/extension/out/extension.js',
    '/remote-endpoint/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js',
    '/remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote-init.js',
    '/remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote.js'
  ]
```

I also tried `VS Code extension mechanism` mentioned in the instructions to use che namespace. 
```typescript
export async function activate(context: vscode.ExtensionContext) {
	const eclipseCheExtPlugin = vscode.extensions.getExtension('@eclipse-che.ext-plugin');
	if (eclipseCheExtPlugin) {
		const user = await eclipseCheExtPlugin.exports.user.getCurrentUser();
		vscode.window.showInformationMessage(`Eclipse Che user information: id ${user.id} with name ${user.name}`);
	} else {
		vscode.window.showWarningMessage('Not running inside Eclipse Che, not displaying any user information');
	}
}
```
But got this error:
```
PLUGIN_HOST(1): initializing(che-api-test@0.0.1 with /remote-endpoint/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/che.api.test.latest.nyhgdnzydb-1.0.0-20210930.025836-62.vsix/extension/out/extension.js)
Activating extension 'che-api-test' failed: TypeError: Cannot read property 'user' of undefined
    at /tmp/vscode-unpacked/che.api.test.latest.nyhgdnzydb-1.0.0-20210930.025836-62.vsix/extension/out/extension.js:18:60
    at Generator.next (<anonymous>)
    at /tmp/vscode-unpacked/che.api.test.latest.nyhgdnzydb-1.0.0-20210930.025836-62.vsix/extension/out/extension.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/vscode-unpacked/che.api.test.latest.nyhgdnzydb-1.0.0-20210930.025836-62.vsix/extension/out/extension.js:4:12)
    at activate (/tmp/vscode-unpacked/che.api.test.latest.nyhgdnzydb-1.0.0-20210930.025836-62.vsix/extension/out/extension.js:15:12)
    at PluginManagerExtImpl.<anonymous> (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:552:87)
    at step (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:48:23)
    at Object.next (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:29:53)
    at /remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:23:71
```
The sample extension: https://github.com/william-xiang/che_api_ext2

### Relevant information

Che-Theia version: 7.32.2

**Comment by edmundreinhardt** [comment]
We are very much interested in a resolution to this issue as it is a blocker for us.  It is interesting that this used to work with an older version of Theia but not in the one that comes with the latest CodeReady Workpaces 2.10
@william-xiang Can you give the exact levels of Theia where it used to work?
This appears to be a regression.

**Comment by william-xiang** [comment]
The Theia version is 1.14. The same sample extension works in CodeReady Workspaces 2.7 with Che-Theia 7.24.2.
