### ISSUE TITLE
Git plugin checkout branch command doesn't work

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#20676]
### Describe the bug

Git plugin checkout command doesn't show any branch items in the quick-pick list, even if some input entered.
A console log error appears:
```
2021-10-21 07:37:30.023 root ERROR [hosted-plugin: 211] Promise rejection not handled in one second: TypeError: Cannot read properties of undefined (reading 'toString') , reason: TypeError: Cannot read properties of undefined (reading 'toString') 
2021-10-21 07:37:30.024 root ERROR Promise rejection not handled in one second: TypeError: Cannot read properties of undefined (reading 'toString') , reason: TypeError: Cannot read properties of undefined (reading 'toString')
 
2021-10-21 07:37:30.025 root ERROR [hosted-plugin: 211] With stack trace: TypeError: Cannot read properties of undefined (reading 'toString')
    at https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:118:64929
    at Array.map (<anonymous>)
    at q.splice (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:118:64868)
    at https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:6:42440
    at Array.forEach (<anonymous>)
    at L.splice (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:6:42411)
    at https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:136:10584
    at o.bufferEvents (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:60:4701)
    at q.splice (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:136:10539)
    at S.setElements (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:563:14968) 
2021-10-21 07:37:30.025 root ERROR With stack trace: TypeError: Cannot read properties of undefined (reading 'toString')
    at https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:118:64929
    at Array.map (<anonymous>)
    at q.splice (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:118:64868)
    at https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:6:42440
    at Array.forEach (<anonymous>)
    at L.splice (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:6:42411)
    at https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:136:10584
    at o.bufferEvents (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:60:4701)
    at q.splice (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:136:10539)
    at S.setElements (https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.23.0/min/vs/editor/editor.main.js:563:14968)
```

### Che version

next (development version)

### Steps to reproduce

Run `Git: Checout to...` command from the command palette.

### Expected behavior

A list of repository branches should appear.

### Runtime

minikube

### Screenshots

![screenshot-192 168 64 56 nip io-2021 10 21-10_37_27](https://user-images.githubusercontent.com/7668752/138232738-e0f88495-9247-4d32-9986-92220ac7c6e6.png)

### Installation method

chectl/next

### Environment

macOS

**Comment by vinokurig** [comment]
Can not reproduce in the latest version.
