### ISSUE TITLE
Microk8s failure to deploy devfile registry pod

### ISSUE THREAD

**Issue by gjevardat** [eclipse/che#20685]
### Summary

I have running fresh microk8s single node cluster with ingress enable.
chectl is configured to use external database (it worked with minikube)

chectl server:deploy -p microk8s
```
› Installer type is set to: 'operator'
› Current Kubernetes context: 'microk8s'
  ✔ Verify Kubernetes API...OK
  ✔ �  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  ✔ ✈️  MicroK8s preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if microk8s is installed
    ✔ Verify if microk8s is running
    ↓ Start microk8s [skipped]
      → MicroK8s is already running.
    ✔ Check Kubernetes version: Found v1.22.2-3+9ad9ee77396805.
    ✔ Verify if microk8s ingress and storage addons is enabled
    ↓ Enable microk8s ingress addon [skipped]
      → Ingress addon is already enabled.
    ↓ Enable microk8s storage addon [skipped]
      → Storage addon is already enabled.
    ✔ Retrieving microk8s IP and domain for ingress URLs...10.194.65.148.nip.io.
    ↓ Check if cluster accessible [skipped]
  ✔ Following Eclipse Che logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che Server logs...done
    ✔ Start following PostgreSQL logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plug-in Registry logs...done
    ✔ Start following Devfile Registry logs...done
    ✔ Start following Eclipse Che Dashboard logs...done
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
  ✔ �‍  Running the Eclipse Che operator
    ✔ Create Namespace (eclipse-che)...Done.
    ✔ Create ServiceAccount che-operator in namespace eclipse-che...done.
    ✔ Read Roles and Bindings...done.
    ✔ Creating Roles and Bindings...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Create backup and restore CRDs...done.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace eclipse-che...done.
    ✔ Operator pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Prepare Eclipse Che cluster CR...Done.
    ✔ Create the Custom Resource of type checlusters.org.eclipse.che in the namespace eclipse-che...done.
  ❯ ✅  Post installation checklist
    ✔ Keycloak pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ❯ Devfile Registry pod bootstrap
      ✖ Scheduling
        → Timeout: there are no pods in the namespace: eclipse-che, selector: app=che,component=devfile-registry. Check Eclipse Che logs for details. Consider increasing error recheck timeout with 
```

I'am not sure why the pod scheduling is failing with time. Logs are not super verbose

```
2021-10-25T09:31:43.978Z Cause: Error: Timeout: there are no pods in the namespace: eclipse-che, selector: app=che,component=devfile-registry. Check Eclipse Che logs for details. Consider increasing error recheck timeout with --k8spoderrorrechecktimeout flag.
2021-10-25T09:31:43.978Z     at KubeTasks.<anonymous> (/usr/local/lib/chectl/lib/tasks/kube.js:155:23)
2021-10-25T09:31:43.978Z     at Generator.next (<anonymous>)
2021-10-25T09:31:43.978Z     at fulfilled (/usr/local/lib/chectl/node_modules/tslib/tslib.js:114:62)
2021-10-25T09:31:43.978Z     at runMicrotasks (<anonymous>)
```
I do not have any other interesting logs, or I do not know where to find them...
Any help is welcome.
I guess it could be a microk8s default configuration issue as it worked well with minikube

### Relevant information

chectl/7.37.2 linux-x64 node-v12.22.6
1.22/stable:      v1.22.2
kubectl 1.22 (client and server)

**Comment by mmorhun** [comment]
Hello @gjevardat. Usually, such problems are related to routing configuration within the cluster. Che components should be able to reach each other via services and/or ingresses (routes for Openshift). So, the error is likely happens due to some configuration policies inside your cluster and out of scope for Che itself.

You may try to change value of `disableInternalClusterSVCNames` in Che Custom Resource:
`kubectl edit checluster eclipse-che -n eclipse-che`
and add the property under the given path below:
```
spec:
  server:
    disableInternalClusterSVCNames: true
```
It switches the way how Che components communicate with each other. However, it should work for the both options if the cluster itself configured correctly (we support this option for clusters with somewhat restricted communication). 

Note, in order to make Che work the cluster should have ingress controller configured properly. In many Kubernetes samples they use NodePort exposure which is a simplification (and sort of cheating) and not gonna work.

**Comment by tolusha** [comment]
@gjevardat 
Any luck to run Eclipse Che successfully ?

**Comment by gjevardat** [comment]
Hello unfortunately no :( I tried advice of @mmorhun  but still having this network issue 
```

0s          Warning   DNSConfigForming    pod/keycloak-699d57ddc5-mfxxl        Search Line limits were exceeded, some search paths have been omitted, the applied search line is: eclipse-che.svc.cluster.local svc.cluster.local cluster.loca
0s          Warning   Unhealthy           pod/keycloak-699d57ddc5-mfxxl        Readiness probe failed: Get "http://10.1.207.86:8080/auth/js/keycloak.js": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
0s          Warning   Unhealthy           pod/keycloak-699d57ddc5-mfxxl        Readiness probe failed: Get "http://10.1.207.86:8080/auth/js/keycloak.js": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
0s          Warning   DNSConfigForming    pod/keycloak-699d57ddc5-mfxxl        Search Line limits were exceeded, some search paths have been omitted, the applied search line is: eclipse-che.svc.cluster.local svc.cluster.local cluster.loca
```

**Comment by gjevardat** [comment]
We see this is really the readiness probe that is failing. I guess the failing IP is an internal IP so not sure why it is not visible

**Comment by mmorhun** [comment]
Looks like not a Che issue, but the cluster configuration. I don't use MicroK8s, so cannot help with details of it, but may recommend to setup a simple example with two pods and a service. Then manually exec into second pod and try to reach the other one via the service. If this works, Che should work too (but set `disableInternalClusterSVCNames` back to false then).
Alternatively, you can try to exec into an existing pod of Che and try to reach manually some endpoint, say, Postgres or Keycloak (try curl or wget). That might give some clues.
