### ISSUE TITLE
Error in 'Check versions compatibility' in chectl (Chectl:deploy)

### ISSUE THREAD

**Issue by siarhei-fedziukovich** [eclipse/che#20690]
### Summary

Chectl:deploy does not work.  (it had work before today morning)

command output:
Current Kubernetes context: 'docker-desktop'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  ✖ Check versions compatibility
    → Not Found
    Download templates
    Error: Command server:deploy failed. Error log: /home/siarhei_fedziukovich/.cache/chectl/error.log.
   
error.log.:
    Error: Command server:deploy failed. Error log: /home/siarhei_fedziukovich/.cache/chectl/error.log.
2021-10-25T20:43:21.285Z     at newError (/usr/local/lib/chectl/lib/util.js:199:19)
2021-10-25T20:43:21.285Z     at Object.wrapCommandError (/usr/local/lib/chectl/lib/util.js:195:12)
2021-10-25T20:43:21.285Z     at Deploy.<anonymous> (/usr/local/lib/chectl/lib/commands/server/deploy.js:243:35)
2021-10-25T20:43:21.285Z     at Generator.throw (<anonymous>)
2021-10-25T20:43:21.285Z     at rejected (/usr/local/lib/chectl/node_modules/tslib/tslib.js:115:69)
2021-10-25T20:43:21.285Z Cause: HttpError: Not Found
2021-10-25T20:43:21.285Z     at /usr/local/lib/chectl/node_modules/@octokit/request/dist-node/index.js:86:21

Looks like it try to open 'https://che-incubator.github.io/chectl/channels/stable/wsl-x64' under the hood, but this link response 404. 

what happened. why chectl breaks down?

### Relevant information

chectl/7.38.0 wsl-x64 node-v12.22.7

**Comment by tolusha** [comment]
@Ga2nibal 
Could you try one more time? Maybe it was race condition ?

**Comment by Ga2nibal** [comment]
no, it does not help. i tried many times. also i notes it does not work from my wsl2. but it works from host win command line.

**Comment by tolusha** [comment]
I guess you use `--version` flag in your chectl command.
To bypass the check download the corresponding version of chectl and use it without that flag

**Comment by Ga2nibal** [comment]
usage without `--version` works.
Thanks!
