### ISSUE TITLE
chectl fails to deploy minikube with Dex

### ISSUE THREAD

**Issue by sparkoo** [eclipse/che#20778]
### Describe the bug

When deploying on minikube with `nativeUserMode` enabled, chectl fails to deploy Dex.

### Che version

next (development version)

### Steps to reproduce

1. start minikube
2. create checluster patch file `native.patch`:
```
spec:
  auth:
    nativeUserMode: true
```
3. deploy `chectl server:deploy --platform=minikube --installer=operator --workspace-engine=dev-workspace --che-operator-cr-patch-yaml=native.patch`

chectl fails to deploy dex
```
❯ Deploy Dex
    ✔ Create namespace: dex...[Exists]
    ❯ Provide Dex certificate
      ✔ Check Cert Manager deployment...already deployed
      ✔ Wait for Cert Manager...ready
      ✖ Check Cert Manager CA certificate...generating new one
        → ENOENT: no such file or directory, open '/home/mvala/.local/share/chectl/client/0.0.20211116-next.75e3141/templates/cert-manager/ca-cert-generator-role.yml'

```

### Expected behavior

chectl must deploy dex and setup minikube

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
2021-11-16T12:24:23.413Z Error: Command server:deploy failed. Error log: /home/mvala/.cache/chectl/error.log.
2021-11-16T12:24:23.413Z     at newError (~/.local/share/chectl/client/0.0.20211116-next.75e3141/lib/util.js:199:19)
2021-11-16T12:24:23.413Z     at Object.wrapCommandError (~/.local/share/chectl/client/0.0.20211116-next.75e3141/lib/util.js:195:12)
2021-11-16T12:24:23.413Z     at Deploy.<anonymous> (~/.local/share/chectl/client/0.0.20211116-next.75e3141/lib/commands/server/deploy.js:235:35)
2021-11-16T12:24:23.413Z     at Generator.throw (<anonymous>)
2021-11-16T12:24:23.413Z     at rejected (~/.local/share/chectl/client/0.0.20211116-next.75e3141/node_modules/tslib/tslib.js:115:69)
2021-11-16T12:24:23.413Z Cause: Error: ENOENT: no such file or directory, open '/home/mvala/.local/share/chectl/client/0.0.20211116-next.75e3141/templates/cert-manager/ca-cert-generator-role.yml'
2021-11-16T12:24:23.413Z     at Object.safeLoadFromYamlFile (~/.local/share/chectl/client/0.0.20211116-next.75e3141/lib/util.js:257:25)
2021-11-16T12:24:23.413Z     at KubeHelper.safeLoadFromYamlFile (~/.local/share/chectl/client/0.0.20211116-next.75e3141/lib/api/kube.js:3111:23)
2021-11-16T12:24:23.413Z     at KubeHelper.<anonymous> (~/.local/share/chectl/client/0.0.20211116-next.75e3141/lib/api/kube.js:333:35)
2021-11-16T12:24:23.413Z     at Generator.next (<anonymous>)
2021-11-16T12:24:23.413Z     at ~/.local/share/chectl/client/0.0.20211116-next.75e3141/node_modules/tslib/tslib.js:117:75
2021-11-16T12:24:23.413Z     at new Promise (<anonymous>)
2021-11-16T12:24:23.413Z     at Object.__awaiter (~/.local/share/chectl/client/0.0.20211116-next.75e3141/node_modules/tslib/tslib.js:113:16)
2021-11-16T12:24:23.413Z     at KubeHelper.createRoleFromFile (~/.local/share/chectl/client/0.0.20211116-next.75e3141/lib/api/kube.js:332:24)
2021-11-16T12:24:23.413Z     at CertManagerTasks.<anonymous> (~/.local/share/chectl/client/0.0.20211116-next.75e3141/lib/tasks/component-installers/cert-manager.js:95:51)
2021-11-16T12:24:23.413Z     at Generator.next (<anonymous>)
2021-11-16T12:24:23.413Z     at fulfilled (~/.local/share/chectl/client/0.0.20211116-next.75e3141/node_modules/tslib/tslib.js:114:62)
```

**Comment by sparkoo** [comment]
I'm setting it as a blocker because it's currently blocking progress on PRs https://github.com/eclipse-che/che-dashboard/pull/401 and https://github.com/eclipse-che/che-server/pull/171 and work on issue https://github.com/eclipse/che/issues/20635
