### ISSUE TITLE
Fix Docker Desktop deployment

### ISSUE THREAD

**Issue by vevikram** [eclipse/che#20901]
### Describe the bug

On Running 

chectl server:deploy --platform=docker-desktop  

Following error is being reported by chectl

chectl server:deploy --platform=docker-desktop
› Installer type is set to: 'operator'
› Current Kubernetes context: 'docker-desktop'
  √ Verify Kubernetes API...OK
  √ 👀  Looking for an already existing Eclipse Che instance
    √ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  > ✈️  Docker Desktop preflight checklist
    √ Verify if kubectl is installed
    √ Verify if kubectl context is Docker Desktop: Found docker-desktop.
    √ Verify remote kubernetes status...done.
    √ Check Kubernetes version: Found v1.22.4.
    √ Verify if nginx ingress is installed
    × Installing nginx ingress
      → deployment.apps/nginx-ingress-controller unchanged
      Verify domain is set
    Error: Command server:deploy failed. Error log: C:\Users\******\AppData\Local\chectl\error.log. Eclipse Che logs:
     C:\Users\******\AppData\Local\Temp\chectl-logs\1638935197814.

Please find the Error Log below.

2021-12-08T03:43:20.409Z Error: Command server:deploy failed. Error log: C:/Users/*******/AppData/Local/chectl/error.log. Eclipse Che logs: C:/Users/*******/AppData/Local/Temp/chectl-logs/1638934987359.
2021-12-08T03:43:20.409Z     at newError (C:/ProgramData/chectl/chectl/lib/util.js:199:19)
2021-12-08T03:43:20.409Z     at Object.wrapCommandError (C:/ProgramData/chectl/chectl/lib/util.js:195:12)
2021-12-08T03:43:20.409Z     at Deploy.<anonymous> (C:/ProgramData/chectl/chectl/lib/commands/server/deploy.js:228:35)
2021-12-08T03:43:20.409Z     at Generator.throw (<anonymous>)
2021-12-08T03:43:20.409Z     at rejected (C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:115:69)
2021-12-08T03:43:20.409Z     at runMicrotasks (<anonymous>)
2021-12-08T03:43:20.409Z Cause: Error: Command failed with exit code 1: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/78d6ce6e6e7d77309bc1e8a563e4ee5308db5566/deploy/static/mandatory.yaml
2021-12-08T03:43:20.409Z unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/78d6ce6e6e7d77309bc1e8a563e4ee5308db5566/deploy/static/mandatory.yaml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
2021-12-08T03:43:20.409Z unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/78d6ce6e6e7d77309bc1e8a563e4ee5308db5566/deploy/static/mandatory.yaml": no matches for kind "Role" in version "rbac.authorization.k8s.io/v1beta1"
2021-12-08T03:43:20.409Z unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/78d6ce6e6e7d77309bc1e8a563e4ee5308db5566/deploy/static/mandatory.yaml": no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
2021-12-08T03:43:20.409Z unable to recognize "https://raw.githubusercontent.com/kubernetes/ingress-nginx/78d6ce6e6e7d77309bc1e8a563e4ee5308db5566/deploy/static/mandatory.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
2021-12-08T03:43:20.409Z namespace/ingress-nginx created
2021-12-08T03:43:20.409Z configmap/nginx-configuration created
2021-12-08T03:43:20.409Z configmap/tcp-services created
2021-12-08T03:43:20.409Z configmap/udp-services created
2021-12-08T03:43:20.409Z serviceaccount/nginx-ingress-serviceaccount created
2021-12-08T03:43:20.409Z deployment.apps/nginx-ingress-controller created
2021-12-08T03:43:20.409Z     at makeError (C:/ProgramData/chectl/chectl/node_modules/execa/lib/error.js:60:11)
2021-12-08T03:43:20.409Z     at handlePromise (C:/ProgramData/chectl/chectl/node_modules/execa/index.js:118:26)
2021-12-08T03:43:20.409Z     at runMicrotasks (<anonymous>)

### Che version

7.40@latest

### Steps to reproduce

1. If you're using Windows x64, here is how to install chectl by using one single PowerShell command:

For stable channel:
C:\Users> Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadStrin

2. run chectl server:deploy --platform=docker-desktop

### Expected behavior

elcipse-che should get installed

### Runtime

Docker Desktop

### Installation method

chectl/latest

### Environment

Windows

### Eclipse Che Logs

```shell
chectl server:deploy --platform=docker-desktop
› Installer type is set to: 'operator'
› Current Kubernetes context: 'docker-desktop'
  √ Verify Kubernetes API...OK
  √ 👀  Looking for an already existing Eclipse Che instance
    √ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  > ✈️  Docker Desktop preflight checklist
    √ Verify if kubectl is installed
    √ Verify if kubectl context is Docker Desktop: Found docker-desktop.
    √ Verify remote kubernetes status...done.
    √ Check Kubernetes version: Found v1.22.4.
    √ Verify if nginx ingress is installed
    × Installing nginx ingress
      → deployment.apps/nginx-ingress-controller unchanged
      Verify domain is set
    Error: Command server:deploy failed. Error log: C:\Users\******\AppData\Local\chectl\error.log. Eclipse Che logs:
     C:\Users\******\AppData\Local\Temp\chectl-logs\1638935197814.
```

### Release Notes Text

Docker Desktop deployment of Eclipse Che was not working due to some outdated templates to install the nginx routing controller. The templates have been updated to the latest version.

**Comment by tolusha** [comment]
It seems templates are outdated.
Could you try to deploy nginx controller manually [1] and redeploy Eclipse Che ?

[1] https://kubernetes.github.io/ingress-nginx/deploy/#docker-desktop

**Comment by vevikram** [comment]
Thanks it started working :-)

**Comment by tolusha** [comment]
I reopen this issue to update templates in chectl
