### ISSUE TITLE
Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io"

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20912]
### Describe the bug

Quite often I have this error when deploying Che on minikube.
```
    ✔ Create Dex service...[OK]
    ✖ Create Dex ingress
      → Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.100.55.50:443: i/o timeout
      Generate Dex username and password
```

### Che version

next (development version)

### Steps to reproduce

1. start minikube `minikube start --cpus 4 --memory 6000`
2. update chectl `chectl update next`
3. deploy che on MacOS `chectl server:deploy --platform=minikube --installer=operator --workspace-engine=dev-workspace`

### Expected behavior

Error should not happen.

### Runtime

minikube

### Screenshots

![Знімок екрана 2021-12-10 о 10 56 29](https://user-images.githubusercontent.com/1614429/145546126-51a10daf-c827-41ae-ad8d-1fb2ccb19d09.png)

### Installation method

chectl/next

### Environment

macOS

### Eclipse Che Logs

```shell
021-11-22T08:03:15.053Z     at rejected (~/.local/share/chectl/client/0.0.20211119-next.53696c6/node_modules/tslib/tslib.js:115:69)
2021-11-22T08:03:15.053Z     at runMicrotasks (<anonymous>)
2021-11-22T08:03:15.053Z Cause: HttpError: HTTP request failed
2021-11-22T08:03:15.053Z     at Request._callback (~/.local/share/chectl/client/0.0.20211119-next.53696c6/node_modules/@kubernetes/client-node/dist/gen/api/networkingV1Api.js:235:40)
2021-11-22T08:03:15.053Z     at Request.self.callback (~/.local/share/chectl/client/0.0.20211119-next.53696c6/node_modules/request/request.js:185:22)
2021-11-22T08:03:15.053Z     at Request.<anonymous> (~/.local/share/chectl/client/0.0.20211119-next.53696c6/node_modules/request/request.js:1154:10)
2021-11-22T08:03:15.053Z     at IncomingMessage.<anonymous> (~/.local/share/chectl/client/0.0.20211119-next.53696c6/node_modules/request/request.js:1076:12)2021-11-26T10:39:55.268Z Error: Expected --workspace-engine=dev-workspac to be one of: che-server, dev-workspace
2021-11-26T10:39:55.268Z See more help with --help
2021-11-26T10:39:55.268Z     at Parser._flags (~/.local/share/chectl/client/0.0.20211124-next.e4abc4e/node_modules/@oclif/parser/lib/parse.js:154:27)
2021-11-26T10:39:55.268Z     at Parser.parse (~/.local/share/chectl/client/0.0.20211124-next.e4abc4e/node_modules/@oclif/parser/lib/parse.js:117:28)
2021-11-26T10:39:55.268Z     at Object.parse (~/.local/share/chectl/client/0.0.20211124-next.e4abc4e/node_modules/@oclif/parser/lib/index.js:27:27)
2021-11-26T10:39:55.268Z     at Deploy.parse (~/.local/share/chectl/client/0.0.20211124-next.e4abc4e/node_modules/@oclif/command/lib/command.js:86:41)
2021-11-26T10:39:55.268Z     at Deploy.<anonymous> (~/.local/share/chectl/client/0.0.20211124-next.e4abc4e/lib/commands/server/deploy.js:156:36)
2021-11-26T10:39:55.268Z     at Generator.next (<anonymous>)
2021-11-26T10:39:55.268Z     at ~/.local/share/chectl/client/0.0.20211124-next.e4abc4e/node_modules/tslib/tslib.js:117:75
2021-11-26T10:39:55.268Z     at new Promise (<anonymous>)
2021-11-26T10:39:55.268Z     at Object.__awaiter (~/.local/share/chectl/client/0.0.20211124-next.e4abc4e/node_modules/tslib/tslib.js:113:16)
2021-11-26T10:39:55.268Z     at Deploy.run (~/.local/share/chectl/client/0.0.20211124-next.e4abc4e/lib/commands/server/deploy.js:155:24)
2021-11-26T10:39:55.268Z     at Deploy._run (~/.local/share/chectl/client/0.0.20211124-next.e4abc4e/node_modules/@oclif/command/lib/command.js:43:31)2021-12-08T07:25:27.062Z Error: Command server:deploy failed. Error log: /Users/skabashn/Library/Caches/chectl/error.log.
2021-12-08T07:25:27.062Z     at newError (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/lib/util.js:199:19)
2021-12-08T07:25:27.062Z     at Object.wrapCommandError (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/lib/util.js:195:12)
2021-12-08T07:25:27.062Z     at Deploy.<anonymous> (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/lib/commands/server/deploy.js:228:35)
2021-12-08T07:25:27.062Z     at Generator.throw (<anonymous>)
2021-12-08T07:25:27.062Z     at rejected (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/node_modules/tslib/tslib.js:115:69)
2021-12-08T07:25:27.062Z     at runMicrotasks (<anonymous>)
2021-12-08T07:25:27.062Z Cause: Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.98.64.190:443: i/o timeout
2021-12-08T07:25:27.062Z     at Object.newError (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/lib/util.js:199:19)
2021-12-08T07:25:27.062Z     at KubeHelper.wrapK8sClientError (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/lib/api/kube.js:3107:31)
2021-12-08T07:25:27.062Z     at KubeHelper.<anonymous> (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/lib/api/kube.js:1561:28)
2021-12-08T07:25:27.062Z     at Generator.throw (<anonymous>)
2021-12-08T07:25:27.062Z     at rejected (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/node_modules/tslib/tslib.js:115:69)
2021-12-08T07:25:27.062Z     at runMicrotasks (<anonymous>)
2021-12-08T07:25:27.062Z Cause: HttpError: HTTP request failed
2021-12-08T07:25:27.062Z     at Request._callback (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/node_modules/@kubernetes/client-node/dist/gen/api/networkingV1Api.js:235:40)
2021-12-08T07:25:27.062Z     at Request.self.callback (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/node_modules/request/request.js:185:22)
2021-12-08T07:25:27.062Z     at Request.<anonymous> (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/node_modules/request/request.js:1154:10)
2021-12-08T07:25:27.062Z     at IncomingMessage.<anonymous> (~/.local/share/chectl/client/0.0.20211207-next.33ff4d2/node_modules/request/request.js:1076:12)2021-12-10T08:53:43.883Z Error: Command server:deploy failed. Error log: /Users/skabashn/Library/Caches/chectl/error.log.
2021-12-10T08:53:43.883Z     at newError (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/lib/util.js:199:19)
2021-12-10T08:53:43.883Z     at Object.wrapCommandError (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/lib/util.js:195:12)
2021-12-10T08:53:43.883Z     at Deploy.<anonymous> (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/lib/commands/server/deploy.js:228:35)
2021-12-10T08:53:43.883Z     at Generator.throw (<anonymous>)
2021-12-10T08:53:43.883Z     at rejected (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/node_modules/tslib/tslib.js:115:69)
2021-12-10T08:53:43.883Z     at runMicrotasks (<anonymous>)
2021-12-10T08:53:43.883Z Cause: Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.100.55.50:443: i/o timeout
2021-12-10T08:53:43.883Z     at Object.newError (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/lib/util.js:199:19)
2021-12-10T08:53:43.883Z     at KubeHelper.wrapK8sClientError (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/lib/api/kube.js:3107:31)
2021-12-10T08:53:43.883Z     at KubeHelper.<anonymous> (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/lib/api/kube.js:1561:28)
2021-12-10T08:53:43.883Z     at Generator.throw (<anonymous>)
2021-12-10T08:53:43.883Z     at rejected (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/node_modules/tslib/tslib.js:115:69)
2021-12-10T08:53:43.883Z     at runMicrotasks (<anonymous>)
2021-12-10T08:53:43.883Z Cause: HttpError: HTTP request failed
2021-12-10T08:53:43.883Z     at Request._callback (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/node_modules/@kubernetes/client-node/dist/gen/api/networkingV1Api.js:235:40)
2021-12-10T08:53:43.883Z     at Request.self.callback (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/node_modules/request/request.js:185:22)
2021-12-10T08:53:43.883Z     at Request.<anonymous> (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/node_modules/request/request.js:1154:10)
2021-12-10T08:53:43.883Z     at IncomingMessage.<anonymous> (~/.local/share/chectl/client/0.0.20211209-next.4e8704a/node_modules/request/request.js:1076:12)
```

### Additional context

n/a

**Comment by benoitf** [comment]
I don't know if this might help but I usually install the addon when starting minikube like

```
minikube start .... --addons=ingress
```

**Comment by tolusha** [comment]
duplicates 
https://github.com/eclipse/che/issues/20888
?

**Comment by skabashnyuk** [comment]
Closing in favor of https://github.com/eclipse/che/issues/20888
