### ISSUE TITLE
Happy Path tests are failing on "Java LS initialization" step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#20926]
### Describe the bug

https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/1288/console

```
...
             ‣ DriverHelper.waitAndGetText By(css selector, div[id='theia-statusBar'])
             ‣ DriverHelper.waitVisibility By(css selector, div[id='theia-statusBar'])
             ‣ DriverHelper.waitVisibility - Element is located and is visible.
             ‣ DriverHelper.wait (2000 milliseconds)
     1) Java LS initialization
   [ERROR] CheReporter runner.on.fail: Language server validation Java LS initialization failed after 1086205ms
             ‣ FullTitle:Language server validation Java LS initialization
             ‣ FullTitleSanitized:Language_server_validation_Java_LS_initialization
             ‣ TestTitle:Java LS initialization
             ‣ TestTitleSanitized:Java_LS_initialization
 
 
   4 passing (21m)
   1 failing
 
   1) Language server validation
        Java LS initialization:
      TimeoutError: Wait timed out after 180271ms
       at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
       at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
```

### Che version

next (development version)

### Steps to reproduce

1. Install Eclipse Che on minikube
2. Create and start E2E Happy path test workspace using.
3. Execute E2E Happy path tests

### Expected behavior

E2E test to passed

### Runtime

minikube

### Screenshots

![screenshot-Java_LS_initialization](https://user-images.githubusercontent.com/1197777/145852686-9af77659-81c9-4103-9204-42f4c9f0ee18.png)

https://user-images.githubusercontent.com/1197777/145852698-8bf1e42e-bd2b-4205-bf54-08de97ed265d.mp4

### Installation method

chectl/next

### Environment

Linux

**Comment by dmytro-ndp** [comment]
The problem isn't reproduced last week.
