### ISSUE TITLE
Git Clone from Theia UI is not working

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [eclipse/che#20978]
### Describe the bug

Unable to clone using the GIT Clone Plugin

### Che version

7.40@latest

### Steps to reproduce

1) Create a workspace
2) Use the Git clone "git:clone"
3) unable to find an option to provide the clone. 

### Expected behavior

4) After the selection of "git:clone", 
5) A blank textbox to enter the https git clone url. it does not work.

### Runtime

Docker Desktop

### Installation method

chectl/latest, other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

1) Used Oracle Kubernetes Instance
2) Local deployment with -v 7.40.2

**Comment by kollachaitanyakrishna** [comment]
Extension-Host:Promise rejection not handled in one second: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'f'
    |     property '_onDidOpenRepository' -> object with constructor 'Emitter'
    |     property '_callbacks' -> object with constructor 'CallbackList'
    |     ...
    |     index 2 -> object with constructor 't.GitDecorations'
    --- property 'model' closes the circle , reason: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'f'
    |     property '_onDidOpenRepository' -> object with constructor 'Emitter'
    |     property '_callbacks' -> object with constructor 'CallbackList'
    |     ...
    |     index 2 -> object with constructor 't.GitDecorations'
    --- property 'model' closes the circle
Extension-Host:With stack trace: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'f'
    |     property '_onDidOpenRepository' -> object with constructor 'Emitter'
    |     property '_callbacks' -> object with constructor 'CallbackList'
    |     ...
    |     index 2 -> object with constructor 't.GitDecorations'
    --- property 'model' closes the circle
    at JSON.stringify (<anonymous>)
    at RPCProtocolImpl.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:238:114)
    at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:134:36)
    at Proxy.target.<computed> (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:112:56)
    at QuickPickExt.dispatchUpdate (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:336:28)
    at QuickPickExt.update (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:325:18)
    at QuickPickExt.show (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:299:14)
    at t (/default-theia-plugins/vscode-git/extension/dist/main.js:1:127183)
    at new Promise (<anonymous>)
    at c (/default-theia-plugins/vscode-git/extension/dist/main.js:1:127097)

**Comment by benoitf** [comment]
it was fixed in 7.41
it's a dup of https://github.com/eclipse/che/issues/20316
