### ISSUE TITLE
Happy Path GitHub action should be adapted in Che Plugin Registry repo

### ISSUE THREAD

**Issue by svor** [eclipse/che#20986]
### Is your task related to a problem? Please describe

che-operator was switched to the Dev Workspace engine by default (see eclipse-che/che-operator#1265) which doesn't use Keycloak any more. Right know Happy Path GitHub action fails with the error:
```
Command server:deploy has completed successfully in 05:16.
Eclipse Che [sets che-url]...
Setting Github Action output value "che-url"...
Eclipse Che [sets che-token]...
stack=Error: Command failed with exit code 1: kubectl get ingress/keycloak -n eclipse-che -o jsonpath='{.spec.rules[0].host}'
Error from server (NotFound): ingresses.networking.k8s.io "keycloak" not found
    at makeError (/home/runner/work/_actions/che-incubator/che-deploy-action/next/lib/index.js:1763:11)
    at handlePromise (/home/runner/work/_actions/che-incubator/che-deploy-action/next/lib/index.js:1512:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Unable to start Error: Command failed with exit code 1: kubectl get ingress/keycloak -n eclipse-che -o jsonpath='{.spec.rules[0].host}'
Error from server (NotFound): ingresses.networking.k8s.io "keycloak" not found
    at makeError (/home/runner/work/_actions/che-incubator/che-deploy-action/next/lib/index.js:1763:11)
    at handlePromise (/home/runner/work/_actions/che-incubator/che-deploy-action/next/lib/index.js:1512:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  shortMessage: "Command failed with exit code 1: kubectl get ingress/keycloak -n eclipse-che -o jsonpath='{.spec.rules[0].host}'",
  command: "kubectl get ingress/keycloak -n eclipse-che -o jsonpath='{.spec.rules[0].host}'",
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Error from server (NotFound): ingresses.networking.k8s.io "keycloak" not found',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
https://github.com/eclipse-che/che-plugin-registry/runs/4714855001?check_suite_focus=true

### Describe the solution you'd like

Happy Path GitHub action should be adapted to work with Dev Workspace engine

**Comment by benoitf** [comment]
it may depend also on https://github.com/eclipse/che/issues/20663

**Comment by l0rd** [comment]
I have raised that to P1. @dmytro-ndp can you confirm that you are not able to fix that and that you require engineering to look at it?

**Comment by dmytro-ndp** [comment]
@dmytro-ndp: actually, Happy path tests are failing on getting Che token, which is not supported in DevWorkspaces mode https://github.com/che-incubator/che-deploy-action/blob/f1620c03083453db63e4940bedab79540ac77817/src/che-helper.ts#L119

Looks like Happy path tests specific problem, which doesn't require developers help at the moment.

**Comment by benoitf** [comment]
`che-deploy-action` is now fixed for DevWorkspace mode (but there is still happy path action to fix)

**Comment by dmytro-ndp** [comment]
@benoitf: thank you!
Let me fix `happy-path-tests-action` then.

**Comment by dmytro-ndp** [comment]
@l0rd: Happy path tests on ubuntu minikube had failed [1] because Eclipse Che Next main page returned `503 Service Temporarily Unavailable` error [2].

@tolusha: could you take a look, please?

[1] https://github.com/eclipse-che/che-plugin-registry/actions/runs/1800124531
[2] #21125

**Comment by benoitf** [comment]
@dmytro-ndp did you try with other minikube versions ? ( More recent 
https://github.com/eclipse-che/che-plugin-registry/blob/main/.github/workflows/happy-path.yaml#L85

Also you may try to use the 'stable' channel of chectl to continue your investigation ( tmp workaround)

**Comment by dmytro-ndp** [comment]
@benoitf: thanks for the tips!

#21125 issue has been reproduced with Eclipse Che Stable (7.43.0), deployed by [chectl 7.43.0](https://github.com/che-incubator/chectl/releases/download/7.43.0/chectl-linux-x64.tar.gz): https://github.com/eclipse-che/che-plugin-registry/runs/5083149233?check_suite_focus=true

There were other errors in latest minikube version v1.25.1:
- #21126
- #21128

**Comment by wbondarchuk** [comment]
> @dmytro-ndp did you try with other minikube versions ? ( More recent https://github.com/eclipse-che/che-plugin-registry/blob/main/.github/workflows/happy-path.yaml#L85
> 
> Also you may try to use the 'stable' channel of chectl to continue your investigation ( tmp workaround)

I installed version 1.21.0, but it didn't solve the 503 error problem(https://github.com/eclipse/che/issues/21125)

**Comment by dmytro-ndp** [comment]
Che stable/next Installation has failed on minikube v1.20.0: 
https://github.com/eclipse-che/che-plugin-registry/runs/5092423006?check_suite_focus=true
```
› Installer type is set to: 'operator'
[11:50:01] Verify Kubernetes API [started]
› Current Kubernetes context: 'minikube'
[11:50:01] Verify Kubernetes API...OK [title changed]
[11:50:02] Verify Kubernetes API...OK [completed]
[11:50:02] 👀  Looking for an already existing Eclipse Che instance [started]
[11:50:02] Verify if Eclipse Che is deployed into namespace "eclipse-che" [started]
[11:50:02] Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not [title changed]
[11:50:02] Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not [completed]
[11:50:02] 👀  Looking for an already existing Eclipse Che instance [completed]
[11:50:02] Check if OIDC Provider installed [started]
[11:50:02] Check if OIDC Provider installed [skipped]
[11:50:02] → Dex will be automatically installed as OIDC Identity Provider
[11:50:02] 🧪  DevWorkspace engine [started]
[11:50:02] Verify cert-manager installation [started]
[11:50:02] Check Cert Manager deployment [started]
[11:50:02] Check Cert Manager deployment...not deployed [title changed]
[11:50:02] Check Cert Manager deployment...not deployed [completed]
[11:50:02] Deploy Cert Manager [started]
[11:50:04] Deploy Cert Manager...done [title changed]
[11:50:04] Deploy Cert Manager...done [completed]
[11:50:04] Wait for Cert Manager [started]
[11:55:[23](https://github.com/eclipse-che/che-plugin-registry/runs/5092423006?check_suite_focus=true#step:12:23)] Wait for Cert Manager [failed]
[11:55:23] → ERR_TIMEOUT: Timeout set to pod ready timeout 600000
[11:55:23] Verify cert-manager installation [failed]
[11:55:23] → ERR_TIMEOUT: Timeout set to pod ready timeout 600000
[11:55:23] 🧪  DevWorkspace engine [failed]
[11:55:23] → ERR_TIMEOUT: Timeout set to pod ready timeout 600000
    Error: Command server:deploy failed. Error log: 
    /home/runner/.cache/chectl/error.log. Eclipse Che logs: 
    /tmp/chectl-logs/16442[34](https://github.com/eclipse-che/che-plugin-registry/runs/5092423006?check_suite_focus=true#step:12:34)601813.
stack=Error: Command failed with exit code 2: chectl server:deploy --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=/tmp/custom-resource-patch.yaml
    Error: Command server:deploy failed. Error log: 
    /home/runner/.cache/chectl/error.log. Eclipse Che logs: 
    /tmp/chectl-logs/164[42](https://github.com/eclipse-che/che-plugin-registry/runs/5092423006?check_suite_focus=true#step:12:42)3[46](https://github.com/eclipse-che/che-plugin-registry/runs/5092423006?check_suite_focus=true#step:12:46)01813.
```

**Comment by dmytro-ndp** [comment]
@l0rd, @benoitf: "503 Server error" has been reproduced with minikube v1.24.0 in GitHub action with Eclipse Che stable and next:
- https://github.com/eclipse-che/che-plugin-registry/runs/5220869436?check_suite_focus=true
- https://github.com/eclipse-che/che-plugin-registry/runs/5220869501?check_suite_focus=true

I will try workaround described in https://github.com/eclipse/che/issues/21125#issuecomment-1031583176
