### ISSUE TITLE
Che-server fails to start on OpenShift with FIPS mode enabled

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20991]
### Is your task related to a problem? Please describe

Che-server fails to start on OpenShift with FIPS mode enabled.

### Describe the solution you'd like

Che-server should be able to successfully start and establish a connection to the underlying k8s/openshift cluster

### Additional context

```
Caused by: AssertionError
	at HttpClientUtils.createHttpClient(HttpClientUtils.java:141)
	at HttpClientUtils.createHttpClient(HttpClientUtils.java:66)
	at KubernetesClientFactory.<init>(KubernetesClientFactory.java:72)
	at CheServerKubernetesClientFactory.<init>(CheServerKubernetesClientFactory.java:43)
	at HttpClientUtils.createHttpClient(HttpClientUtils.java:66)
	at KubernetesClientFactory.<init>(KubernetesClientFactory.java:72)
	at OpenShiftClientFactory.<init>(OpenShiftClientFactory.java:74)
	at OpenShiftClientFactory$$FastClassByGuice$$166068897.GUICE$TRAMPOLINE(<generated>)
	at OpenShiftClientFactory$$FastClassByGuice$$166068897.apply(<generated>)
	at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at ConstructorInjector.provision(ConstructorInjector.java:114)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
```
Could be related https://github.com/fabric8io/kubernetes-client/issues/3582
Openshift fips mode - https://docs.openshift.com/container-platform/4.6/installing/installing-fips.html
Downstream issue https://issues.redhat.com/browse/CRW-2606

**Comment by skabashnyuk** [comment]
After small modification of HttpClientUtils I was able to get the real Exception
```
Caused by: KubernetesClientException: An error has occurred.                                                                                                                                                 │
│     at KubernetesClientException.launderThrowable(KubernetesClientException.java:103)                                                                                                                        │
│     at KubernetesClientException.launderThrowable(KubernetesClientException.java:97)                                                                                                                         │
│     at HttpClientUtils.createHttpClient(HttpClientUtils.java:160)                                                                                                                                            │
│     at HttpClientUtils.createHttpClient(HttpClientUtils.java:85)                                                                                                                                             │
│     at KubernetesClientFactory.<init>(KubernetesClientFactory.java:77)                                                                                                                                       │
│     at OpenShiftClientFactory.<init>(OpenShiftClientFactory.java:72)                                                                                                                                         │
│     at OpenShiftClientFactory$$FastClassByGuice$$171156543.GUICE$TRAMPOLINE(<generated>)                                                                                                                     │
│     at OpenShiftClientFactory$$FastClassByGuice$$171156543.apply(<generated>)                                                                                                                                │
│     at java.base/NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                             │
│     at java.base/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                           │
│     at java.base/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                   │
│     at java.base/Method.invoke(Method.java:566)                                                                                                                                                              │
│     at Bootstrap.start(Bootstrap.java:345)                                                                                                                                                                   │
│     at Bootstrap.main(Bootstrap.java:476)                                                                                                                                                                    │
│ Caused by: KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used                                                                                                                         │
│     at java.base/SSLContextImpl.chooseTrustManager(SSLContextImpl.java:133)                                                                                                                                  │
│     at java.base/SSLContextImpl.engineInit(SSLContextImpl.java:95)                                                                                                                                           │
│     at java.base/SSLContext.init(SSLContext.java:297)                                                                                                                                                        │
│     at SSLUtils.sslContext(SSLUtils.java:86)                                                                                                                                                                 │
│     at HttpClientUtils.createHttpClient(HttpClientUtils.java:157)                                                                                                                                            │
│     ... 60 more
```

**Comment by skabashnyuk** [comment]
Blocked by this https://github.com/fabric8io/kubernetes-client/issues/3582 .

**Comment by dayglo** [comment]
We've hit this issues while using Openshift dev spaces. Whats the best way to turn this off?
