### ISSUE TITLE
Cannot start a workspace in Che with che-server engine

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21016]
### Describe the bug

Workspace fails to start when Che is switched to `che-server` engine.

### Che version

next (development version)

### Steps to reproduce

1. Start Che and switch the engine to `che-workspace`: `oc patch checluster/eclipse-che -n eclipse-che --type=json -p '[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": false}]'`.
2. Start a workspace.
3. See: an error appears:
![screenshot-che-eclipse-che apps ci-ln-bpk4232-72292 origin-ci-int-gce dev rhcloud com-2022 01 13-15_34_28](https://user-images.githubusercontent.com/7668752/149341133-20d39a9d-228e-4902-93b1-5afb6188ff35.png)

### Expected behavior

The workspace must start successfully.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS

### Eclipse Che Logs

```shell
2022-01-13 13:34:07,829[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 257]  - Failed to start Kubernetes runtime of workspace workspace6g9puojxs3mntvjk.
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Plugins installation process timed out
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.WaitBrokerResult.execute(WaitBrokerResult.java:75)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.DeployBroker.execute(DeployBroker.java:129)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.PrepareStorage.execute(PrepareStorage.java:76)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.ListenBrokerEvents.execute(ListenBrokerEvents.java:63)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager.getTooling(PluginBrokerManager.java:129)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner.provision(SidecarToolingProvisioner.java:90)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.provisionWorkspace(KubernetesInternalRuntime.java:288)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:204)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:139)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:1016)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-01-13 13:34:07,984[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 1042]  - Workspace 'kube:admin:wksp-nk80' with id 'workspace6g9puojxs3mntvjk' start failed
```
```


### Additional context

_No response_

**Comment by svor** [comment]
is not relevant anymore
