### ISSUE TITLE
Error 401 when cloning a public repository with github oAuth enabled

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21014]
### Describe the bug

If I configure github oAuth and then I try to open a link from a PUBLIC repository (example https://github.com/che-samples/java-spring-petclinic/tree/devfilev2) , I got 401 error on `resolver/.che/che-theia-plugins.yaml` file call

### Che version

next (development version)

### Steps to reproduce

1. install che
2. setup github oAuth by configuring a secret / https://www.eclipse.org/che/docs/next/administration-guide/configuring-authorization/#enabling-authentication-with-social-accounts-and-brokering_che
3. start a workspace with https://che-server#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2

I've a 401 error

If I import a private repository, then it works for public repository afterwards

### Expected behavior

Able to start a workspace from a public repository

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux, other (please specify in additional context)

**Comment by mshaposhnik** [comment]
Reproduced. Stack trace:
```
2022-01-14 11:10:57,522[io-8080-exec-10]  [ERROR] [thubPersonalAccessTokenFetcher 207]  - Unexpected status code 401 (GET https://api.github.com/user) 401
org.eclipse.che.api.factory.server.scm.exception.ScmCommunicationException: Unexpected status code 401 (GET https://api.github.com/user) 401
	at org.eclipse.che.api.factory.server.github.GithubApiClient.executeRequest(GithubApiClient.java:181)
	at org.eclipse.che.api.factory.server.github.GithubApiClient.getTokenScopes(GithubApiClient.java:135)
	at org.eclipse.che.api.factory.server.github.GithubPersonalAccessTokenFetcher.isValid(GithubPersonalAccessTokenFetcher.java:204)
	at org.eclipse.che.api.factory.server.scm.ScmPersonalAccessTokenFetcher.isValid(ScmPersonalAccessTokenFetcher.java:65)
	at org.eclipse.che.api.factory.server.scm.kubernetes.KubernetesPersonalAccessTokenManager.get(KubernetesPersonalAccessTokenManager.java:159)
	at org.eclipse.che.api.factory.server.scm.AuthorizingFileContentProvider.fetchContent(AuthorizingFileContentProvider.java:58)
	at org.eclipse.che.api.factory.server.urlfactory.URLFactoryBuilder.createFactoryFromDevfile(URLFactoryBuilder.java:114)
	at org.eclipse.che.api.factory.server.github.GithubFactoryParametersResolver.createFactory(GithubFactoryParametersResolver.java:106)
	at org.eclipse.che.api.factory.server.FactoryService.resolveFactory(FactoryService.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

**Comment by mshaposhnik** [comment]
Ok so that seems no be not the Che-server issue.
Explanation:
 - Step 0  We have OAuth configured, but user is not logged in yet (we have no user  tokens stored)
 - Step 1  Dashboard asks for existing files (devfile.yaml, extensions.json etc) - they're accessible w/out authentication user to OAuth login; (see green oval on picture)
 - Step 2  Dashboard asks for unexisting file (/.che/che-theia-plugins.yaml) - Che server cannot know is the file is really not exists, or it is hidden by the private repo (since the GitHub responses are exactly the same) - and returns reponse that OAuth login is needed. User must be redirected to it by dashb, but it is not. So it is seems to be a clearly Dashb issue.
 
 
![image](https://user-images.githubusercontent.com/1651062/149512044-e7ce709f-ddc5-461b-8e6e-ae98459d8836.png)

**Comment by benoitf** [comment]
but it looks strange if we're able to say that devfile exists and extensions.json exists but not for `/.che/che-theia-plugins.yaml`

che-server can know if repository exists (public) or not (does not exist or private)
if repository exists, if a file does not exist it's for sure a 404

**Comment by mshaposhnik** [comment]
>che-server can know if repository exists (public) or not (does not exist or private)
Not sure you can know this until logged in

**Comment by benoitf** [comment]
anyway with https://github.com/eclipse/che/issues/20583 even on a public repository we should use oAuth flow so it may be better to implement https://github.com/eclipse/che/issues/20583

**Comment by benoitf** [comment]
>> che-server can know if repository exists (public) or not (does not exist or private)

> Not sure you can know this until logged in

```
curl https://api.github.com/repos/eclipse/che
exists and no 404
```

**Comment by mshaposhnik** [comment]
Than not help much. You need to know if it;s 404 or 401 when not exists.

**Comment by benoitf** [comment]
@mshaposhnik if repository exists, file does not exists = 404
if repository does not exist, then we always need to go to oAuth

in the issue example `https://github.com/che-samples/java-spring-petclinic`is a public repository so file not found is surely a 404
