### ISSUE TITLE
DevWorkspace routing segmentation violation when starting a workspace

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21089]
### Describe the bug

I cannot start any workspace from the samples (I tried Quarkus, SpringBoot and Go). The message is `devworkspace failed to progress past phase 'Starting' for longer than timeout (5m)`.

From the Che operator logs:

```logs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x167eb56]

goroutine 1402 [running]:
github.com/devfile/devworkspace-operator/pkg/config.ExperimentalFeaturesEnabled(...)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/pkg/config/sync.go:90
github.com/devfile/devworkspace-operator/pkg/provision/sync.printDiff(0x1faf260, 0xc000c90780, 0x1faf260, 0xc000c91900, 0x1f91db8, 0xc000e5cbe0)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/pkg/provision/sync/sync.go:128 +0x36
github.com/devfile/devworkspace-operator/pkg/provision/sync.SyncObjectWithCluster(0x1faf260, 0xc000c90780, 0x1f9df58, 0xc00007d720, 0x0, 0x0, 0xc00013a070, 0x1f91db8, 0xc000e5cbe0, 0x1f87f88, ...)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/pkg/provision/sync/sync.go:69 +0x487
github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting.(*DevWorkspaceRoutingReconciler).syncServices(0xc0007db880, 0xc0008e0f00, 0xc000241900, 0x1, 0x1, 0x0, 0x0, 0xc000241900, 0x1, 0x1, ...)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting/sync_services.go:57 +0x3d1
github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting.(*DevWorkspaceRoutingReconciler).Reconcile(0xc0007db880, 0x1f87ff8, 0xc0005cfc80, 0xc000462d20, 0x19, 0xc000c96c30, 0x21, 0xc0005cfc80, 0xc000980000, 0x1b8e5a0, ...)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting/devworkspacerouting_controller.go:182 +0xc88
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005c0640, 0x1f87f50, 0xc0007dbd00, 0x1b354a0, 0xc0005cd820)
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005c0640, 0x1f87f50, 0xc0007dbd00, 0xc000a93700)
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000680b00, 0xc0005c0640, 0x1f87f50, 0xc0007dbd00)
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:210 +0x425
```

### Che version

next (development version)

### Steps to reproduce

Deploy using chectl
Try to start one of the samples

### Expected behavior

The workspace is started correctly

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Amazon

### Eclipse Che Logs

```shell
2022-01-28T22:14:17.838Z	INFO	Binary info 	{"Go version": "go1.16.12"}
2022-01-28T22:14:17.838Z	INFO	Binary info 	{"OS": "linux", "Arch": "amd64"}
2022-01-28T22:14:17.838Z	INFO	Address 	{"Metrics": ":60000"}
2022-01-28T22:14:17.838Z	INFO	Address 	{"Probe": ":6789"}
2022-01-28T22:14:17.838Z	INFO	Operator is running on 	{"Infrastructure": "OpenShift v4.x"}
I0128 22:14:18.895854       1 request.go:668] Waited for 1.045465044s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s
time="2022-01-28T22:14:20Z" level=info msg="Limit cache by selector: app.kubernetes.io/part-of=che.eclipse.org"
2022-01-28T22:14:22.772Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":60000"}
time="2022-01-28T22:14:25Z" level=info msg="Use 'terminationGracePeriodSeconds' 20 sec. from operator deployment."
time="2022-01-28T22:14:25Z" level=info msg="Set up process signal handler"
2022-01-28T22:14:27.718Z	INFO	setup	DevWorkspace support enabled.
2022-01-28T22:14:27.718Z	INFO	setup	starting manager
I0128 22:14:27.718292       1 leaderelection.go:243] attempting to acquire leader lease openshift-operators/e79b08a4.org.eclipse.che...
2022-01-28T22:14:27.718Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
I0128 22:15:07.997951       1 leaderelection.go:253] successfully acquired lease openshift-operators/e79b08a4.org.eclipse.che
2022-01-28T22:15:07.998Z	INFO	controller-runtime.manager.controller.project	Starting EventSource	{"reconciler group": "project.openshift.io", "reconciler kind": "Project", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.998Z	INFO	controller-runtime.manager.controller.project	Starting EventSource	{"reconciler group": "project.openshift.io", "reconciler kind": "Project", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.998Z	INFO	controller-runtime.manager.controller.project	Starting EventSource	{"reconciler group": "project.openshift.io", "reconciler kind": "Project", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.998Z	INFO	controller-runtime.manager.controller.project	Starting EventSource	{"reconciler group": "project.openshift.io", "reconciler kind": "Project", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.998Z	INFO	controller-runtime.manager.controller.project	Starting Controller	{"reconciler group": "project.openshift.io", "reconciler kind": "Project"}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:07.999Z	INFO	controller-runtime.manager.controller.checluster	Starting Controller	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster"}
2022-01-28T22:15:08.000Z	INFO	controller-runtime.manager.controller.checlusterbackup-controller	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheClusterBackup", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.000Z	INFO	controller-runtime.manager.controller.checlusterbackup-controller	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheClusterBackup", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.000Z	INFO	controller-runtime.manager.controller.checlusterbackup-controller	Starting Controller	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheClusterBackup"}
2022-01-28T22:15:08.001Z	INFO	controller-runtime.manager.controller.checlusterrestore-controller	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheClusterRestore", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.001Z	INFO	controller-runtime.manager.controller.checlusterrestore-controller	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheClusterRestore", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.001Z	INFO	controller-runtime.manager.controller.checlusterrestore-controller	Starting Controller	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheClusterRestore"}
2022-01-28T22:15:08.001Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.001Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.001Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.001Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.001Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.001Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.checluster	Starting EventSource	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.checluster	Starting Controller	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster"}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.devworkspacerouting	Starting EventSource	{"reconciler group": "controller.devfile.io", "reconciler kind": "DevWorkspaceRouting", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.devworkspacerouting	Starting EventSource	{"reconciler group": "controller.devfile.io", "reconciler kind": "DevWorkspaceRouting", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.devworkspacerouting	Starting EventSource	{"reconciler group": "controller.devfile.io", "reconciler kind": "DevWorkspaceRouting", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.devworkspacerouting	Starting EventSource	{"reconciler group": "controller.devfile.io", "reconciler kind": "DevWorkspaceRouting", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.devworkspacerouting	Starting EventSource	{"reconciler group": "controller.devfile.io", "reconciler kind": "DevWorkspaceRouting", "source": "kind source: /, Kind="}
2022-01-28T22:15:08.002Z	INFO	controller-runtime.manager.controller.devworkspacerouting	Starting Controller	{"reconciler group": "controller.devfile.io", "reconciler kind": "DevWorkspaceRouting"}
2022-01-28T22:15:08.103Z	INFO	controller-runtime.manager.controller.checlusterrestore-controller	Starting workers	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheClusterRestore", "worker count": 1}
2022-01-28T22:15:08.108Z	INFO	controller-runtime.manager.controller.project	Starting workers	{"reconciler group": "project.openshift.io", "reconciler kind": "Project", "worker count": 1}
2022-01-28T22:15:08.108Z	INFO	controller-runtime.manager.controller.devworkspacerouting	Starting workers	{"reconciler group": "controller.devfile.io", "reconciler kind": "DevWorkspaceRouting", "worker count": 1}
2022-01-28T22:15:08.109Z	INFO	controllers.DevWorkspaceRouting	Reconciling DevWorkspaceRouting	{"Request.Namespace": "che-kube-admin-che-mpgfgk", "Request.Name": "routing-workspace5de9e3afd12647a5", "devworkspace_id": "workspace5de9e3afd12647a5"}
2022-01-28T22:15:08.109Z	INFO	controllers.DevWorkspaceRouting	controller not ready for devworkspace routing. Retrying	{"Request.Namespace": "che-kube-admin-che-mpgfgk", "Request.Name": "routing-workspace5de9e3afd12647a5", "devworkspace_id": "workspace5de9e3afd12647a5", "DelayMs": 1000}
2022-01-28T22:15:08.112Z	INFO	controller-runtime.manager.controller.checluster	Starting workers	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "worker count": 1}
2022-01-28T22:15:08.118Z	INFO	controller-runtime.manager.controller.checlusterbackup-controller	Starting workers	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheClusterBackup", "worker count": 1}
2022-01-28T22:15:08.118Z	INFO	controller-runtime.manager.controller.checluster	Starting workers	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "worker count": 1}
2022-01-28T22:15:08.134Z	INFO	controllers.DevWorkspaceRouting	Reconciling DevWorkspaceRouting	{"Request.Namespace": "che-kube-admin-che-mpgfgk", "Request.Name": "routing-workspace5de9e3afd12647a5", "devworkspace_id": "workspace5de9e3afd12647a5"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x167eb56]

goroutine 1402 [running]:
github.com/devfile/devworkspace-operator/pkg/config.ExperimentalFeaturesEnabled(...)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/pkg/config/sync.go:90
github.com/devfile/devworkspace-operator/pkg/provision/sync.printDiff(0x1faf260, 0xc000c90780, 0x1faf260, 0xc000c91900, 0x1f91db8, 0xc000e5cbe0)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/pkg/provision/sync/sync.go:128 +0x36
github.com/devfile/devworkspace-operator/pkg/provision/sync.SyncObjectWithCluster(0x1faf260, 0xc000c90780, 0x1f9df58, 0xc00007d720, 0x0, 0x0, 0xc00013a070, 0x1f91db8, 0xc000e5cbe0, 0x1f87f88, ...)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/pkg/provision/sync/sync.go:69 +0x487
github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting.(*DevWorkspaceRoutingReconciler).syncServices(0xc0007db880, 0xc0008e0f00, 0xc000241900, 0x1, 0x1, 0x0, 0x0, 0xc000241900, 0x1, 0x1, ...)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting/sync_services.go:57 +0x3d1
github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting.(*DevWorkspaceRoutingReconciler).Reconcile(0xc0007db880, 0x1f87ff8, 0xc0005cfc80, 0xc000462d20, 0x19, 0xc000c96c30, 0x21, 0xc0005cfc80, 0xc000980000, 0x1b8e5a0, ...)
	/che-operator/vendor/github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting/devworkspacerouting_controller.go:182 +0xc88
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005c0640, 0x1f87f50, 0xc0007dbd00, 0x1b354a0, 0xc0005cd820)
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005c0640, 0x1f87f50, 0xc0007dbd00, 0xc000a93700)
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000680b00, 0xc0005c0640, 0x1f87f50, 0xc0007dbd00)
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:210 +0x425
```

**Comment by l0rd** [comment]
Closing as I am not able to reproduce it anymore

**Comment by amisevsk** [comment]
Context: In some cases, Che Operator was briefly vulnerable to hitting a panic when it needed to update routes. This issue was introduced in https://github.com/eclipse-che/che-operator/pull/1302, fixed in DWO in https://github.com/devfile/devworkspace-operator/commit/69be85cdf34d1cb7d4aafc85cdd9c8a809e27a09, and included in Che Operator in https://github.com/eclipse-che/che-operator/pull/1306. 

The cause of the actual issue is sporadic; for most workspaces everything functions fine, but as soon as some route/service/ingress needed to be updated the Che Operator would enter a crashloop.

**Comment by l0rd** [comment]
@amisevsk thanks for the explanation ;-)
