### ISSUE TITLE
Empty page and "Unauthorized! Configured service account doesn't have access" server error after login to Che on minikube as Dex user

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#21126]
### Describe the bug

Empty page and "Unauthorized! Configured service account doesn't have access" server error when try to login to Eclipse Che on minikube as "che@eclipse.org", "user1@che" Dex users.

### Che version

next (development version)

### Steps to reproduce

1. Install minikube v1.25.1
2. Execute `minikube start --vm-driver=docker --addons=ingress --cpus 2 --memory 6500`
3. Create eclipse-che namespace: `kubectl create namespace eclipse-che`
4. Download and unpack [chectl 0.0.20220204-next.c1ecf46](https://github.com/che-incubator/chectl/releases/download/20220204150459/chectl-linux-x64.tar.gz)
5. Deploy Eclipse Che to minikube:
```
chectl/bin/chectl server:deploy \
                        --k8spodreadytimeout=600000 \
                        --k8spodwaittimeout=600000 \
                        --k8spoddownloadimagetimeout=600000 \
                        --listr-renderer=verbose \
                        --platform=minikube \
                        --telemetry=off
```
6. Go to https://192.168.49.2.nip.io/dashboard/
7. Log into Eclipse Che as `che@eclipse.org:admin`

### Expected behavior

Eclipse Che Dashboard page is opened.

### Runtime

minikube

### Screenshots

![Screenshot from 2022-02-06 00-36-17](https://user-images.githubusercontent.com/1197777/152662956-2475ab6c-74cb-4f73-b05d-52c1a5ad68e8.png)

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs
[che-logs.zip](https://github.com/eclipse/che/files/8009157/che-logs.zip)

Che server error log:
```
2022-02-05 22:33:11,648[nio-8080-exec-4]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2022-02-05 22:33:11
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/admin-che/secrets/workspace-credentials-secret. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:686)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:623)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:565)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:526)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:493)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:475)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:807)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:188)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:155)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:88)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.configurator.CredentialsSecretConfigurator.configure(CredentialsSecretConfigurator.java:43)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespaceFactory.configureNamespace(KubernetesNamespaceFactory.java:570)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespaceFactory.getOrCreate(KubernetesNamespaceFactory.java:334)
	at org.eclipse.che.workspace.infrastructure.kubernetes.provision.NamespaceProvisioner.provision(NamespaceProvisioner.java:42)
	at org.eclipse.che.workspace.infrastructure.kubernetes.api.server.KubernetesNamespaceService.provision(KubernetesNamespaceService.java:95)
```

Chectl logs:
```
$ chectl/bin/chectl server:deploy                         --k8spodreadytimeout=600000                         --k8spodwaittimeout=600000                         --k8spoddownloadimagetimeout=600000                         --listr-renderer=verbose                         --platform=minikube                         --telemetry=off
› Installer type is set to: 'operator'
[00:13:12] Verify Kubernetes API [started]
› Current Kubernetes context: 'minikube'
[00:13:12] Verify Kubernetes API...OK [title changed]
[00:13:12] Verify Kubernetes API...OK [completed]
[00:13:12] 👀  Looking for an already existing Eclipse Che instance [started]
[00:13:12] Verify if Eclipse Che is deployed into namespace "eclipse-che" [started]
[00:13:13] Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not [title changed]
[00:13:13] Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not [completed]
[00:13:13] 👀  Looking for an already existing Eclipse Che instance [completed]
[00:13:13] Check if OIDC Provider installed [started]
[00:13:13] Check if OIDC Provider installed [skipped]
[00:13:13] → Dex will be automatically installed as OIDC Identity Provider
[00:13:13] 🧪  DevWorkspace engine [started]
[00:13:13] Verify cert-manager installation [started]
[00:13:13] Check Cert Manager deployment [started]
[00:13:13] Check Cert Manager deployment...not deployed [title changed]
[00:13:13] Check Cert Manager deployment...not deployed [completed]
[00:13:13] Deploy Cert Manager [started]
[00:13:18] Deploy Cert Manager...done [title changed]
[00:13:18] Deploy Cert Manager...done [completed]
[00:13:18] Wait for Cert Manager [started]
[00:13:28] Wait for Cert Manager...ready [title changed]
[00:13:28] Wait for Cert Manager...ready [completed]
[00:13:28] Verify cert-manager installation [completed]
[00:13:28] 🧪  DevWorkspace engine [completed]
[00:13:28] ✈️  Minikube preflight checklist [started]
[00:13:29] Verify if kubectl is installed [started]
[00:13:29] Verify if kubectl is installed [completed]
[00:13:29] Verify if minikube is installed [started]
[00:13:29] Verify if minikube is installed [completed]
[00:13:29] Verify if minikube is running [started]
[00:13:30] Verify if minikube is running [completed]
[00:13:30] Start minikube [started]
[00:13:30] Start minikube [skipped]
[00:13:30] → Minikube is already running.
[00:13:30] Check Kubernetes version [started]
[00:13:30] Check Kubernetes version: Found v1.23.1. [title changed]
[00:13:30] Check Kubernetes version: Found v1.23.1. [completed]
[00:13:30] Verify if minikube ingress addon is enabled [started]
[00:13:30] Verify if minikube ingress addon is enabled [completed]
[00:13:30] Enable minikube ingress addon [started]
[00:13:30] Enable minikube ingress addon [skipped]
[00:13:30] → Ingress addon is already enabled.
[00:13:30] Retrieving minikube IP and domain for ingress URLs [started]
[00:13:30] Retrieving minikube IP and domain for ingress URLs...192.168.49.2.nip.io. [title changed]
[00:13:30] Retrieving minikube IP and domain for ingress URLs...192.168.49.2.nip.io. [completed]
[00:13:30] Checking minikube version [started]
[00:13:30] Checking minikube version... 1.25.1 [title changed]
[00:13:30] Checking minikube version... 1.25.1 [completed]
[00:13:30] Check if cluster accessible [started]
[00:13:30] Check if cluster accessible [skipped]
[00:13:30] ✈️  Minikube preflight checklist [completed]
[00:13:30] Following Eclipse Che logs [started]
[00:13:30] Start following Operator logs [started]
[00:13:30] Start following Operator logs...done [title changed]
[00:13:30] Start following Operator logs...done [completed]
[00:13:30] Start following Eclipse Che Server logs [started]
[00:13:30] Start following Eclipse Che Server logs...done [title changed]
[00:13:30] Start following Eclipse Che Server logs...done [completed]
[00:13:30] Start following PostgreSQL logs [started]
[00:13:30] Start following PostgreSQL logs...done [title changed]
[00:13:30] Start following PostgreSQL logs...done [completed]
[00:13:30] Start following Keycloak logs [started]
[00:13:30] Start following Keycloak logs...done [title changed]
[00:13:30] Start following Keycloak logs...done [completed]
[00:13:30] Start following Plug-in Registry logs [started]
[00:13:30] Start following Plug-in Registry logs...done [title changed]
[00:13:30] Start following Plug-in Registry logs...done [completed]
[00:13:30] Start following Devfile Registry logs [started]
[00:13:30] Start following Devfile Registry logs...done [title changed]
[00:13:30] Start following Devfile Registry logs...done [completed]
[00:13:30] Start following Eclipse Che Dashboard logs [started]
[00:13:30] Start following Eclipse Che Dashboard logs...done [title changed]
[00:13:30] Start following Eclipse Che Dashboard logs...done [completed]
[00:13:30] Start following namespace events [started]
[00:13:30] Start following namespace events...done [title changed]
[00:13:30] Start following namespace events...done [completed]
[00:13:30] Following Eclipse Che logs [completed]
[00:13:30] Create Namespace eclipse-che [started]
[00:13:31] Create Namespace eclipse-che...[Exists] [title changed]
[00:13:31] Create Namespace eclipse-che...[Exists] [completed]
[00:13:31] Deploy Dex [started]
[00:13:31] Create namespace: dex [started]
[00:13:31] Create namespace: dex...[OK] [title changed]
[00:13:31] Create namespace: dex...[OK] [completed]
[00:13:31] Provide Dex certificate [started]
[00:13:31] Check Cert Manager deployment [started]
[00:13:31] Check Cert Manager deployment...already deployed [title changed]
[00:13:31] Check Cert Manager deployment...already deployed [completed]
[00:13:31] Wait for Cert Manager [started]
[00:13:31] Wait for Cert Manager...ready [title changed]
[00:13:31] Wait for Cert Manager...ready [completed]
[00:13:31] Check Cert Manager CA certificate [started]
[00:13:31] Check Cert Manager CA certificate...generating new one [title changed]
[00:13:33] Check Cert Manager CA certificate...generating new one [completed]
[00:13:33] Set up Eclipse Che certificates issuer [started]
[00:13:33] Set up Eclipse Che certificates issuer...done [title changed]
[00:13:33] Set up Eclipse Che certificates issuer...done [completed]
[00:13:33] Request certificate for dnsNames: [dex.192.168.49.2.nip.io,*.dex.192.168.49.2.nip.io] [started]
[00:13:33] Request self-signed certificate [title changed]
[00:13:33] Request self-signed certificate...done [title changed]
[00:13:33] Request self-signed certificate...done [completed]
[00:13:33] Wait for certificate [started]
[00:13:33] Wait for self-signed certificate [title changed]
[00:13:34] Wait for self-signed certificate...ready [title changed]
[00:13:34] Wait for self-signed certificate...ready [completed]
[00:13:34] Read Dex certificate [started]
[00:13:34] Read Dex certificate...[OK] [title changed]
[00:13:34] Read Dex certificate...[OK] [completed]
[00:13:34] Save Dex certificate [started]
[00:13:34] Save Dex certificate...[OK: /tmp/dex-ca.crt] [title changed]
[00:13:34] Save Dex certificate...[OK: /tmp/dex-ca.crt] [completed]
[00:13:34] Add Dex certificate to Eclipse Che certificates bundle [started]
[00:13:34] Add Dex certificate to Eclipse Che certificates bundle...[OK] [title changed]
[00:13:34] Add Dex certificate to Eclipse Che certificates bundle...[OK] [completed]
[00:13:34] Provide Dex certificate [completed]
[00:13:34] Create Dex service account [started]
[00:13:34] Create Dex service account...[OK] [title changed]
[00:13:34] Create Dex service account...[OK] [completed]
[00:13:34] Create Dex cluster role [started]
[00:13:34] Create Dex cluster role...[OK] [title changed]
[00:13:34] Create Dex cluster role...[OK] [completed]
[00:13:34] Create Dex cluster role binding [started]
[00:13:34] Create Dex cluster role binding...[OK] [title changed]
[00:13:34] Create Dex cluster role binding...[OK] [completed]
[00:13:34] Create Dex service [started]
[00:13:34] Create Dex service...[OK] [title changed]
[00:13:34] Create Dex service...[OK] [completed]
[00:13:34] Create Dex ingress [started]
[00:13:34] Create Dex ingress...[OK] [title changed]
[00:13:34] Create Dex ingress...[OK] [completed]
[00:13:34] Generate Dex username and password [started]
[00:13:34] Generate Dex username and password...[OK: admin:admin] [title changed]
[00:13:34] Generate Dex username and password...[OK: admin:admin] [completed]
[00:13:34] Create Dex configmap [started]
[00:13:34] Create Dex configmap...[OK] [title changed]
[00:13:34] Create Dex configmap...[OK] [completed]
[00:13:34] Create Dex deployment [started]
[00:13:34] Create Dex deployment...[OK] [title changed]
[00:13:34] Create Dex deployment...[OK] [completed]
[00:13:34] Wait for Dex is ready [started]
[00:13:35] Wait for Dex is ready...[OK] [title changed]
[00:13:35] Wait for Dex is ready...[OK] [completed]
[00:13:35] Configure API server [started]
[00:13:35] Create /etc/ca-certificates directory [started]
[00:13:36] Create /etc/ca-certificates directory...[OK] [title changed]
[00:13:36] Create /etc/ca-certificates directory...[OK] [completed]
[00:13:36] Copy Dex certificate into Minikube [started]
[00:13:36] Copy Dex certificate into Minikube...[OK] [title changed]
[00:13:36] Copy Dex certificate into Minikube...[OK] [completed]
[00:13:36] Configure Minikube API server [started]
[00:13:44] Configure Minikube API server...[OK] [title changed]
[00:13:44] Configure Minikube API server...[OK] [completed]
[00:13:44] Wait for Minikube API server [started]
[00:14:14] Wait for Minikube API server...[OK] [title changed]
[00:14:14] Wait for Minikube API server...[OK] [completed]
[00:14:14] Configure API server [completed]
[00:14:14] Deploy Dex [completed]
[00:14:14] 🏃‍  Running the Eclipse Che operator [started]
[00:14:14] Create ServiceAccount che-operator in namespace eclipse-che [started]
[00:14:14] Create ServiceAccount che-operator in namespace eclipse-che...done. [title changed]
[00:14:14] Create ServiceAccount che-operator in namespace eclipse-che...done. [completed]
[00:14:14] Read Roles and Bindings [started]
[00:14:14] Read Roles and Bindings...done. [title changed]
[00:14:14] Read Roles and Bindings...done. [completed]
[00:14:14] Creating Roles and Bindings [started]
[00:14:15] Creating Roles and Bindings...done. [title changed]
[00:14:15] Creating Roles and Bindings...done. [completed]
[00:14:15] Create CRD checlusters.org.eclipse.che [started]
[00:14:15] Create CRD checlusters.org.eclipse.che...done. [title changed]
[00:14:15] Create CRD checlusters.org.eclipse.che...done. [completed]
[00:14:15] Waiting 5 seconds for the new Kubernetes resources to get flushed [started]
[00:14:20] Waiting 5 seconds for the new Kubernetes resources to get flushed...done. [title changed]
[00:14:20] Waiting 5 seconds for the new Kubernetes resources to get flushed...done. [completed]
[00:14:20] Create deployment che-operator in namespace eclipse-che [started]
[00:14:20] Create deployment che-operator in namespace eclipse-che...done. [title changed]
[00:14:20] Create deployment che-operator in namespace eclipse-che...done. [completed]
[00:14:20] Operator pod bootstrap [started]
[00:14:20] Scheduling [started]
[00:14:20] Scheduling...done [title changed]
[00:14:20] Scheduling...done [completed]
[00:14:20] Downloading images [started]
[00:15:54] Downloading images...done [title changed]
[00:15:54] Downloading images...done [completed]
[00:15:54] Starting [started]
[00:16:00] Starting...done [title changed]
[00:16:00] Starting...done [completed]
[00:16:00] Operator pod bootstrap [completed]
[00:16:00] Prepare Eclipse Che cluster CR [started]
[00:16:00] Prepare Eclipse Che cluster CR...Done. [title changed]
[00:16:00] Prepare Eclipse Che cluster CR...Done. [completed]
[00:16:00] Create the Custom Resource of type checlusters.org.eclipse.che [started]
[00:16:00] Create the Custom Resource of type checlusters.org.eclipse.che in the namespace eclipse-che [title changed]
[00:16:00] Create the Custom Resource of type checlusters.org.eclipse.che in the namespace eclipse-che...done. [title changed]
[00:16:00] Create the Custom Resource of type checlusters.org.eclipse.che in the namespace eclipse-che...done. [completed]
[00:16:00] 🏃‍  Running the Eclipse Che operator [completed]
[00:16:00] ✅  Post installation checklist [started]
[00:16:00] PostgreSQL pod bootstrap [started]
[00:16:00] Scheduling [started]
[00:18:55] Scheduling...done [title changed]
[00:18:55] Scheduling...done [completed]
[00:18:55] Downloading images [started]
[00:21:52] Downloading images...done [title changed]
[00:21:52] Downloading images...done [completed]
[00:21:52] Starting [started]
[00:22:15] Starting...done [title changed]
[00:22:15] Starting...done [completed]
[00:22:15] PostgreSQL pod bootstrap [completed]
[00:22:15] Keycloak pod bootstrap [started]
[00:22:15] Keycloak pod bootstrap...skipped [title changed]
[00:22:15] Keycloak pod bootstrap...skipped [completed]
[00:22:15] Devfile Registry pod bootstrap [started]
[00:22:15] Scheduling [started]
[00:22:19] Scheduling...done [title changed]
[00:22:19] Scheduling...done [completed]
[00:22:19] Downloading images [started]
[00:23:07] Downloading images...done [title changed]
[00:23:07] Downloading images...done [completed]
[00:23:07] Starting [started]
[00:23:09] Starting...done [title changed]
[00:23:09] Starting...done [completed]
[00:23:09] Devfile Registry pod bootstrap [completed]
[00:23:09] Plug-in Registry pod bootstrap [started]
[00:23:09] Scheduling [started]
[00:23:12] Scheduling...done [title changed]
[00:23:12] Scheduling...done [completed]
[00:23:12] Downloading images [started]
[00:23:43] Downloading images...done [title changed]
[00:23:43] Downloading images...done [completed]
[00:23:43] Starting [started]
[00:23:52] Starting...done [title changed]
[00:23:52] Starting...done [completed]
[00:23:52] Plug-in Registry pod bootstrap [completed]
[00:23:52] Eclipse Che Dashboard pod bootstrap [started]
[00:23:52] Scheduling [started]
[00:23:56] Scheduling...done [title changed]
[00:23:56] Scheduling...done [completed]
[00:23:56] Downloading images [started]
[00:24:50] Downloading images...done [title changed]
[00:24:50] Downloading images...done [completed]
[00:24:50] Starting [started]
[00:24:56] Starting...done [title changed]
[00:24:56] Starting...done [completed]
[00:24:56] Eclipse Che Dashboard pod bootstrap [completed]
[00:24:56] Eclipse Che Server pod bootstrap [started]
[00:24:56] Scheduling [started]
[00:25:04] Scheduling...done [title changed]
[00:25:04] Scheduling...done [completed]
[00:25:04] Downloading images [started]
[00:28:31] Downloading images...done [title changed]
[00:28:31] Downloading images...done [completed]
[00:28:31] Starting [started]
[00:29:39] Starting...done [title changed]
[00:29:39] Starting...done [completed]
[00:29:39] Eclipse Che Server pod bootstrap [completed]
[00:29:39] Eclipse Che status check [started]
[00:29:39] Eclipse Che status check...done [title changed]
[00:29:39] Eclipse Che status check...done [completed]
[00:29:39] ✅  Post installation checklist [completed]
[00:29:39] Retrieving Che self-signed CA certificate [started]
[00:29:39] Retrieving Che self-signed CA certificate...OK [title changed]
[00:29:39] Retrieving Che self-signed CA certificate...OK [completed]
[00:29:39] Prepare post installation output [started]
[00:29:44] Prepare post installation output...done [title changed]
[00:29:44] Prepare post installation output...done [completed]
[00:29:44] Show important messages [started]
[00:29:44] Eclipse Che 'next' has been successfully deployed. [started]
[00:29:44] Eclipse Che 'next' has been successfully deployed. [completed]
[00:29:44] Documentation             : https://www.eclipse.org/che/docs/ [started]
[00:29:44] Documentation             : https://www.eclipse.org/che/docs/ [completed]
[00:29:44] ------------------------------------------------------------------------------- [started]
[00:29:44] ------------------------------------------------------------------------------- [completed]
[00:29:44] Users Dashboard           : https://192.168.49.2.nip.io/dashboard/ [started]
[00:29:44] Users Dashboard           : https://192.168.49.2.nip.io/dashboard/ [completed]
[00:29:44] ------------------------------------------------------------------------------- [started]
[00:29:44] ------------------------------------------------------------------------------- [completed]
[00:29:44] Plug-in Registry          : https://192.168.49.2.nip.io/plugin-registry/v3/ [started]
[00:29:44] Plug-in Registry          : https://192.168.49.2.nip.io/plugin-registry/v3/ [completed]
[00:29:44] Devfile Registry          : https://192.168.49.2.nip.io/devfile-registry/ [started]
[00:29:44] Devfile Registry          : https://192.168.49.2.nip.io/devfile-registry/ [completed]
[00:29:44] ------------------------------------------------------------------------------- [started]
[00:29:44] ------------------------------------------------------------------------------- [completed]
[00:29:44] Dex user credentials      : che@eclipse.org:admin [started]
[00:29:44] Dex user credentials      : che@eclipse.org:admin [completed]
[00:29:44] Dex user credentials      : user1@che:password [started]
[00:29:44] Dex user credentials      : user1@che:password [completed]
[00:29:44] Dex user credentials      : user2@che:password [started]
[00:29:44] Dex user credentials      : user2@che:password [completed]
[00:29:44] Dex user credentials      : user3@che:password [started]
[00:29:44] Dex user credentials      : user3@che:password [completed]
[00:29:44] Dex user credentials      : user4@che:password [started]
[00:29:44] Dex user credentials      : user4@che:password [completed]
[00:29:44] Dex user credentials      : user5@che:password [started]
[00:29:44] Dex user credentials      : user5@che:password [completed]
[00:29:44] ------------------------------------------------------------------------------- [started]
[00:29:44] ------------------------------------------------------------------------------- [completed]
[00:29:44] Show important messages [completed]
Command server:deploy has completed successfully in 16:32.
```

**Comment by debovema** [comment]
I'm able to reproduce using ```minikube start --addons=ingress --vm=true --memory=16384 --cpus=4```for minikube initialization.

**Comment by metlos** [comment]
I can't reproduce with minikube 1.23.2. Maybe this has something to do with Kubernetes version?

**Comment by dmytro-ndp** [comment]
@metlos: yep, it could be minikube version specific, for v1.25.1

@debovema: could you, please, write minikube version you reproduced the issue on?

**Comment by metlos** [comment]
reproduced on minikube 1.25.1. weird...

**Comment by tolusha** [comment]
Duplicates
https://github.com/eclipse/che/issues/20984
