### ISSUE TITLE
Unable to Load Dashboard Page

### ISSUE THREAD

**Issue by cmille62** [eclipse/che#21143]
### Describe the bug

Che Dashboard crashes due to errors on the front end.

Che Dashboard redirects to keycloak, logs user in, and redirects back to che daskboard, here the user's token (/api/token) is valid and the user's (api/user) is also populated properly. These are the logs in the front end: 

`
client.f26467f483f9ac419981.js:1 Skip keycloak settings field:  che.oidc.auth_server_url
client.f26467f483f9ac419981.js:1 Skip keycloak settings field:  che.oidc.username_claim
client.f26467f483f9ac419981.js:1 Skip keycloak settings field:  che.oidc.oidc_provider
`

`vendor.591bfce3d6abac540979.js:66 WebSocket connection to 'wss://code.url.com/api/websocket?token={token}' failed: `

`react_devtools_backend.js:4061 UD: preload data failed. undefined`
`
react_devtools_backend.js:4061 TypeError: Cannot read properties of undefined (reading 'email')
    at Xe.render (client.f26467f483f9ac419981.js:1:86930)
    at Bi (vendor.591bfce3d6abac540979.js:115:69877)
    at Vi (vendor.591bfce3d6abac540979.js:115:69672)
    at gs (vendor.591bfce3d6abac540979.js:115:105471)
    at lc (vendor.591bfce3d6abac540979.js:115:96718)
    at sc (vendor.591bfce3d6abac540979.js:115:96643)
    at Qs (vendor.591bfce3d6abac540979.js:115:93673)
    at Zs (vendor.591bfce3d6abac540979.js:115:90437)
    at Nc (vendor.591bfce3d6abac540979.js:115:111885)
    at vendor.591bfce3d6abac540979.js:115:113128
`

After that the websocket keeps trying to connect and failing. 

Within my setup, I am using an external keycloak service. 

### Che version

7.42@latest

### Steps to reproduce

1. Deploy Che Helm Chart using ArgoCD
2. Change Keycloak Url / Realm / Client to Custom Keycloak Information
3. Add to the config map the url adapter:
`CHE_KEYCLOAK_JS__ADAPTER__URL: {{ .Values.customOidcUrl }}/js/keycloak.js`
4. Sync Che
5. Go to Che Dashboard url, login, white screen.

### Expected behavior

Dashboard to not show a white, empty screen.

### Runtime

Kubernetes (vanilla)

### Installation method

other (please specify in additional context)

### Environment

Amazon

### Eclipse Che Logs

```shell
Using embedded assembly in /home/user/eclipse-che.
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Listening for transport dt_socket at address: 8000
08-Feb-2022 17:09:25.593 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/10.0.14
08-Feb-2022 17:09:25.680 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 2 2021 22:01:36 UTC
08-Feb-2022 17:09:25.680 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 10.0.14.0
08-Feb-2022 17:09:25.681 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
08-Feb-2022 17:09:25.681 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.117-58.216.amzn2.x86_64
08-Feb-2022 17:09:25.681 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
08-Feb-2022 17:09:25.682 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
08-Feb-2022 17:09:25.682 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.11+9
08-Feb-2022 17:09:25.682 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            AdoptOpenJDK
08-Feb-2022 17:09:25.683 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/user/eclipse-che/tomcat
08-Feb-2022 17:09:25.686 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/user/eclipse-che/tomcat
08-Feb-2022 17:09:25.704 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
08-Feb-2022 17:09:25.704 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
08-Feb-2022 17:09:25.704 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
08-Feb-2022 17:09:25.705 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
08-Feb-2022 17:09:25.705 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
08-Feb-2022 17:09:25.705 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/user/eclipse-che/tomcat/conf/logging.properties
08-Feb-2022 17:09:25.705 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
08-Feb-2022 17:09:25.706 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxRAMPercentage=85.0
08-Feb-2022 17:09:25.708 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.docker.network=bridge
08-Feb-2022 17:09:25.709 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStore=/home/user/cacerts
08-Feb-2022 17:09:25.709 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStorePassword=changeit
08-Feb-2022 17:09:25.709 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dport.http=8080
08-Feb-2022 17:09:25.710 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.home=/home/user/eclipse-che
08-Feb-2022 17:09:25.710 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.logs.dir=/data/logs
08-Feb-2022 17:09:25.712 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.logs.level=INFO
08-Feb-2022 17:09:25.712 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djuli-logback.configurationFile=file:/home/user/eclipse-che/tomcat/conf/tomcat-logger.xml
08-Feb-2022 17:09:25.713 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
08-Feb-2022 17:09:25.713 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
08-Feb-2022 17:09:25.713 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0022
08-Feb-2022 17:09:25.713 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
08-Feb-2022 17:09:25.716 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.local.conf.dir=/etc/conf
08-Feb-2022 17:09:25.716 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
08-Feb-2022 17:09:25.718 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/user/eclipse-che/tomcat
08-Feb-2022 17:09:25.719 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/home/user/eclipse-che/tomcat
08-Feb-2022 17:09:25.719 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/user/eclipse-che/tomcat/temp
08-Feb-2022 17:09:27.399 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
08-Feb-2022 17:09:27.463 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [2888] milliseconds
08-Feb-2022 17:09:27.687 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
08-Feb-2022 17:09:27.688 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.14]
08-Feb-2022 17:09:27.933 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war]
08-Feb-2022 17:09:39.098 WARNING [main] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [104] milliseconds.
08-Feb-2022 17:09:39.152 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war] has finished in [11,219] ms
08-Feb-2022 17:09:39.162 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/api.war]
2022-02-08 17:10:00,052[main]             [INFO ] [.e.c.c.d.JNDIDataSourceFactory 63]   - This=org.eclipse.che.core.db.postgresql.PostgreSQLJndiDataSourceFactory@499b274c obj=ResourceRef[className=javax.sql.DataSource,factoryClassLocation=null,factoryClassName=org.apache.naming.factory.ResourceFactory,{type=scope,content=Shareable},{type=auth,content=Container},{type=singleton,content=true},{type=factory,content=org.eclipse.che.core.db.postgresql.PostgreSQLJndiDataSourceFactory}] name=che Context=org.apache.naming.NamingContext@35be6701 environment={}
2022-02-08 17:10:01,883[main]             [INFO ] [.e.c.a.d.WsMasterServletModule 55]   - Running in classic multi-user mode ...
2022-02-08 17:10:07,117[main]             [INFO ] [o.e.c.m.oidc.OIDCInfoProvider 71]    - Retrieving OpenId configuration from endpoint: https://login.urlcom/auth/realms/realm/.well-known/openid-configuration
2022-02-08 17:10:10,086[main]             [INFO ] [o.e.c.m.oidc.OIDCInfoProvider 80]    - openid configuration = {issuer=https://login.urlcom/auth/realms/realm, authorization_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/auth, token_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/token, introspection_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/token/introspect, userinfo_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/userinfo, end_session_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/logout, frontchannel_logout_session_supported=true, frontchannel_logout_supported=true, jwks_uri=https://login.urlcom/auth/realms/realm/protocol/openid-connect/certs, check_session_iframe=https://login.urlcom/auth/realms/realm/protocol/openid-connect/login-status-iframe.html, grant_types_supported=[authorization_code, implicit, refresh_token, password, client_credentials, urn:ietf:params:oauth:grant-type:device_code, urn:openid:params:grant-type:ciba], response_types_supported=[code, none, id_token, token, id_token token, code id_token, code token, code id_token token], subject_types_supported=[public, pairwise], id_token_signing_alg_values_supported=[PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512], id_token_encryption_alg_values_supported=[RSA-OAEP, RSA-OAEP-256, RSA1_5], id_token_encryption_enc_values_supported=[A256GCM, A192GCM, A128GCM, A128CBC-HS256, A192CBC-HS384, A256CBC-HS512], userinfo_signing_alg_values_supported=[PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512, none], request_object_signing_alg_values_supported=[PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512, none], request_object_encryption_alg_values_supported=[RSA-OAEP, RSA-OAEP-256, RSA1_5], request_object_encryption_enc_values_supported=[A256GCM, A192GCM, A128GCM, A128CBC-HS256, A192CBC-HS384, A256CBC-HS512], response_modes_supported=[query, fragment, form_post, query.jwt, fragment.jwt, form_post.jwt, jwt], registration_endpoint=https://login.urlcom/auth/realms/realm/clients-registrations/openid-connect, token_endpoint_auth_methods_supported=[private_key_jwt, client_secret_basic, client_secret_post, tls_client_auth, client_secret_jwt], token_endpoint_auth_signing_alg_values_supported=[PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512], introspection_endpoint_auth_methods_supported=[private_key_jwt, client_secret_basic, client_secret_post, tls_client_auth, client_secret_jwt], introspection_endpoint_auth_signing_alg_values_supported=[PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512], authorization_signing_alg_values_supported=[PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512], authorization_encryption_alg_values_supported=[RSA-OAEP, RSA-OAEP-256, RSA1_5], authorization_encryption_enc_values_supported=[A256GCM, A192GCM, A128GCM, A128CBC-HS256, A192CBC-HS384, A256CBC-HS512], claims_supported=[aud, sub, iss, auth_time, name, given_name, family_name, preferred_username, email, acr], claim_types_supported=[normal], claims_parameter_supported=true, scopes_supported=[openid, offline_access, username, web-origins, groups, phone, email, address, profile, microprofile-jwt, roles], request_parameter_supported=true, request_uri_parameter_supported=true, require_request_uri_registration=true, code_challenge_methods_supported=[plain, S256], tls_client_certificate_bound_access_tokens=true, revocation_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/revoke, revocation_endpoint_auth_methods_supported=[private_key_jwt, client_secret_basic, client_secret_post, tls_client_auth, client_secret_jwt], revocation_endpoint_auth_signing_alg_values_supported=[PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512], backchannel_logout_supported=true, backchannel_logout_session_supported=true, device_authorization_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/auth/device, backchannel_token_delivery_modes_supported=[poll, ping], backchannel_authentication_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/ext/ciba/auth, backchannel_authentication_request_signing_alg_values_supported=[PS384, ES384, RS384, ES256, RS256, ES512, PS256, PS512, RS512], require_pushed_authorization_requests=false, pushed_authorization_request_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/ext/par/request, mtls_endpoint_aliases={token_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/token, revocation_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/revoke, introspection_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/token/introspect, device_authorization_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/auth/device, registration_endpoint=https://login.urlcom/auth/realms/realm/clients-registrations/openid-connect, userinfo_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/userinfo, pushed_authorization_request_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/ext/par/request, backchannel_authentication_endpoint=https://login.urlcom/auth/realms/realm/protocol/openid-connect/ext/ciba/auth}}
2022-02-08 17:10:13,989[main]             [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - Both KUBERNETES_NAMESPACE and OPENSHIFT_KUBE_PING_NAMESPACE are defined, OPENSHIFT_KUBE_PING_NAMESPACE is deprecated so please remove it
2022-02-08 17:10:13,989[main]             [INFO ] [o.j.p.kubernetes.KUBE_PING 131]      - namespace che set; clustering enabled

-------------------------------------------------------------------
GMS: address=che-7c98444dc-hfk9n-8717, cluster=RemoteSubscriptionChannel, physical address=192.168.56.50:7800
-------------------------------------------------------------------
2022-02-08 17:10:17,411[main]             [INFO ] [o.jgroups.protocols.pbcast.GMS 125]  - che-7c98444dc-hfk9n-8717: no members discovered after 3386 ms: creating cluster as coordinator
2022-02-08 17:10:17,523[main]             [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - Both KUBERNETES_NAMESPACE and OPENSHIFT_KUBE_PING_NAMESPACE are defined, OPENSHIFT_KUBE_PING_NAMESPACE is deprecated so please remove it
2022-02-08 17:10:17,524[main]             [INFO ] [o.j.p.kubernetes.KUBE_PING 131]      - namespace che set; clustering enabled

-------------------------------------------------------------------
GMS: address=che-7c98444dc-hfk9n-6333, cluster=WorkspaceLocks, physical address=192.168.56.50:7801
-------------------------------------------------------------------
2022-02-08 17:10:20,686[main]             [INFO ] [o.jgroups.protocols.pbcast.GMS 125]  - che-7c98444dc-hfk9n-6333: no members discovered after 3145 ms: creating cluster as coordinator
2022-02-08 17:10:20,711[main]             [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - Both KUBERNETES_NAMESPACE and OPENSHIFT_KUBE_PING_NAMESPACE are defined, OPENSHIFT_KUBE_PING_NAMESPACE is deprecated so please remove it
2022-02-08 17:10:20,712[main]             [INFO ] [o.j.p.kubernetes.KUBE_PING 131]      - namespace che set; clustering enabled

-------------------------------------------------------------------
GMS: address=che-7c98444dc-hfk9n-38532, cluster=WorkspaceStateCache, physical address=192.168.56.50:7802
-------------------------------------------------------------------
2022-02-08 17:10:24,003[main]             [INFO ] [o.jgroups.protocols.pbcast.GMS 125]  - che-7c98444dc-hfk9n-38532: no members discovered after 3249 ms: creating cluster as coordinator
2022-02-08 17:10:24,856[main]             [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:postgresql://postgres:5432/dbche (PostgreSQL 9.6)
2022-02-08 17:10:24,906[main]             [INFO ] [o.f.c.i.util.VersionPrinter 44]      - Flyway 4.2.0 by Boxfuse
2022-02-08 17:10:24,939[main]             [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:postgresql://postgres:5432/dbche (PostgreSQL 9.6)
2022-02-08 17:10:25,074[main]             [INFO ] [i.f.CustomSqlMigrationResolver 158]  - Searching for SQL scripts in locations [classpath:che-schema]
2022-02-08 17:10:25,385[main]             [INFO ] [o.f.c.i.command.DbValidate 44]       - Successfully validated 63 migrations (execution time 00:00.314s)
2022-02-08 17:10:25,640[main]             [INFO ] [o.f.c.i.command.DbMigrate 44]        - Current version of schema "public": 7.26.0.1
2022-02-08 17:10:25,641[main]             [INFO ] [o.f.c.i.command.DbMigrate 44]        - Schema "public" is up to date. No migration necessary.
2022-02-08 17:10:29,956[main]             [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - Both KUBERNETES_NAMESPACE and OPENSHIFT_KUBE_PING_NAMESPACE are defined, OPENSHIFT_KUBE_PING_NAMESPACE is deprecated so please remove it
2022-02-08 17:10:29,957[main]             [INFO ] [o.j.p.kubernetes.KUBE_PING 131]      - namespace che set; clustering enabled

-------------------------------------------------------------------
GMS: address=che-7c98444dc-hfk9n-436, cluster=EclipseLinkCommandChannel, physical address=192.168.56.50:7803
-------------------------------------------------------------------
2022-02-08 17:10:33,090[main]             [INFO ] [o.jgroups.protocols.pbcast.GMS 125]  - che-7c98444dc-hfk9n-436: no members discovered after 3124 ms: creating cluster as coordinator
2022-02-08 17:10:33,206[main]             [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 182]   - Configured factories for environments: '[kubernetes, no-environment]'
2022-02-08 17:10:33,207[main]             [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 183]   - Registered infrastructure 'kubernetes'
2022-02-08 17:10:33,400[main]             [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 749]   - Infrastructure is tracking 0 active runtimes
2022-02-08 17:10:33,470[main]             [INFO ] [o.e.c.a.c.u.ApiInfoLogInformer 36]   - Eclipse Che Api Core: Build info '7.44.0-SNAPSHOT' scmRevision '5003afcce2bbb8e854fad4a6636c4c62a4463fd0' implementationVersion '7.44.0-SNAPSHOT'
2022-02-08 17:10:33,541[main]             [WARN ] [p.s.AdminPermissionInitializer 69]   - Admin admin not found yet.
2022-02-08 17:10:33,556[main]             [WARN ] [o.e.c.a.c.u.ApiInfoLogInformer 39]   - Eclipse Che deployed on non-TLS mode. This may cause client-side problems opening workspaces on multi-cluster installations. See https://eclipse.org/che/docs/che-7/introduction-to-eclipse-che/#problems-opening-workspace-in-newest-chrome-versions-on-non-tls-installations-on-distributed-clusters for details.
08-Feb-2022 17:10:34.239 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/api.war] has finished in [55,076] ms
08-Feb-2022 17:10:34.250 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war]
08-Feb-2022 17:10:34.499 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war] has finished in [249] ms
08-Feb-2022 17:10:34.518 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
08-Feb-2022 17:10:34.553 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [67084] milliseconds
```

**Comment by RomanNikitenko** [comment]
I'm not sure about using `keycloak` with `7.42` version of Che.
Could someone clarify it.
maybe @tolusha...

**Comment by cmille62** [comment]
Okay -- Is there a version I should be using to utilize `keycloak`? Thanks!

**Comment by nils-mosbach** [comment]
If you're running devworkspace mode, which I think is the default in Che 7.42 Kubernetes api Server requires to validate against Keycloak. We had similar issues with Che 7.42. 

Since documentation is quite limited on the Kubernetes side I summarized what worked in our case. Maybe that helps. 

https://github.com/eclipse/che/issues/21049#issuecomment-1022108499

At least in native auth mode keycloak works as expected. :)
