### ISSUE TITLE
Get rid of outdated keycloak references in Eclipse Che E2E typescript tests 

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#21175]
### Is your task related to a problem? Please describe

There is code in E2E typescript tests of Eclipse Che, which is getting auth token from keycloak.

After keycloak had been removed from Eclipse Che 7.40, E2E tests are failing on getting auth token step:

####  getting keycloak token to then set 'Preferences' to `never` value:
```
  Git with ssh workflow
Can not get bearer token. URL used: https://192.168.59.146.nip.io/auth/realms/che/protocol/openid-connect/token
  [ERROR] PreferencesHandler.setPreferences failed to get user preferences: Error: unable to verify the first certificate
Can not get bearer token. URL used: https://192.168.59.146.nip.io/auth/realms/che/protocol/openid-connect/token
  [ERROR] PreferencesHandler.setPreferences failed to get user preferences: Error: unable to verify the first certificate
Can not get bearer token. URL used: https://192.168.59.146.nip.io/auth/realms/che/protocol/openid-connect/token
```
#### getting keycloak token to stop and delete workspace throughout che-server API
```
1) The 'TypescriptPlugin and Node-debug' tests
       Stopping and deleting the workspace
         Stop and remove workspace:
     UnexpectedAlertOpenError: unexpected alert open: {Alert text : }
  (Session info: chrome=98.0.4758.80)
  (Driver info: chromedriver=97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}),platform=Linux 5.16.7-200.fc35.x86_64 x86_64)
      at Object.checkLegacyResponse (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/error.js:553:13)
      at parseHttpResponse (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/http.js:441:30
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
  From: Task: WebDriver.findElements(By(xpath, //div[@id='page-sidebar']//a[contains(text(), 'Workspaces (')]))
      at thenableWebDriverProxy.schedule (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at thenableWebDriverProxy.findElements (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/webdriver.js:1048:19)
      at /home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/until.js:243:23
      at /home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/webdriver.js:938:14
      at TaskQueue.execute_ (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at /home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:2974:25
      at /home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
  From: Task: <anonymous>
      at pollCondition (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:2195:19)
      at /home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:2191:7
      at new ManagedPromise (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at ControlFlow.promise (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:2505:12)
      at /home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:2190:22
      at TaskQueue.execute_ (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at /home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:2974:25
      at /home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
  From: Task: Waiting for element to be located By(xpath, //div[@id='page-sidebar']//a[contains(text(), 'Workspaces (')])
      at scheduleWait (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/home/bmakam/che/tests/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at DriverHelper.waitVisibility (/home/bmakam/che/tests/e2e/utils/DriverHelper.ts:110:45)
      at Dashboard.waitPage (/home/bmakam/che/tests/e2e/pageobjects/dashboard/Dashboard.ts:72:33)
      at Dashboard.openDashboard (/home/bmakam/che/tests/e2e/pageobjects/dashboard/Dashboard.ts:65:20)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at WorkspaceHandlingTests.stopAndRemoveWorkspace (/home/bmakam/che/tests/e2e/testsLibrary/WorkspaceHandlingTests.ts:65:9)
      at Context.<anonymous> (/home/bmakam/che/tests/e2e/tests/plugins/TypescriptPlugin.spec.ts:160:17)
```

### Describe the solution you'd like

We need to rewrite E2E tests to get auth token from another place.
1) remove all code part related to keycloak/token/url
2) investigate how to do Set/configure 'Preferences' to `never` to avoid alert browser popup
3) fix automated removal of workspace after test execution (it could be done through Dashboard UI)

An example of fix: https://github.com/eclipse/che/pull/21170/commits/b874cd9d78942fc47e083b0412fcb230cb482da2

### Describe alternatives you've considered

Remove functionality, which requires the token from tests.

**Comment by makambalaji** [comment]
1. **Oauth_proxy and JSESSIONID** cookies are used as request headers in all api's instead of the bearer token.
2. How to retrieve this cookies -> Login to the application from Eclipse Che UI and fetch the cookie details from the api : {eclipse_che_url}/api/user
3. Re-use it in all other api's

**Comment by nickboldt** [comment]
Downgrading from Blocker so that the Che 7.44 release can proceed. Feel free to re-escalate next week.
