### ISSUE TITLE
Build arm64 version of che-operator image to deploy Che on Apple Silicon M1

### ISSUE THREAD

**Issue by lingenhag** [eclipse/che#21234]
### Describe the bug

Tried to install eclipse-che on a MacBookPro with M1. Got this

Cause: Error: Failed to download image, reason: ErrImagePull, message: rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest 

I guess the image is also working on amd64 mode. How can I force the script to download the image anyway ?

### Che version

7.44@latest

### Steps to reproduce

bash chectl server:deploy --platform minikube

### Expected behavior

ignore:
✖ Downloading images...failed
        → Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-operator
…
        Starting

### Runtime

minikube

### Installation method

chectl/latest

### Environment

macOS

### Eclipse Che Logs

```shell
2022-03-05T12:05:53.401Z Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
2022-03-05T12:05:53.401Z     at Object.warn (/Users/atahualpa/Code/bin/chectl/node_modules/@oclif/errors/lib/index.js:49:15)
2022-03-05T12:05:53.401Z     at Deploy.warn (/Users/atahualpa/Code/bin/chectl/node_modules/@oclif/command/lib/command.js:57:16)
2022-03-05T12:05:53.401Z     at OperatorTasks.<anonymous> (/Users/atahualpa/Code/bin/chectl/lib/tasks/installers/operator.js:151:25)
2022-03-05T12:05:53.401Z     at Generator.next (<anonymous>)
2022-03-05T12:05:53.401Z     at fulfilled (/Users/atahualpa/Code/bin/chectl/node_modules/tslib/tslib.js:114:62)
2022-03-05T12:05:53.401Z     at runMicrotasks (<anonymous>)
2022-03-05T12:05:53.401Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-05T12:07:04.148Z Error: Command server:deploy failed. Error log: /Users/atahualpa/Library/Caches/chectl/error.log.
2022-03-05T12:07:04.148Z     at newError (~/Code/bin/chectl/lib/util.js:199:19)
2022-03-05T12:07:04.148Z     at Object.wrapCommandError (~/Code/bin/chectl/lib/util.js:195:12)
2022-03-05T12:07:04.148Z     at Deploy.<anonymous> (~/Code/bin/chectl/lib/commands/server/deploy.js:189:35)
2022-03-05T12:07:04.148Z     at Generator.throw (<anonymous>)
2022-03-05T12:07:04.148Z     at rejected (~/Code/bin/chectl/node_modules/tslib/tslib.js:115:69)
2022-03-05T12:07:04.148Z     at runMicrotasks (<anonymous>)
2022-03-05T12:07:04.148Z Cause: Error: Failed to download image, reason: ErrImagePull, message: rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries.
2022-03-05T12:07:04.148Z     at KubeTasks.<anonymous> (~/Code/bin/chectl/lib/tasks/kube.js:84:39)
2022-03-05T12:07:04.148Z     at Generator.next (<anonymous>)
2022-03-05T12:07:04.148Z     at fulfilled (~/Code/bin/chectl/node_modules/tslib/tslib.js:114:62)
2022-03-05T12:07:04.148Z     at runMicrotasks (<anonymous>)
2022-03-05T12:08:20.723Z Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
2022-03-05T12:08:20.723Z     at Object.warn (/Users/atahualpa/Code/bin/chectl/node_modules/@oclif/errors/lib/index.js:49:15)
2022-03-05T12:08:20.723Z     at Deploy.warn (/Users/atahualpa/Code/bin/chectl/node_modules/@oclif/command/lib/command.js:57:16)
2022-03-05T12:08:20.723Z     at OperatorTasks.<anonymous> (/Users/atahualpa/Code/bin/chectl/lib/tasks/installers/operator.js:151:25)
2022-03-05T12:08:20.723Z     at Generator.next (<anonymous>)
2022-03-05T12:08:20.723Z     at fulfilled (/Users/atahualpa/Code/bin/chectl/node_modules/tslib/tslib.js:114:62)
2022-03-05T12:08:20.723Z     at runMicrotasks (<anonymous>)
2022-03-05T12:08:20.723Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-05T12:09:27.158Z Error: Command server:deploy failed. Error log: /Users/atahualpa/Library/Caches/chectl/error.log.
2022-03-05T12:09:27.158Z     at newError (~/Code/bin/chectl/lib/util.js:199:19)
2022-03-05T12:09:27.158Z     at Object.wrapCommandError (~/Code/bin/chectl/lib/util.js:195:12)
2022-03-05T12:09:27.158Z     at Deploy.<anonymous> (~/Code/bin/chectl/lib/commands/server/deploy.js:189:35)
2022-03-05T12:09:27.158Z     at Generator.throw (<anonymous>)
2022-03-05T12:09:27.158Z     at rejected (~/Code/bin/chectl/node_modules/tslib/tslib.js:115:69)
2022-03-05T12:09:27.158Z     at runMicrotasks (<anonymous>)
2022-03-05T12:09:27.158Z Cause: Error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-operator:7.44.0".
2022-03-05T12:09:27.158Z     at KubeTasks.<anonymous> (~/Code/bin/chectl/lib/tasks/kube.js:84:39)
2022-03-05T12:09:27.158Z     at Generator.next (<anonymous>)
2022-03-05T12:09:27.158Z     at fulfilled (~/Code/bin/chectl/node_modules/tslib/tslib.js:114:62)
2022-03-05T12:09:27.158Z     at runMicrotasks (<anonymous>)
2022-03-05T12:38:00.346Z Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
2022-03-05T12:38:00.346Z     at Object.warn (/Users/atahualpa/Code/bin/chectl/node_modules/@oclif/errors/lib/index.js:49:15)
2022-03-05T12:38:00.346Z     at Deploy.warn (/Users/atahualpa/Code/bin/chectl/node_modules/@oclif/command/lib/command.js:57:16)
2022-03-05T12:38:00.346Z     at OperatorTasks.<anonymous> (/Users/atahualpa/Code/bin/chectl/lib/tasks/installers/operator.js:151:25)
2022-03-05T12:38:00.346Z     at Generator.next (<anonymous>)
2022-03-05T12:38:00.346Z     at fulfilled (/Users/atahualpa/Code/bin/chectl/node_modules/tslib/tslib.js:114:62)
2022-03-05T12:38:00.346Z     at runMicrotasks (<anonymous>)
2022-03-05T12:38:00.346Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-05T12:39:06.547Z Error: Command server:deploy failed. Error log: /Users/atahualpa/Library/Caches/chectl/error.log.
2022-03-05T12:39:06.547Z     at newError (~/Code/bin/chectl/lib/util.js:199:19)
2022-03-05T12:39:06.547Z     at Object.wrapCommandError (~/Code/bin/chectl/lib/util.js:195:12)
2022-03-05T12:39:06.547Z     at Deploy.<anonymous> (~/Code/bin/chectl/lib/commands/server/deploy.js:189:35)
2022-03-05T12:39:06.547Z     at Generator.throw (<anonymous>)
2022-03-05T12:39:06.547Z     at rejected (~/Code/bin/chectl/node_modules/tslib/tslib.js:115:69)
2022-03-05T12:39:06.547Z     at runMicrotasks (<anonymous>)
2022-03-05T12:39:06.547Z Cause: Error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-operator:7.44.0".
2022-03-05T12:39:06.547Z     at KubeTasks.<anonymous> (~/Code/bin/chectl/lib/tasks/kube.js:84:39)
2022-03-05T12:39:06.547Z     at Generator.next (<anonymous>)
2022-03-05T12:39:06.547Z     at fulfilled (~/Code/bin/chectl/node_modules/tslib/tslib.js:114:62)
2022-03-05T12:39:06.547Z     at runMicrotasks (<anonymous>)
```

**Comment by l0rd** [comment]
We are [not building arm64](https://github.com/eclipse-che/che-operator/blob/main/make-release.sh#L30) that explains why it doesn't run natively on M1 Silicon. I don't know how to force minikube (or docker) to use `amd64`.

**Comment by l0rd** [comment]
@lingenhag have you considered signing up to [Che mailing list](https://accounts.eclipse.org/mailing-list/che-dev) or joining [Che weekly community call](https://github.com/eclipse/che/wiki/Che-Dev-Meetings) to help us improving the project?

**Comment by lingenhag** [comment]
will do! thanks for the hint.

**Comment by huyinsong** [comment]
When will che support arm64？

**Comment by l0rd** [comment]
@huyinsong we do not have a plan, we are looking for some contribution here. Will you be interested in providing some help?

**Comment by celevra** [comment]
+1
