### ISSUE TITLE
che server pod error ( exitcode: 137)

### ISSUE THREAD

**Issue by Ryder05** [eclipse/che#21321]
### Describe the bug

I can't  install kubernetes on my k8s cluster  the Eclipse Che Server pod bootstrap is stuck at starting and then throws an error saying        "   → Failed to start a pod, reason: Error, exitCode: 137 " 

### Che version

7.44@latest

### Steps to reproduce

1. chectl server:deploy --domain=os.*******.me --platform=k8s --che-operator-cr-yaml=checluster.yml  --skip-oidc-provider-check  -n che

### Expected behavior

1. I can access the che dashboard and start creating workspaces 

### Runtime

Kubernetes (vanilla)

### Screenshots

 
![image](https://user-images.githubusercontent.com/59898800/161772621-03715685-72bb-408b-87ca-e8338cf70889.png)

### Installation method

chectl/latest

### Environment

Windows, Azure

### Eclipse Che Logs

```shell
java.base@11.0.14.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@11.0.14.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
 java.base@11.0.14.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
 java.base@11.0.14.1/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:417)
 org.jgroups.protocols.TransferQueueBundler.run(TransferQueueBundler.java:104)
 java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
05-Apr-2022 14:25:44.421 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [api] appears to have started a thread named [jgroups-6,EclipseLinkCommandChannel,che-5576497dfd-72xt8-54011] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.14.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@11.0.14.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
 java.base@11.0.14.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
 java.base@11.0.14.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
 java.base@11.0.14.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
05-Apr-2022 14:25:44.421 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [api] appears to have started a thread named [TcpServer.Acceptor[7803]-2,EclipseLinkCommandChannel,che-5576497dfd-72xt8-54011] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.14.1/java.net.PlainSocketImpl.socketAccept(Native Method)
 java.base@11.0.14.1/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
 java.base@11.0.14.1/java.net.ServerSocket.implAccept(ServerSocket.java:565)
 java.base@11.0.14.1/java.net.ServerSocket.accept(ServerSocket.java:533)
 org.jgroups.blocks.cs.TcpServer$Acceptor.run(TcpServer.java:110)
 java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
05-Apr-2022 14:25:44.421 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [api] appears to have started a thread named [FD_SOCK acceptor-9,EclipseLinkCommandChannel,che-5576497dfd-72xt8-54011] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.14.1/java.net.PlainSocketImpl.socketAccept(Native Method)
 java.base@11.0.14.1/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
 java.base@11.0.14.1/java.net.ServerSocket.implAccept(ServerSocket.java:565)
 java.base@11.0.14.1/java.net.ServerSocket.accept(ServerSocket.java:533)
 org.jgroups.protocols.FD_SOCK$ServerSocketHandler.run(FD_SOCK.java:993)
 java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
05-Apr-2022 14:25:44.422 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [api] appears to have started a thread named [Annotated-scheduler-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.14.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@11.0.14.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
 java.base@11.0.14.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
 java.base@11.0.14.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1177)
 java.base@11.0.14.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
05-Apr-2022 14:25:44.423 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [api] appears to have started a thread named [Annotated-scheduler-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.14.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@11.0.14.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
 java.base@11.0.14.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
 java.base@11.0.14.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1177)
 java.base@11.0.14.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
05-Apr-2022 14:25:44.423 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [api] appears to have started a thread named [Annotated-scheduler-3] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.14.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@11.0.14.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
 java.base@11.0.14.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
 java.base@11.0.14.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1177)
 java.base@11.0.14.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
 java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
05-Apr-2022 14:25:44.438 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/api.war] has finished in [31,918] ms
05-Apr-2022 14:25:44.439 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war]
05-Apr-2022 14:25:44.633 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war] has finished in [194] ms
05-Apr-2022 14:25:44.634 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war]
05-Apr-2022 14:25:47.042 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war] has finished in [2,408] ms
05-Apr-2022 14:25:47.045 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
05-Apr-2022 14:25:47.108 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [34763] milliseconds
05-Apr-2022 14:25:53.997 INFO [jgroups-6,WorkspaceLocks,che-5576497dfd-72xt8-16311] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.jgroups.util.Headers]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.jgroups.util.Headers]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1464)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1452)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1291)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1252)
        at org.jgroups.Message.putHeader(Message.java:466)
        at org.jgroups.protocols.pbcast.STABLE.sendStableMessage(STABLE.java:667)
        at org.jgroups.protocols.pbcast.STABLE$StableTask.run(STABLE.java:832)
        at org.jgroups.util.TimeScheduler3$Task.run(TimeScheduler3.java:328)
        at org.jgroups.util.TimeScheduler3$RecurringTask.run(TimeScheduler3.java:362)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-05 14:25:54,000[dfd-72xt8-16311]  [ERROR] [o.jgroups.util.TimeScheduler3 104]   - JGRP000169: failed executing task STABLE: StableTask
java.lang.NoClassDefFoundError: org/jgroups/util/Headers
    at org.jgroups.Message.putHeader(Message.java:466)
    at org.jgroups.protocols.pbcast.STABLE.sendStableMessage(STABLE.java:667)
    at org.jgroups.protocols.pbcast.STABLE$StableTask.run(STABLE.java:832)
    at org.jgroups.util.TimeScheduler3$Task.run(TimeScheduler3.java:328)
    at org.jgroups.util.TimeScheduler3$RecurringTask.run(TimeScheduler3.java:362)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [org.jgroups.util.Headers]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1454)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1291)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1252)
    ... 8 common frames omitted
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.jgroups.util.Headers]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1464)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1452)
```

**Comment by sparkoo** [comment]
is it full log?

**Comment by Ryder05** [comment]
> is it full log?
[log.txt](https://github.com/eclipse/che/files/8450611/log.txt)

**Comment by mingfang** [comment]
what was the solution to this problem?
I'm still seeing this error in v7.47.0

**Comment by Ryder05** [comment]
> what was the solution to this problem? I'm still seeing this error in v7.47.0

In my case, I resolved the problem after using a TLS certificate for my externel OIDC provider ( keycloak ).
