### ISSUE TITLE
Factory creation from a branch of a pull request on GitHub fails with  `Unable to extract the data` error

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse/che#21343]
### Describe the bug

Factory creation from a branch of a pull request on GitHub fails with  `Unable to extract the data` error. 
Checked on both `#` and `/f?url` factory creation ways.

### Che version

next (development version)

### Steps to reproduce

Steps from [this document](https://che.eclipseprojects.io/2021/12/20/@florent.benoit-authoring-a-url-to-start-a-workspace.html). Example 4.

To clone the branch of a pull request on GitHub to the starting workspace:
`#https://github.com/<user_or_org>/<repository>/pull/<pull-request-id>`

Example 4. Cloning the [Plug-in registry repository pull request #1097](https://github.com/eclipse-che/che-plugin-registry/pull/1097).
`https://che-host#https://github.com/eclipse-che/che-plugin-registry/pull/1097`
`https://che-host/f?url=https://github.com/eclipse-che/che-plugin-registry/pull/1097`

### Runtime

OpenShift

### Screenshots
![Selection_017](https://user-images.githubusercontent.com/7760565/164459776-2a0dc04c-38aa-46d9-acdb-c690e7515ee9.png)

![Selection_018](https://user-images.githubusercontent.com/7760565/164460027-2f99f59f-a058-4f01-8e11-40ec5429c7e5.png)

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
21-Apr-2022 08:56:42.723 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [45769] milliseconds
2022-04-21 09:17:26,915[nio-8080-exec-8]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2022-04-21 09:17:26
java.lang.IllegalArgumentException: The given Pull Request github url https://github.com/eclipse/che/pull/21276 is not a valid Pull Request URL github url. Unable to extract the data
	at org.eclipse.che.api.factory.server.github.GithubURLParser.parse(GithubURLParser.java:94)
	at org.eclipse.che.api.factory.server.github.GithubFactoryParametersResolver.createFactory(GithubFactoryParametersResolver.java:102)
	at org.eclipse.che.api.factory.server.FactoryService.resolveFactory(FactoryService.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:174)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:61)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:329)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:319)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:257)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:131)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:61)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:130)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:62)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:777)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.eclipse.che.core.metrics.ApiResponseMetricFilter.doFilter(ApiResponseMetricFilter.java:46)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:161)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:872)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1705)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Additional context

[devspaces-78f9fff597-kv9hf-devspaces.log](https://github.com/eclipse/che/files/8530839/devspaces-78f9fff597-kv9hf-devspaces.log)

**Comment by skabashnyuk** [comment]
Looks like problem in URlFetcher. https://github.com/eclipse-che/che-server/blob/ea1897b28986b689dcc5719e418db10bc1141cde/wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java#L79 @benoitf  that is the class you've added. Can you take a look?  maybe something changed in page design https://github.com/eclipse-che/che-server/blob/ea1897b28986b689dcc5719e418db10bc1141cde/wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java#L52

**Comment by benoitf** [comment]
fixed by https://github.com/eclipse-che/che-server/pull/299

**Comment by nickboldt** [comment]
Downstream issue https://issues.redhat.com/browse/CRW-2890
