### ISSUE TITLE
No X11 DISPLAY variable was set, but this program performed an operation which requires it

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21383]
### Summary

i'm using below `devfile.yaml` . i have specified is a `javacontainer` and [selenium novnc-container](https://github.com/SeleniumHQ/docker-selenium#using-your-browser-no-vnc-client-is-needed)

```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.myorganization/repository.git
components:
  - container:
      image: 'quay.io/devfile/universal-developer-image:ubi8-0e189d9'
      memoryLimit: 2G
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: 8080-http
          protocol: http
          targetPort: 8080
      volumeMounts:
        - name: m2volume
          path: /home/user/.m2
    name: javacontainer
  - container:
      image: 'mycustomdockerregistry/standalone-chrome:4.1.2-20220217'
      memoryLimit: 2G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
          secure: true
      volumeMounts:
        - name: seleniumvolume
          path: /home/user/.m2
    name: seleniumcontainer
  - name: m2volume
    volume:
      size: 2G
  - name: seleniumvolume
    volume:
      size: 2G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage
```

The javaprogram in the workspace will make use of the selenium-novnc container to run tests on webpages.
when i execute the javaprogram, the first page of my test appears in the `selenium-novnc` website, but then it fails with below error(i understand below stacktrace shows some of my classnames, but its fine).

```
vTAPRegression.moduledrivers.DuckduckgoDriver@41200e0c|Error: Failed in executing component |vTap_duck_Operation| |java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at cbf.engine.BaseModuleDriver.invokeMethod(BaseModuleDriver.java:103)
        at cbf.engine.BaseModuleDriver.eval(BaseModuleDriver.java:56)
        at cbf.engine.BaseModuleDriver.perform(BaseModuleDriver.java:50)
        at cbf.engine.BaseAppDriver.perform(BaseAppDriver.java:61)
        at cbf.engine.TestCaseRunner.performComponent(TestCaseRunner.java:260)
        at cbf.engine.TestCaseRunner.access$400(TestCaseRunner.java:41)
        at cbf.engine.TestCaseRunner$4.run(TestCaseRunner.java:234)
        at cbf.engine.TestResultTracker.track(TestResultTracker.java:135)
        at cbf.engine.TestCaseRunner.runComponent(TestCaseRunner.java:229)
        at cbf.engine.TestCaseRunner$3.run(TestCaseRunner.java:168)
        at cbf.engine.TestResultTracker.track(TestResultTracker.java:135)
        at cbf.engine.TestCaseRunner.runStep(TestCaseRunner.java:160)
        at cbf.engine.TestCaseRunner$2.run(TestCaseRunner.java:139)
        at cbf.engine.TestResultTracker.track(TestResultTracker.java:135)
        at cbf.engine.TestCaseRunner.runIteration(TestCaseRunner.java:132)
        at cbf.engine.TestCaseRunner.access$200(TestCaseRunner.java:41)
        at cbf.engine.TestCaseRunner$1.run(TestCaseRunner.java:113)
        at cbf.engine.TestResultTracker.track(TestResultTracker.java:135)
        at cbf.engine.TestCaseRunner.runTestCase(TestCaseRunner.java:89)
        at cbf.engine.Engine.runTestCase(Engine.java:48)
        at cbf.engine.TestSetRunner$4.run(TestSetRunner.java:146)
        at cbf.engine.TestResultTracker.track(TestResultTracker.java:135)
        at cbf.engine.TestSetRunner.runTestInstance(TestSetRunner.java:130)
        at cbf.engine.TestSetRunner$3.run(TestSetRunner.java:107)
        at cbf.engine.TestResultTracker.track(TestResultTracker.java:135)
        at cbf.engine.TestSetRunner.runTestsetRerun(TestSetRunner.java:98)
        at cbf.engine.TestSetRunner$1.run(TestSetRunner.java:65)
        at cbf.engine.TestResultTracker.track(TestResultTracker.java:135)
        at cbf.engine.TestSetRunner.runTestSet(TestSetRunner.java:60)
        at cbf.engine.Engine.runTestSet(Engine.java:42)
        at cbf.engine.TestSetRunner.runTestSetInstance(TestSetRunner.java:183)
        at cbf.runner.MainRunner.<init>(MainRunner.java:61)
        at cbf.runner.MainRunner.main(MainRunner.java:53)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:186)
        at cbf.reporting.ScreenDumpManager.dumpScreen(ScreenDumpManager.java:154)
        at cbf.reporting.ScreenDumpManager.log(ScreenDumpManager.java:122)
        at cbf.engine.TestResultTracker.log(TestResultTracker.java:177)
        at cbf.engine.TestResultLogger.log(TestResultLogger.java:159)
        at cbf.engine.TestResultLogger.passed(TestResultLogger.java:86)
        at vTAPRegression.moduledrivers.DuckduckgoDriver.vTap_duck_Operation(DuckduckgoDriver.java:42)
        ... 37 more

```

i noticed this error `Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.` . i'm not sure how to fix this.

i tried adding `export DISPLAY=:0` , `export DISPLAY=localhost:0.0`, `export DISPLAY=:0.0` , it didn't work

below is the operating system detail of the `java container
![image](https://user-images.githubusercontent.com/10482177/167581002-57d585fc-7ebb-4050-89aa-3e8863eaba25.png)

please let me know how to fix this problem

**Comment by tolusha** [comment]
Correct me if I am wrong. You need to set some environment variables into workspace containers?
so, it can help https://www.eclipse.org/che/docs/stable/end-user-guide/secret-as-a-variable/

**Comment by Divine1** [comment]
@tolusha i looked up for solutions to fix this issue

https://stackoverflow.com/a/25969150/3673073

the above solution requires to install below tool
```
 wget http://vault.centos.org/6.2/os/x86_64/Packages/xorg-x11-server-Xvfb-1.10.4-6.el6.x86_64.rpm
 yum localinstall xorg-x11-server-Xvfb-1.10.4-6.el6.x86_64.rpm
```

i'm facing this error in `quay.io/devfile/universal-developer-image:ubi8-0e189d9` image (redhat 8 operating system). 

![image](https://user-images.githubusercontent.com/10482177/167760782-f541c0c2-219d-4d61-a2c1-f5a435f9bfd5.png)

The commands mentioned above requires `sudo` permission. Could you let me know what is the root username/password to login as sudo user in this image?

![image](https://user-images.githubusercontent.com/10482177/167760858-6fbe8e59-1136-4fe2-bb4b-65fb6363f53d.png)

**Comment by tolusha** [comment]
>  I tried to set environment variable within the container using export DISPLAY=0.0 and few other values, but it didnot work.

I believe it won't work. It works only for current terminal session.

> The commands mentioned above requires sudo permission

I don't think that it is possible to install something that requires sudo rights when workspace is up and running. I recommend to build your own image on top of universal one and install there anything your need (plus set any environment variables) .

**Comment by Divine1** [comment]
@tolusha  i still need username/password details inorder to login as sudo user to install new tools in the image and to customize the image, right?

`quay.io/devfile/universal-developer-image:ubi8-0e189d9` -- any idea of what is the sudo username/password for this image

**Comment by Divine1** [comment]
i have received the intended information . thank you

**Comment by Divine1** [comment]
@benoitf  could you please share if you have any idea on how to fix this problem?




`xvfb-run -a java -jar target/cbfvTAPRegression.jar ` - we have to use the `xvfb-run -a ` command to run the java program within `quay.io/devfile/universal-developer-image:ubi8-latest` container

**Comment by Divine1** [comment]
@benoitf 
i figured the solution for my issue.

instead of using the image with redhat os`quay.io/devfile/universal-developer-image:ubi8-latest`  , i used `selenium/standalone-chrome` (this image was required for my project) as a base image and installed the java tools in the image. this image had `xvfb` installed in it.

the issue is fixed now.


thank you for the help
