### ISSUE TITLE
chectl minikube kubernetes version fails

### ISSUE THREAD

**Issue by patnan** [eclipse/che#21451]
### Describe the bug

When running chectl server:deploy --telemetry=off --platform minikube the kubernetes version check fails

    ✖ Check Kubernetes version
      → See 'minikube kubectl --help' for usage.

### Che version

7.47@latest

### Steps to reproduce

Run chectl server:deploy --telemetry=off --platform minikube

Observe:
![image](https://user-images.githubusercontent.com/19404665/172655474-ffd7f3d0-f537-49ec-b274-929184153765.png)

### Expected behavior

Kubernetes check to pass

### Runtime

minikube

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
2022-06-08T15:23:53.970Z Error: Command server:deploy failed. Error log: /home/patna/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1654701831836.
2022-06-08T15:23:53.970Z     at newError (~/.local/share/chectl/client/7.49.0/lib/util.js:199:19)
2022-06-08T15:23:53.970Z     at Object.wrapCommandError (~/.local/share/chectl/client/7.49.0/lib/util.js:195:12)
2022-06-08T15:23:53.970Z     at Deploy.<anonymous> (~/.local/share/chectl/client/7.49.0/lib/commands/server/deploy.js:173:35)
2022-06-08T15:23:53.970Z     at Generator.throw (<anonymous>)
2022-06-08T15:23:53.970Z     at rejected (~/.local/share/chectl/client/7.49.0/node_modules/tslib/tslib.js:115:69)
2022-06-08T15:23:53.970Z Cause: Error: Command failed with exit code 14: kubectl version --short
2022-06-08T15:23:53.970Z Error: unknown flag: --short
2022-06-08T15:23:53.970Z See 'minikube kubectl --help' for usage.
2022-06-08T15:23:53.970Z     at makeError (~/.local/share/chectl/client/7.49.0/node_modules/execa/lib/error.js:60:11)
2022-06-08T15:23:53.970Z     at handlePromise (~/.local/share/chectl/client/7.49.0/node_modules/execa/index.js:118:26)
```

### Additional context

The version check seems to be done using the --short flag

**Comment by tolusha** [comment]
@patnan 
What does print?
`kubectl version`

**Comment by patnan** [comment]
Hi @tolusha 

Here is the output:
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

Also chectl version is:
```
chectl version
chectl/7.49.0 linux-x64 node-v16.13.2
```

**Comment by tolusha** [comment]
I think issues comes from the fact that `kubectl` is an alias for `minikube kubectl` which does not contain `--short` flag.

**Comment by patnan** [comment]
Ok now I get this. What host is it trying to reach? there is no host at 192.168.49.2

I'm trying to follow this : https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-minikube/

```
chectl server:deploy --telemetry=off --platform minikube
    Error: connect EHOSTUNREACH 192.168.49.2:8443
    Code: EHOSTUNREACH
```

**Comment by tolusha** [comment]
> Verify if kubectl is installed → E_REQUISITE_NOT_FOUND

check if you have `kubectl` file in the directory where you run `chectl` from.
if so, delete it and try `chectl` again.
