### ISSUE TITLE
Chectl cant find kubectl although it is installed

### ISSUE THREAD

**Issue by patnan** [eclipse/che#21474]
### Describe the bug

When runninf "chectl server:deploy --platform minikube" to deploy a server the Minikube preflight check fails on checking kubectl

### Che version

other (please specify in additional context)

### Steps to reproduce

Run "chectl server:deploy --platform minikube " as described here: https://www.eclipse.org/che/docs/stable/administration-guide/installing-che-on-minikube/

----

REgarding version, since I cant start there is non appart from chectl whcih is chectl/7.49.0 linux-x64 node-v16.13.2

### Expected behavior

Preflight to pass

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/19404665/174253108-3cddf30d-7908-4e20-a25e-92c02b527b4c.png)

### Installation method

chectl/latest

### Environment

Linux, other (please specify in additional context)

### Eclipse Che Logs

```shell
2022-06-17T07:59:53.789Z Error: Command server:deploy failed. Error log: /home/user/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1655452793702.
2022-06-17T07:59:53.789Z     at newError (/usr/local/lib/chectl/lib/util.js:199:19)
2022-06-17T07:59:53.789Z     at Object.wrapCommandError (/usr/local/lib/chectl/lib/util.js:195:12)
2022-06-17T07:59:53.789Z     at Deploy.<anonymous> (/usr/local/lib/chectl/lib/commands/server/deploy.js:173:35)
2022-06-17T07:59:53.789Z     at Generator.throw (<anonymous>)
2022-06-17T07:59:53.789Z     at rejected (/usr/local/lib/chectl/node_modules/tslib/tslib.js:115:69)
2022-06-17T07:59:53.789Z Cause: Error: E_REQUISITE_NOT_FOUND
2022-06-17T07:59:53.789Z     at Object.error (/usr/local/lib/chectl/node_modules/@oclif/errors/lib/index.js:26:15)
2022-06-17T07:59:53.789Z     at Deploy.error (/usr/local/lib/chectl/node_modules/@oclif/command/lib/command.js:60:23)
2022-06-17T07:59:53.789Z     at Task.task (/usr/local/lib/chectl/lib/tasks/platforms/minikube.js:35:33)
2022-06-17T07:59:53.789Z     at /usr/local/lib/chectl/node_modules/listr/lib/task.js:167:30
```

### Additional context

```
chectl version

chectl/7.49.0 linux-x64 node-v16.13.2
```

Kubectl installed according to:  https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

```
which kubectl 
/usr/bin/kubectl
```

**Comment by patnan** [comment]
An addition, nothing is written to the Eclipse Che logs: /tmp/chectl-logs folder. I'm not sure it is created. Even if I create it and set appropriate access rights nothing is written....

**Comment by tolusha** [comment]
@patnan 
Check the current directory where you run `chectl` from. There should be downloaded `kubectl` file.
Pld delete it and try again.

**Comment by patnan** [comment]
Thanks, actually found it and removed it and it worked.
