### ISSUE TITLE
Dashboard sometimes crashing with `Unexpected token � in JSON at position 0` error in the logs

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21703]
### Describe the bug

Dashboard sometimes crashing with `Unexpected token � in JSON at position 0` error in the logs

### Che version

7.50

### Steps to reproduce

N/A 

### Expected behavior

No errors, pod is not crashing /  crashloopbackoff

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

### Eclipse Che Logs

```shell
<100x>
Unexpected error null
Unexpected error null
undefined:1



SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at R.<anonymous> (/backend/server/backend.js:8:544161)
    at R.emit (node:events:532:35)
    at e.exports.H (/backend/server/backend.js:2:472245)
    at e.exports.emit (node:events:520:28)
    at e.exports.dataMessage (/backend/server/backend.js:2:449005)
    at e.exports.getData (/backend/server/backend.js:2:448157)
    at e.exports.startLoop (/backend/server/backend.js:2:444956)
    at e.exports._write (/backend/server/backend.js:2:444311)
    at writeOrBuffer (node:internal/streams/writable:389:12)
+ echo 'Dashboard backend server is stopped.'
Dashboard backend server is stopped.
```

**Comment by ibuziuk** [comment]
Closing since the appropriate logging has been added. A new issue should be created with a clear error message
