### ISSUE TITLE
dashboard-happy-path tests are failing on "Validation of debug functionality"

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#21728]
### Describe the bug

dashboard-happy-path tests are failing on "Validation of debug functionality":

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-dashboard/637/pull-ci-eclipse-che-che-dashboard-main-v10-dashboard-happy-path/1572951146840985600

<details>
<summary>Test logs:</summary>

```

  16 passing (12m)
  4 failing
  1) Validation of debug functionality
       Launch debug:
     TimeoutError: Waiting for element to be located By(css selector, div[aria-label="run-debug, Global"])
Wait timed out after 1004ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
7 skipped lines...
      at DriverHelper.waitAndClick (/tmp/e2e/utils/DriverHelper.ts:270:38)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  2) Validation of debug functionality
       Check content of the launched application:
     TimeoutError: Wait timed out after 5000ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
8 skipped lines...
      at Context.test (/tmp/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts:180:31)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  3) Validation of debug functionality
       Run debug:
     TimeoutError: Wait timed out after 60351ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at DebugView.waitForDebuggerToConnect (/tmp/e2e/pageobjects/ide/DebugView.ts:57:45)
      at waitDebugToConnect (/tmp/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts:294:25)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  4) Validation of debug functionality
       Check debugger stop at the breakpoint:
     Error: Provided config url is not valid
      at Axios.request (/tmp/e2e/node_modules/axios/lib/core/Axios.js:40:11)
      at Axios.(anonymous function) [as get] (/tmp/e2e/node_modules/axios/lib/core/Axios.js:136:17)
      at Function.wrap [as get] (/tmp/e2e/node_modules/axios/lib/helpers/bind.js:9:15)
      at sendRequestToDebugApp (/tmp/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts:281:49)
      at Context.test (/tmp/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts:208:15)
      at callFn (/tmp/e2e/node_modules/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/tmp/e2e/node_modules/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/tmp/e2e/node_modules/mocha/lib/runner.js:678:10)
      at /tmp/e2e/node_modules/mocha/lib/runner.js:801:12
      at next (/tmp/e2e/node_modules/mocha/lib/runner.js:593:14)
      at /tmp/e2e/node_modules/mocha/lib/runner.js:603:7
      at next (/tmp/e2e/node_modules/mocha/lib/runner.js:486:14)
      at Immediate.<anonymous> (/tmp/e2e/node_modules/mocha/lib/runner.js:571:5)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
            ‣ DriverHelper.getDriver
  [WARN] Property DELETE_WORKSPACE_ON_FAILED_TEST se to true - trying to stop and delete running workspace.
          ▼ TestWorkspaceUtil.stopAndDeleteWorkspaceByName
          ▼ TestWorkspaceUtil.stopWorkspaceByName
          ▼ ApiUrlResolver.obtainUserNamespace happypath-dev-che
            ‣ DriverHelper.getDriver
```

</details>

Screencast:

https://user-images.githubusercontent.com/16220722/192234336-45e56b88-7ffd-4ee3-a1bf-ca582b54f3f6.mp4

### Che version

next (development version)

### Steps to reproduce

Open a PR in `che-dashboard`

### Expected behavior

Tests are passing

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

GCE

**Comment by musienko-maxim** [comment]
Colleagues you can merge it PR it is not the Dashboard problem, but potentially this version of CHE can include problems with the debugger. If we have time - we will look at this. But you can merge this PR
