### ISSUE TITLE
Chectl: Timeout reached while waiting for "eclipse-che-subscription" subscription is ready.'

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21746]
### Describe the bug

On the `next` release for chectl, I am not able to install Che with `chectl server:deploy -p openshift`:

![image](https://user-images.githubusercontent.com/83611742/193916555-bdc32897-f990-4396-ab15-5c753b86c6d2.png)

Here is the version of chectl used:
```
$ chectl version
chectl/0.0.20220930-next.9b8d5ff darwin-x64 node-v16.13.2
```

This is what I see when viewing the subscription from the OpenShift console:
![image](https://user-images.githubusercontent.com/83611742/193917398-dee081d3-c8d9-4a7b-88a6-ed634ccc9a69.png)

![image](https://user-images.githubusercontent.com/83611742/193917453-80a5856c-bd12-4eae-81f4-da4dfbb4a031.png)

### Che version

next (development version)

### Steps to reproduce

1. Run `chectl server:deploy -p openshift`

### Expected behavior

Eclipse Che should be installed

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS

### Eclipse Che Logs

```shell
2022-10-04T19:44:52.372Z     at newError (~/.local/share/chectl/client/0.0.20220930-next.9b8d5ff/lib/util.js:199:19)
2022-10-04T19:44:52.372Z     at Object.wrapCommandError (~/.local/share/chectl/client/0.0.20220930-next.9b8d5ff/lib/util.js:195:12)
2022-10-04T19:44:52.372Z     at Deploy.<anonymous> (~/.local/share/chectl/client/0.0.20220930-next.9b8d5ff/lib/commands/server/deploy.js:160:35)
2022-10-04T19:44:52.372Z     at Generator.throw (<anonymous>)
2022-10-04T19:44:52.372Z     at rejected (~/.local/share/chectl/client/0.0.20220930-next.9b8d5ff/node_modules/tslib/tslib.js:115:69)
2022-10-04T19:44:52.372Z     at runMicrotasks (<anonymous>)
2022-10-04T19:44:52.372Z Cause: TypeError: Cannot create property 'context' on string 'Timeout reached while waiting for "eclipse-che-subscription" subscription is ready.'
2022-10-04T19:44:52.372Z     at ~/.local/share/chectl/client/0.0.20220930-next.9b8d5ff/node_modules/listr/index.js:112:19
2022-10-04T19:44:52.372Z     at runMicrotasks (<anonymous>)
```
```


### Additional context

_No response_

**Comment by tolusha** [comment]
What was OpenShift version? Could you constantly reproduce it?
I checked with OpenShift 4.10 and everything worked fine.

**Comment by dkwon17** [comment]
Thank you for checking, I had this issue consistently yesterday on OpenShift 4.11. I tried it again today and I don't have this bug anymore, although I'm not sure what initially caused it
