### ISSUE TITLE
Fix build of quay.io/eclipse/che-e2e image

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#21904]
### Is your task related to a problem? Please describe

Build of quay.io/eclipse/che-e2e image failed [1] after the merge [2]:
```
Step 9/14 : RUN cd /tmp/e2e &&     npm --silent i
 ---> Running in 172977fc37a2
/tmp/e2e/node_modules/chromedriver/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/e2e/node_modules/chromedriver/install.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
The command '/bin/sh -c cd /tmp/e2e &&     npm --silent i' returned a non-zero code: 1
```
Related issue: https://github.com/axios/axios/issues/5035

[1] https://github.com/eclipse/che/actions/runs/3766073256
[2] https://github.com/eclipse/che/pull/21901

There was also lint error:
```$ npm run lint

> @eclipse-che/che-e2e@7.58.0-SNAPSHOT lint /home/ndp/projects/che/tests/e2e
> tslint --fix -p .

no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
/home/ndp/projects/che/tests/e2e/TestConstants.ts:25:14
ERROR: 25:14   typedef  expected variable-declaration: 'TestConstants' to have a typedef

/home/ndp/projects/che/tests/e2e/TimeoutConstants.ts:11:14
ERROR: 11:14   typedef  expected variable-declaration: 'TimeoutConstants' to have a typedef

/home/ndp/projects/che/tests/e2e/driver/CheReporter.ts:104:15
ERROR: 104:15  typedef  expected variable-declaration: 'report' to have a typedef
ERROR: 160:13  typedef  expected variable-declaration: 'screenshotStream' to have a typedef
ERROR: 166:13  typedef  expected variable-declaration: 'pageSourceStream' to have a typedef
ERROR: 178:13  typedef  expected variable-declaration: 'browserLogsStream' to have a typedef

/home/ndp/projects/che/tests/e2e/driver/ChromeDriver.ts:52:15
ERROR: 52:15   typedef  expected variable-declaration: 'disableW3copts' to have a typedef

/home/ndp/projects/che/tests/e2e/inversify.types.ts:12:7
ERROR: 12:7    typedef  expected variable-declaration: 'TYPES' to have a typedef
ERROR: 21:7    typedef  expected variable-declaration: 'CLASSES' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/dashboard/workspace-details/WorkspaceDetailsPlugins.ts:79:15
ERROR: 79:15   typedef  expected variable-declaration: 'pluginListItemSwitcherLocator' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/ide/theia/DebugView.ts:60:19
ERROR: 60:19   typedef  expected variable-declaration: 'threadsTreeLocator' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/ide/theia/DialogWindow.ts:91:13
ERROR: 91:13   typedef  expected variable-declaration: 'dialogWindow' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/ide/theia/Editor.ts:242:15
ERROR: 242:15  typedef  expected variable-declaration: 'editorLine' to have a typedef
ERROR: 303:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 308:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 389:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 596:15  typedef  expected variable-declaration: 'breakpointLineNumberXpathLocator' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/ide/theia/Ide.ts:316:13
ERROR: 316:13  typedef  expected variable-declaration: 'notification' to have a typedef
ERROR: 355:23  typedef  expected variable-declaration: 'res' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/ide/theia/OpenWorkspaceWidget.ts:35:15
ERROR: 35:15   typedef  expected variable-declaration: 'promises' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/ide/theia/ProjectTree.ts:196:18
ERROR: 196:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 197:17  typedef  expected variable-declaration: 'item' to have a typedef
ERROR: 236:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 238:19  typedef  expected variable-declaration: 'isRootFolderVisible' to have a typedef
ERROR: 256:19  typedef  expected variable-declaration: 'isSubfolderVisible' to have a typedef
ERROR: 283:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 284:19  typedef  expected variable-declaration: 'isProjectFolderVisible' to have a typedef
ERROR: 303:15  typedef  expected variable-declaration: 'splitDelimeter' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/ide/theia/Terminal.ts:172:13
ERROR: 172:13  typedef  expected variable-declaration: 'terminalClass' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/third-parties/GitLoginPage.ts:22:29
ERROR: 22:29   typedef  expected member-variable-declaration: 'USERNAME_FIELD_LOCATOR' to have a typedef
ERROR: 23:29   typedef  expected member-variable-declaration: 'PASSWORD_FIELD_LOCATOR' to have a typedef
ERROR: 24:29   typedef  expected member-variable-declaration: 'SIGN_IN_BUTTON_LOCATOR' to have a typedef

/home/ndp/projects/che/tests/e2e/pageobjects/third-parties/GitOauthAppsSettings.ts:22:29
ERROR: 22:29   typedef  expected member-variable-declaration: 'GITHUB_OAUTH_APPS_SETTINGS_URL' to have a typedef

/home/ndp/projects/che/tests/e2e/tests/e2e/theia/GitPublishBranch.spec.ts:42:7
ERROR: 42:7    typedef  expected variable-declaration: 'wsNameGitPublishBranch' to have a typedef
ERROR: 43:7    typedef  expected variable-declaration: 'changedFile' to have a typedef
ERROR: 44:7    typedef  expected variable-declaration: 'branchName' to have a typedef
ERROR: 45:7    typedef  expected variable-declaration: 'file' to have a typedef
ERROR: 49:15   typedef  expected variable-declaration: 'wsConfig' to have a typedef
ERROR: 101:11  typedef  expected variable-declaration: 'confirmMessage' to have a typedef

/home/ndp/projects/che/tests/e2e/tests/e2e/theia/GitSelfSignCert.spec.ts:42:7
ERROR: 42:7    typedef  expected variable-declaration: 'workspaceName' to have a typedef
ERROR: 46:11   typedef  expected variable-declaration: 'gitProjectUrl' to have a typedef
ERROR: 47:11   typedef  expected variable-declaration: 'committedFile' to have a typedef
ERROR: 50:15   typedef  expected variable-declaration: 'wsConfig' to have a typedef
ERROR: 100:11  typedef  expected variable-declaration: 'confirmMessage' to have a typedef

/home/ndp/projects/che/tests/e2e/tests/e2e/theia/GitSsh.spec.ts:49:7
ERROR: 49:7    typedef  expected variable-declaration: 'wsNameCheckGeneratingKeys' to have a typedef
ERROR: 50:7    typedef  expected variable-declaration: 'wsNameCheckPropagatingKeys' to have a typedef
ERROR: 51:7    typedef  expected variable-declaration: 'committedFile' to have a typedef
ERROR: 55:15   typedef  expected variable-declaration: 'wsConfig' to have a typedef
ERROR: 85:15   typedef  expected variable-declaration: 'publicSshKey' to have a typedef
ERROR: 110:15  typedef  expected variable-declaration: 'data' to have a typedef
ERROR: 136:11  typedef  expected variable-declaration: 'confirmMessage' to have a typedef

/home/ndp/projects/che/tests/e2e/tests/e2e/theia/OpenshiftConnector.spec.ts:54:11
ERROR: 54:11   typedef  expected variable-declaration: 'wsConfig' to have a typedef

/home/ndp/projects/che/tests/e2e/tests/e2e_happy_path/theia/DevWorkspaceHappyPath.spec.ts:42:7
ERROR: 42:7    typedef  expected variable-declaration: 'globalTaskScope' to have a typedef
ERROR: 48:7    typedef  expected variable-declaration: 'SpringAppLocators' to have a typedef
ERROR: 168:9   typedef  expected variable-declaration: 'urlToPetClinicApp' to have a typedef
ERROR: 238:14  typedef  expected variable-declaration: 'index' to have a typedef
ERROR: 270:11  typedef  expected variable-declaration: 'httpClient' to have a typedef

/home/ndp/projects/che/tests/e2e/tests/e2e_happy_path/theia/HappyPath.spec.ts:61:7
ERROR: 61:7    typedef  expected variable-declaration: 'globalTaskScope' to have a typedef
ERROR: 63:7    typedef  expected variable-declaration: 'SpringAppLocators' to have a typedef

/home/ndp/projects/che/tests/e2e/tests/load_test/theia/LoadTest.spec.ts:37:15
ERROR: 37:15   typedef  expected variable-declaration: 'wsConfig' to have a typedef

/home/ndp/projects/che/tests/e2e/tests/plugins/theia/VscodeYamlPlugin.spec.ts:35:7
ERROR: 35:7    typedef  expected variable-declaration: 'yamlSchema' to have a typedef

/home/ndp/projects/che/tests/e2e/testsLibrary/theia/CodeExecutionTestsTheia.ts:84:27
ERROR: 84:27   typedef  expected variable-declaration: 'res' to have a typedef
ERROR: 151:22  typedef  expected variable-declaration: 'i' to have a typedef

/home/ndp/projects/che/tests/e2e/testsLibrary/theia/LanguageServerTestsTheia.ts:43:22
ERROR: 43:22   typedef  expected variable-declaration: 'i' to have a typedef

/home/ndp/projects/che/tests/e2e/testsLibrary/theia/ProjectAndFileTestsTheia.ts:37:21
ERROR: 37:21   typedef  expected variable-declaration: 'tabs' to have a typedef
ERROR: 39:26   typedef  expected variable-declaration: 'i' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/DriverHelper.ts:69:18
ERROR: 69:18   typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 88:18   typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 107:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 134:23  typedef  expected variable-declaration: 'visibleWebElement' to have a typedef
ERROR: 165:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 194:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 231:15  typedef  expected variable-declaration: 'isDisappeared' to have a typedef
ERROR: 267:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 312:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 332:23  typedef  expected variable-declaration: 'attributeValue' to have a typedef
ERROR: 355:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 375:23  typedef  expected variable-declaration: 'cssAttributeValue' to have a typedef
ERROR: 413:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 455:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 497:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 539:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 597:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 700:18  typedef  expected variable-declaration: 'i' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/Logger.ts:76:18
ERROR: 76:18   typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 83:18   typedef  expected variable-declaration: 'i' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/ScreenCatcher.ts:24:15
ERROR: 24:15   typedef  expected variable-declaration: 'executionScreenCastDir' to have a typedef
ERROR: 25:15   typedef  expected variable-declaration: 'executionScreenCastErrorsDir' to have a typedef
ERROR: 59:15   typedef  expected variable-declaration: 'screenshotStream' to have a typedef
ERROR: 68:19   typedef  expected variable-declaration: 'screenshotStream' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/VCS/CheGitApi.ts:8:19
ERROR: 8:19    typedef  expected member-variable-declaration: 'GIT_API_ENTRIPOINT_URL' to have a typedef
ERROR: 17:13   typedef  expected variable-declaration: 'responce' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/VCS/github/GitHubUtil.ts:6:27
ERROR: 6:27    typedef  expected member-variable-declaration: 'GITHUB_API_ENTRIPOINT_URL' to have a typedef
ERROR: 15:11   typedef  expected variable-declaration: 'authHeader' to have a typedef
ERROR: 17:11   typedef  expected variable-declaration: 'data' to have a typedef
ERROR: 38:13   typedef  expected variable-declaration: 'response' to have a typedef
ERROR: 49:11   typedef  expected variable-declaration: 'authHeader' to have a typedef
ERROR: 51:13   typedef  expected variable-declaration: 'response' to have a typedef
ERROR: 52:13   typedef  expected variable-declaration: 'stringified' to have a typedef
ERROR: 53:13   typedef  expected variable-declaration: 'arrayOfWorkspaces' to have a typedef
ERROR: 68:11   typedef  expected variable-declaration: 'authHeader' to have a typedef
ERROR: 78:11   typedef  expected variable-declaration: 'authHeader' to have a typedef
ERROR: 80:13   typedef  expected variable-declaration: 'response' to have a typedef
ERROR: 81:13   typedef  expected variable-declaration: 'stringified' to have a typedef
ERROR: 82:13   typedef  expected variable-declaration: 'arrayOfPublicKeys' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/WorkspaceNameHandler.ts:27:18
ERROR: 27:18   typedef  expected variable-declaration: 'i' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/requestHandlers/headers/CheMultiuserAuthorizationHeaderHandler.ts:25:17
ERROR: 25:17   typedef  expected variable-declaration: 'token' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts:21:11
ERROR: 21:11   typedef  expected variable-declaration: 'keycloakUrl' to have a typedef
ERROR: 23:11   typedef  expected variable-declaration: 'params' to have a typedef
ERROR: 31:13   typedef  expected variable-declaration: 'responseToObtainBearerToken' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/theia/PreferencesHandlerTheia.ts:53:13
ERROR: 53:13   typedef  expected variable-declaration: 'preferences' to have a typedef
ERROR: 96:13   typedef  expected variable-declaration: 'response' to have a typedef
ERROR: 103:13  typedef  expected variable-declaration: 'userPref' to have a typedef
ERROR: 105:17  typedef  expected variable-declaration: 'theiaPref' to have a typedef
ERROR: 112:17  typedef  expected variable-declaration: 'theiaPref' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/workspace/ApiUrlResolver.ts:29:15
ERROR: 29:15   typedef  expected variable-declaration: 'namespace' to have a typedef
ERROR: 41:19   typedef  expected variable-declaration: 'kubernetesResponse' to have a typedef

/home/ndp/projects/che/tests/e2e/utils/workspace/TestWorkspaceUtil.ts:41:18
ERROR: 41:18   typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 42:19   typedef  expected variable-declaration: 'response' to have a typedef
ERROR: 59:17   typedef  expected variable-declaration: 'waitTime' to have a typedef
ERROR: 68:13   typedef  expected variable-declaration: 'stopWorkspaceResponse' to have a typedef
ERROR: 89:13   typedef  expected variable-declaration: 'deleteWorkspaceResponse' to have a typedef
ERROR: 106:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 118:17  typedef  expected variable-declaration: 'waitTime' to have a typedef
ERROR: 134:13  typedef  expected variable-declaration: 'response' to have a typedef
ERROR: 135:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 144:13  typedef  expected variable-declaration: 'response' to have a typedef
ERROR: 146:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 156:13  typedef  expected variable-declaration: 'response' to have a typedef
ERROR: 158:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 174:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 175:19  typedef  expected variable-declaration: 'response' to have a typedef
ERROR: 203:15  typedef  expected variable-declaration: 'getAllWorkspacesResponse' to have a typedef
ERROR: 210:13  typedef  expected variable-declaration: 'stringified' to have a typedef
ERROR: 211:13  typedef  expected variable-declaration: 'arrayOfWorkspaces' to have a typedef
ERROR: 227:15  typedef  expected variable-declaration: 'getWorkspacesByNameResponse' to have a typedef
ERROR: 239:19  typedef  expected variable-declaration: 'getAllWorkspacesResponse' to have a typedef
ERROR: 245:17  typedef  expected variable-declaration: 'stringified' to have a typedef
ERROR: 246:17  typedef  expected variable-declaration: 'arrayOfWorkspaces' to have a typedef
ERROR: 270:19  typedef  expected variable-declaration: 'deleteWorkspaceResponse' to have a typedef
ERROR: 287:13  typedef  expected variable-declaration: 'stopWorkspaceResponse' to have a typedef
ERROR: 301:13  typedef  expected variable-declaration: 'wsStatus' to have a typedef
ERROR: 302:18  typedef  expected variable-declaration: 'i' to have a typedef
ERROR: 312:17  typedef  expected variable-declaration: 'waitTime' to have a typedef

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @eclipse-che/che-e2e@7.58.0-SNAPSHOT lint: `tslint --fix -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @eclipse-che/che-e2e@7.58.0-SNAPSHOT lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ndp/.npm/_logs/2022-12-24T15_40_10_385Z-debug.log
```

### Describe the solution you'd like

Possible solution: use node.js 16 when build quay.io/eclipse/che-e2e [3].

[3] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### Describe alternatives you've considered

Downgrade version of "axios" library to 0.22.

### Additional context
Related issue: https://github.com/eclipse/che/issues/21763

**Comment by dmytro-ndp** [comment]
quay.io/eclipse/che-e2e image build has been fixed: https://github.com/eclipse/che/actions/runs/3823838547
