### ISSUE TITLE
HappyPath tests fails

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21940]
### Describe the bug

HappyPath tests fails with the stacktrace

```
✖ ERROR: TypeError: Reflect.hasOwnMetadata is not a function
    at _tagParameterOrProperty (/tmp/e2e/node_modules/inversify/lib/annotation/decorator_utils.js:22:17)
    at Object.tagParameter (/tmp/e2e/node_modules/inversify/lib/annotation/decorator_utils.js:7:5)
    at /tmp/e2e/node_modules/inversify/lib/annotation/inject.js:24:31
    at /tmp/e2e/dist/utils/requestHandlers/CheApiRequestHandler.js:21:37
    at __decorate (/tmp/e2e/dist/utils/requestHandlers/CheApiRequestHandler.js:14:95)
    at Object.<anonymous> (/tmp/e2e/utils/requestHandlers/CheApiRequestHandler.ts:19:34)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/tmp/e2e/utils/theia/PreferencesHandlerTheia.ts:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/tmp/e2e/tests/MochaHooks.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at formattedImport (/tmp/e2e/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at exports.requireOrImport (/tmp/e2e/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at exports.handleRequires (/tmp/e2e/node_modules/mocha/lib/cli/run-helpers.js:94:28)
    at /tmp/e2e/node_modules/mocha/lib/cli/run.js:353:25
```

### Che version

7.59@latest

### Steps to reproduce

Run HappyPath tests

### Expected behavior

HappyPath tests run successfully.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by dmytro-ndp** [comment]
It could be related to recent commit https://github.com/eclipse/che/commit/02b2ac759d122ae2e32ac9b0ddd0ee90fd35b250

More details are needed.

Is it about EmptyWorkspace test run?
Which command were used to run the test?
Which npm version did you have when run test? npm 9.x is preferable one.

**Comment by tolusha** [comment]
1. I can reproduce it for both `test-empty-workspace-devworkspace-happy-path-code` and `test-devworkspace-happy-path-code` suites.

2. 
```bash
export DEVWORKSPACE_HAPPY_PATH="https://raw.githubusercontent.com/eclipse/che/main/tests/devworkspace-happy-path"
bash <(curl -s ${DEVWORKSPACE_HAPPY_PATH}/remote-launch.sh)
```

3. I don't know. I thought tests are run inside container `quay.io/eclipse/che-e2e`

**Comment by dmytro-ndp** [comment]
@tolusha : thank you for details.

I was able to reproduce the error too, with command `npm run test-devworkspace-happy-path-code`.
