### ISSUE TITLE
Strict check for JSON comments

### ISSUE THREAD

**Issue by ArvinB** [eclipse/che#22015]
### Describe the bug

@svor I believe I found a bug with the typescript code that is used to strip comments out of a json file.

Specifically [here](https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-code/code/src/vs/base/common/stripComments.js#L6).

This is especially true for `.vscode/extensions.json`

FYI @nickboldt 

### Che version

7.60@latest

### Steps to reproduce

1. Create a devfile where the file `.vscode/extensions.json` does not contain a comment
2. Run the generate devworkspace template [script](https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-devfileregistry/build/scripts/generate_devworkspace_templates.sh)

### Expected behavior

Everything runs just fine with or without comments in the json file.

### Runtime

other (please specify in additional context)

### Screenshots

N/A

### Installation method

other (please specify in additional context)

### Environment

Linux

### Eclipse Che Logs

Here is the stack trace:

```shell
stack=TypeError: text.charCodeAt is not a function

    at Object.scanNext [as scan] (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/jsonc-parser/lib/umd/impl/scanner.js:187:29)

    at Object.stripComments (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/jsonc-parser/lib/umd/impl/parser.js:619:29)

    at VscodeExtensionJsonAnalyzer.extractPlugins (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/devfile/vscode-extension-json-analyzer.js:28:45)

    at CheTheiaPluginsDevfileResolver.handle (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/devfile/che-theia-plugins-devfile-resolver.js:53:71)

    at Generate.generate (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/generate.js:82:51)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Main.start (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/main.js:88:13)

    at async /home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/entrypoint.js:18:21

Unable to start TypeError: text.charCodeAt is not a function

    at Object.scanNext [as scan] (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/jsonc-parser/lib/umd/impl/scanner.js:187:29)

    at Object.stripComments (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/jsonc-parser/lib/umd/impl/parser.js:619:29)

    at VscodeExtensionJsonAnalyzer.extractPlugins (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/devfile/vscode-extension-json-analyzer.js:28:45)

    at CheTheiaPluginsDevfileResolver.handle (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/devfile/che-theia-plugins-devfile-resolver.js:53:71)

    at Generate.generate (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/generate.js:82:51)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Main.start (/home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/main.js:88:13)

    at async /home/travis/build/Zowe-Commercial/wazi-devspaces-images/devspaces-devfileregistry/node_modules/@eclipse-che/che-theia-devworkspace-handler/lib/entrypoint.js:18:21

The command "sh -c 'cd ${CONTEXT_DEVFILE} && ./build/scripts/generate_devworkspace_templates.sh'" failed and exited with 1 during .
```

### Additional context

It would be nice to know more about what the following output means:

```
redhat/ansible/latest is missing on the plug-in registry but it is flagged as optional, skipping it
ibm/zopeneditor/latest is missing on the plug-in registry but it is flagged as optional, skipping it
zowe/vscode-extension-for-zowe/latest is missing on the plug-in registry but it is flagged as optional, skipping it
```

**Comment by ArvinB** [comment]
@svor Any update?

**Comment by ArvinB** [comment]
Yes even for generating VSCode Dev workspaces template that strip comments from Json function is used still.

**Comment by svor** [comment]
@ArvinB could you please elaborate what are you trying to do
in my steps:
1. Clone https://github.com/redhat-developer/devspaces
2. cd devspaces/dependencies/che-devfile-registry
3. ./build/scripts/generate_devworkspace_templates.sh

I don't see any error

what do you mean by 
> Create a devfile where the file .vscode/extensions.json does not contain a comment

**Comment by ArvinB** [comment]
Hi @svor 

So nearly all devfiles have a repo URL like this one:

https://github.com/devspaces-samples/python-hello-world/tree/devspaces-3-rhel-8

In the `.vscode` folder when generating the template it reads the files, specifically `extensions.json` which has these comments.
See here for example:
https://github.com/devspaces-samples/python-hello-world/blob/devspaces-3-rhel-8/.vscode/extensions.json#L2-L3

So if you have a repo like this with the `extensions.json` without that comment, you can reproduce the error as raised above.

I'm not a Type Script expert but my colleagues believe this is being caused because of the `use strict` located in the code here:
https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-code/code/src/vs/base/common/stripComments.js#L6

**Comment by svor** [comment]
@ArvinB since 3.4 the generation process was reworked, so the problem could be fixed.
