### ISSUE TITLE
Token seems to not refresh automatically when expired (Amazon EKS 1.25, External Keycloak as OIDC)

### ISSUE THREAD

**Issue by Deddinho23** [eclipse/che#22073]
### Describe the bug

When the JWT expired, Che redirects forcefully the user to re-login from the dashboard

### Che version

next (development version)

### Steps to reproduce

1. Whatever you are doing in Che
2. *Token expired*
3. If you make any further actions from now on, you'll redirect to a page that tells you to login in the Dashboard (page's screenshot below) 

### Expected behavior

When the tokens expiring, I expect them to auto refresh for keeping the user logged, without the explicit re-login

### Runtime

Kubernetes (vanilla)

### Screenshots

The redirect page after the token expired:
![image](https://user-images.githubusercontent.com/48152430/226406946-d08e49c9-68ae-4bcd-b366-b906a9be2112.png)

URL that respond with 500 in the first screenshot
![image](https://user-images.githubusercontent.com/48152430/226407650-aafa3925-a0fe-42f1-9019-cebfa2c4906c.png)

### Installation method

chectl/latest, other (please specify in additional context)

### Environment

Amazon

### Eclipse Che Logs

```shell
che.log
2023-03-20 16:01:58,361[nio-8080-exec-6]  [ERROR] [o.a.c.c.C.[.[.[/api].[default] 175]  - Servlet.service() for servlet [default] in context with path [/api] threw exception
io.jsonwebtoken.ExpiredJwtException: JWT expired at 2023-03-20T15:14:14Z. Current time: 2023-03-20T16:01:58Z, a difference of 2861332 milliseconds.  Allowed clock skew: 3000 milliseconds.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:448)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:550)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:610)
	at io.jsonwebtoken.impl.ImmutableJwtParser.parseClaimsJws(ImmutableJwtParser.java:173)
	at org.eclipse.che.multiuser.oidc.filter.OidcTokenInitializationFilter.processToken(OidcTokenInitializationFilter.java:80)
	at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:127)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:872)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1705)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-20 16:01:58,485[nio-8080-exec-8]  [ERROR] [o.a.c.c.C.[.[.[/api].[default] 175]  - Servlet.service() for servlet [default] in context with path [/api] threw exception
io.jsonwebtoken.ExpiredJwtException: JWT expired at 2023-03-20T15:14:14Z. Current time: 2023-03-20T16:01:58Z, a difference of 2861483 milliseconds.  Allowed clock skew: 3000 milliseconds.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:448)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:550)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:610)
	at io.jsonwebtoken.impl.ImmutableJwtParser.parseClaimsJws(ImmutableJwtParser.java:173)
	at org.eclipse.che.multiuser.oidc.filter.OidcTokenInitializationFilter.processToken(OidcTokenInitializationFilter.java:80)
	at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:127)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:872)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1705)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Additional context

Operator Version:
_chectl/0.0.20230314-next.f7d1fd4 win32-x64 node-v16.13.2_

About page:
![image](https://user-images.githubusercontent.com/48152430/226410737-d0042471-9d5a-4562-bd73-4a20893885d2.png)

**Comment by ibuziuk** [comment]
cc: @olexii4 @akurinnoy could you please take a look? I believe this is expected behavior. @Deddinho23 could you please clarify what is the lifetime of the token?

**Comment by Deddinho23** [comment]
The default lifetime of the token should be 5 minutes in Keycloak, in this case I edit it to be 10 minutes as a possible workaround, screenshot of the setting below:
![image](https://user-images.githubusercontent.com/48152430/226455168-f154b452-e92b-4d89-93cc-02209278918d.png)

Idk if this can help, but here it is a slice of oauth-proxy.log:
```
10.99.11.49:47748 - 508a8b54-50db-4797-8ce3-9f51274ea8cf - <user> [2023/03/20 16:01:57] <cheURL> GET / "/dashboard/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 200 1178 0.004
10.99.11.49:47748 - 9457abf0-8794-4bff-88ee-68214f99405d - <user> [2023/03/20 16:01:57] <cheURL> GET / "/dashboard/service-worker.js" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 200 63 0.003
10.99.11.49:47752 - d57163e6-42b6-425a-aac3-6f0dd118b018 - <user> [2023/03/20 16:01:57] <cheURL> GET / "/dashboard/editor.worker.js" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 200 1606 0.005
10.99.11.49:47752 - b91e1bfb-4f89-4004-b8d3-1db50e38f6b1 - <user> [2023/03/20 16:01:58] <cheURL> POST / "/api/kubernetes/namespace/provision" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 500 2016 0.155
10.99.11.49:47752 - 94f269fa-03df-4dfb-b352-a9171d019af9 - <user> [2023/03/20 16:01:58] <cheURL> POST / "/api/kubernetes/namespace/provision" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 500 2016 0.018
10.99.11.49:47752 - cd587498-eff7-4021-a8da-b3148123283b - <user> [2023/03/20 16:01:59] <cheURL> GET / "/dashboard/service-worker.js" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 200 63 0.003
10.99.11.49:47752 - 53039067-fe7c-44dd-bc71-c333a4611e2c - - [2023/03/20 16:02:00] <cheURL> GET - "/oauth/sign_in" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 302 375 0.000
10.99.11.49:47752 - eddf2017-a331-4425-8397-2646171780b7 - <user> [2023/03/20 16:02:00] [AuthSuccess] Authenticated via OAuth2: Session{email:<redacted> user:<redacted> PreferredUsername:<redacted> token:true id_token:true created:2023-03-20 16:02:00.943961773 +0000 UTC m=+6615.840274452 expires:2023-03-20 16:12:00.94356124 +0000 UTC m=+7215.839873930 refresh_token:true groups:<redacted>}
[2023/03/20 16:02:00] [session_store.go:163] WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.
10.99.11.49:47752 - eddf2017-a331-4425-8397-2646171780b7 - - [2023/03/20 16:02:00] <cheURL> GET - "/oauth/callback?state=icOi7HIWfnE7M5jXKyBAJ56h_raZENL0wH2qltrJFYo%3A%2F&session_state=d1564f4f-ff6e-45b1-b352-b58011720e18&code=ba1d7585-f12e-4f02-9143-17e645a74875.d1564f4f-ff6e-45b1-b352-b58011720e18.f79972a8-08b7-4d65-a1c1-bdd8088f42ed" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 302 24 0.058
10.99.11.49:47752 - 98db5462-0db5-4f96-a7b0-cc9744272282 - <user> [2023/03/20 16:02:01] <cheURL> GET / "/dashboard/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 200 1178 0.003
```
The previous token was expired at _2023-03-20 15:14:14.124809816_

**Comment by olexii4** [comment]
@Deddinho23 This is expected behavior because we support different identity providers and don't refresh the Keycloak token automatically. This problem could be solved by increasing the access token lifespan.
