### ISSUE TITLE
che dashboard is crashing with std::bad_alloc

### ISSUE THREAD

**Issue by ddoan** [eclipse/che#22266]
### Describe the bug

che-dashboard pod crashes with

```
Starting Dashboard backend server...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Dashboard backend server is stopped.
```

### Che version

7.68@latest

### Steps to reproduce

- Mac M1 using Lima to install x86_64 Docker ([docker.yaml](https://gist.github.com/ddoan/86ef48d090e5f08ff65ad75f739514f5))

```
[doug@lima-docker lima]$ uname -a
Linux lima-docker 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux
```

- I [hacked minikube](https://github.com/kubernetes/minikube/issues/16622) to deploy an amd64 cluster. 

- I pulled the amd64 images inside minikube first

```
$ minikube ssh

docker@minikube:~$ docker pull quay.io/eclipse/che-dashboard:7.68.0 --platform amd64
docker@minikube:~$ docker pull quay.io/eclipse/che-operator:7.68.0 --platform amd64
docker@minikube:~$ docker pull quay.io/eclipse/che-plugin-registry:7.68.0 --platform amd64
```

- Then deployed using

```
chectl server:deploy \
	--k8spoddownloadimagetimeout=12000000 \
	--k8spoderrorrechecktimeout=600000 \
	--k8spodreadytimeout=600000 \
	--k8spodwaittimeout=600000 \
	--platform=minikube
```

- It gets to here before crashing

```
  ❯ Wait for Eclipse Che ready
    ✔ Devfile Registry pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ✔ Plugin Registry pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ❯ Dashboard pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✖ Starting
        → Failed to start a pod, reason: Completed
      Gateway pod bootstrap
      Eclipse Che Server pod bootstrap
      Wait Eclipse Che active
    Retrieving Eclipse Che self-signed CA certificate
    Prepare post installation output
    Error: Command server:deploy failed with the error: Failed to start a pod, reason:
```

Logs say 

```
Starting Dashboard backend server...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Dashboard backend server is stopped.
```

### Expected behavior

Pod should not crash.

### Runtime

minikube

### Installation method

chectl/latest

### Environment

macOS

### Eclipse Che Logs

[eclipse-che.zip](https://github.com/eclipse/che/files/11643215/eclipse-che.zip)

**Comment by ddoan** [comment]
Thanks I ran that and enabled core dumps.

```
$ docker run --platform linux/amd64 --ulimit core=-1 --privileged -ti --rm --entrypoint=sh quay.io/eclipse/che-dashboard:7.68.0
/ # sysctl -w kernel.core_pattern="/tmp/%e_core_dump.%p"
/ # cd /tmp
/tmp # node /backend/server/backend.js --publicFolder /public
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
/tmp # ls
node_core_dump.17  v8-compile-cache-0
```

I copied off this core file into another docker with gdb installed.

```
root@89da68bcbbd5:/# gdb node node_core_dump.17
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
BFD: warning: /node: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
BFD: warning: /node: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
Reading symbols from node...done.
[New LWP 17]
[New LWP 19]
[New LWP 22]
[New LWP 21]
[New LWP 20]
[New LWP 18]
[New LWP 23]

warning: Can't read pathname for load map: Unknown error -1.
BFD: warning: /usr/lib/libstdc++.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
BFD: warning: /usr/lib/libstdc++.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
BFD: warning: /usr/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
BFD: warning: /usr/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
BFD: warning: /lib/ld-musl-x86_64.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
BFD: warning: /lib/ld-musl-x86_64.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
Core was generated by `node /backend/server/backend.js --publicFolder /public'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f23986a83f1 in setjmp () from /lib/ld-musl-x86_64.so.1
[Current thread is 1 (LWP 17)]
```

`bt` doesn't seem all that helpful however.

```
(gdb) bt
#0  0x00007f23986a83f1 in setjmp () from /lib/ld-musl-x86_64.so.1
#1  0x00007f23986a854c in raise () from /lib/ld-musl-x86_64.so.1
#2  0x00007f23986a99a8 in ?? () from /lib/ld-musl-x86_64.so.1
#3  0x00007f23986f8e98 in ?? () from /lib/ld-musl-x86_64.so.1
#4  0x0000000000000000 in ?? ()
```
