### ISSUE TITLE
Che-server image built by the PR GitHub action fails to start

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#22384]
### Describe the bug

A test image built by a test [`che-server` PR](https://github.com/eclipse-che/che-server/pull/534): `quay.io/eclipse/che-server:pr-534` fails to start with an error. The issue affects all new che-server Pull Requests.

A `che-server` built locally starts without any issues.

### Che version

next (development version)

### Steps to reproduce

Deploy che with the image built by the GitHub action: `quay.io/eclipse/che-server:pr-534`
See the error:
```
Using custom assembly from /home/user/eclipse-che
Certificate was added to keystore
Certificate was added to keystore
Certificate was added to keystore
Certificate was added to keystore
Imported 4 certificates from /public-certs/kube-root-ca.crt.ca.crt
Listening for transport dt_socket at address: 8000
Handler error
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:556)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:489)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:299)
	at java.logging/java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:445)
	at java.logging/java.util.logging.LogManager$2.run(LogManager.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.logging/java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:382)
	at java.logging/java.util.logging.LogManager.getLogManager(LogManager.java:430)
	at java.logging/java.util.logging.Logger.demandLogger(Logger.java:648)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:717)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:701)
	at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:61)
	at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:181)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:133)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:156)
	at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:211)
	at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:52)
Caused by: java.lang.Error: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.el8.x86_64/lib/tzdb.dat (No such file or directory)
	at java.base/sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:261)
	at java.base/sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:251)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.util.calendar.ZoneInfoFile.<clinit>(ZoneInfoFile.java:251)
	at java.base/sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:588)
	at java.base/java.util.TimeZone.getTimeZone(TimeZone.java:577)
	at java.base/java.util.TimeZone.setDefaultZone(TimeZone.java:682)
	at java.base/java.util.TimeZone.getDefaultRef(TimeZone.java:653)
	at java.base/java.util.TimeZone.getDefault(TimeZone.java:642)
	at java.base/java.util.Calendar.defaultTimeZone(Calendar.java:1679)
	at java.base/java.util.Calendar.getInstance(Calendar.java:1660)
	at java.base/java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:676)
	at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:620)
	at org.apache.juli.DateFormatCache$Cache.<init>(DateFormatCache.java:124)
	at org.apache.juli.DateFormatCache.<init>(DateFormatCache.java:90)
	at org.apache.juli.OneLineFormatter.setTimeFormat(OneLineFormatter.java:103)
	at org.apache.juli.OneLineFormatter.<init>(OneLineFormatter.java:74)
	at org.apache.juli.FileHandler.configure(FileHandler.java:398)
	at org.apache.juli.FileHandler.<init>(FileHandler.java:119)
	at org.apache.juli.FileHandler.<init>(FileHandler.java:107)
	at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:79)
	at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:74)
	at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:70)
	at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:66)
	... 21 more
Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.el8.x86_64/lib/tzdb.dat (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:255)
	... 44 more
```

### Expected behavior

The image built by the GitHub action must start successfully 

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

macOS

**Comment by svor** [comment]
I see the same problem in plugin-registry repo https://github.com/eclipse-che/che-plugin-registry/actions/runs/5649932923/job/15305301023?pr=1742#step:6:1791. For plugin registry the problem should be fixed by https://github.com/eclipse-che/che-plugin-registry/pull/1736.
