### ISSUE TITLE
Deployment of Eclipse Che operator on minikube timeouts

### ISSUE THREAD

**Issue by Deel96** [eclipse/che#22402]
### Describe the bug

The Eclipse Che operator fails to be deployed because of a timeout.

### Che version

7.71@latest

### Steps to reproduce

1. minikube start --addons=ingress,dashboard --vm=true --memory=10240 --cpus=4
1. chectl server:deploy --platform minikube

### Expected behavior

Deplyoment should succeed

### Runtime

minikube

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
2023-07-26T19:06:21.959Z Error: Command server:deploy failed with the error: ERR_TIMEOUT: Timeout set to pod ready timeout 60000 See details: /home/user/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1690398147806.
2023-07-26T19:06:21.959Z     at Object.newError (~/.local/share/chectl/client/7.71.0/lib/utils/utls.js:37:19)
2023-07-26T19:06:21.959Z     at Object.wrapCommandError (~/.local/share/chectl/client/7.71.0/lib/utils/command-utils.js:53:19)
2023-07-26T19:06:21.959Z     at Deploy.<anonymous> (~/.local/share/chectl/client/7.71.0/lib/commands/server/deploy.js:82:44)
2023-07-26T19:06:21.959Z     at Generator.throw (<anonymous>)
2023-07-26T19:06:21.959Z     at rejected (~/.local/share/chectl/client/7.71.0/node_modules/tslib/tslib.js:165:69)
2023-07-26T19:06:21.959Z Cause: Error: ERR_TIMEOUT: Timeout set to pod ready timeout 60000
2023-07-26T19:06:21.959Z     at KubeClient.<anonymous> (~/.local/share/chectl/client/7.71.0/lib/api/kube-client.js:827:19)
2023-07-26T19:06:21.959Z     at Generator.next (<anonymous>)
2023-07-26T19:06:21.959Z     at fulfilled (~/.local/share/chectl/client/7.71.0/node_modules/tslib/tslib.js:164:62)
```

### Additional context

❯ Deploy Eclipse Che operator
    ❯ Install Dev Workspace operator
      ✔ Create Namespace devworkspace-controller...[Created]
      ✔ Create Dev Workspace operator resources...[Created]
      ✖ Wait for Dev Workspace operator ready
        → ERR_TIMEOUT: Timeout set to pod ready timeout 60000

**Comment by tolusha** [comment]
@Deel96 
What is minikube version? I don't have any issues with:
```
minikube version
minikube version: v1.29.0
commit: ddac20b4b34a9c8c857fc602203b6ba2679794d3
```

Could you check events:  `oc get events -n devworkspace-controller`

**Comment by Deel96** [comment]
> @Deel96 What is minikube version? I don't have any issues with:
> 
> ```
> minikube version
> minikube version: v1.29.0
> commit: ddac20b4b34a9c8c857fc602203b6ba2679794d3
> ```


I use 1.31.1:
minikube version: v1.31.1
commit: fd3f3801765d093a485d255043149f92ec0a695f

On another machine where I have no problems.
The machine where I get the timeouts has a relativly slow internet connection. Maybe this is the problem?
Is there a way to increase the timeout or to prepull e.g. images?

> @Deel96 What is minikube version? I don't have any issues with:
> 
> ```
> minikube version
> minikube version: v1.29.0
> commit: ddac20b4b34a9c8c857fc602203b6ba2679794d3
> ```
> 
> Could you check events: `oc get events -n devworkspace-controller`

oc just works for OpenShift Clusters or not?

**Comment by Deel96** [comment]
@tolusha 

After some googlng I guess the command for minikube is:
`kubectl get events -n devworkspace-controller`


```
user@pc:~$ kubectl get events -n devworkspace-controller
LAST SEEN   TYPE      REASON              OBJECT                                                          MESSAGE
2m41s       Normal    LeaderElection      lease/8d217f93.devfile.io                                       devworkspace-controller-manager-65ff55699f-92jwx_73836259-618e-404c-b131-7db4153a420a became leader
3m55s       Normal    Scheduled           pod/devworkspace-controller-manager-65ff55699f-92jwx            Successfully assigned devworkspace-controller/devworkspace-controller-manager-65ff55699f-92jwx to minikube
3m55s       Warning   FailedMount         pod/devworkspace-controller-manager-65ff55699f-92jwx            MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "devworkspace-operator-webhook-cert" not found
3m53s       Normal    Pulling             pod/devworkspace-controller-manager-65ff55699f-92jwx            Pulling image "quay.io/devfile/devworkspace-controller:v0.21.2"
2m42s       Normal    Pulled              pod/devworkspace-controller-manager-65ff55699f-92jwx            Successfully pulled image "quay.io/devfile/devworkspace-controller:v0.21.2" in 1m11.360479969s (1m11.360515759s including waiting)
2m41s       Normal    Created             pod/devworkspace-controller-manager-65ff55699f-92jwx            Created container devworkspace-controller
2m41s       Normal    Started             pod/devworkspace-controller-manager-65ff55699f-92jwx            Started container devworkspace-controller
2m41s       Normal    Pulling             pod/devworkspace-controller-manager-65ff55699f-92jwx            Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1"
2m27s       Normal    Pulled              pod/devworkspace-controller-manager-65ff55699f-92jwx            Successfully pulled image "gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1" in 13.93072495s (13.930840287s including waiting)
2m27s       Normal    Created             pod/devworkspace-controller-manager-65ff55699f-92jwx            Created container kube-rbac-proxy
2m27s       Normal    Started             pod/devworkspace-controller-manager-65ff55699f-92jwx            Started container kube-rbac-proxy
3m55s       Normal    SuccessfulCreate    replicaset/devworkspace-controller-manager-65ff55699f           Created pod: devworkspace-controller-manager-65ff55699f-92jwx
3m55s       Normal    ScalingReplicaSet   deployment/devworkspace-controller-manager                      Scaled up replica set devworkspace-controller-manager-65ff55699f to 1
3m55s       Normal    cert-manager.io     certificaterequest/devworkspace-controller-serving-cert-tbnrl   Certificate request has been approved by cert-manager.io
3m55s       Warning   BadConfig           certificaterequest/devworkspace-controller-serving-cert-tbnrl   Certificate will be issued with an empty Issuer DN, which contravenes RFC 5280 and could break some strict clients
3m55s       Normal    CertificateIssued   certificaterequest/devworkspace-controller-serving-cert-tbnrl   Certificate fetched from issuer successfully
3m55s       Normal    Issuing             certificate/devworkspace-controller-serving-cert                Issuing certificate as Secret does not exist
3m55s       Normal    Generated           certificate/devworkspace-controller-serving-cert                Stored new private key in temporary Secret resource "devworkspace-controller-serving-cert-c2jtb"
3m55s       Normal    Requested           certificate/devworkspace-controller-serving-cert                Created new CertificateRequest resource "devworkspace-controller-serving-cert-tbnrl"
3m55s       Normal    Issuing             certificate/devworkspace-controller-serving-cert                The certificate has been successfully issued
2m40s       Normal    Scheduled           pod/devworkspace-webhook-server-5bb96f454b-64tb9                Successfully assigned devworkspace-controller/devworkspace-webhook-server-5bb96f454b-64tb9 to minikube
2m40s       Normal    Pulling             pod/devworkspace-webhook-server-5bb96f454b-64tb9                Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1"
2m26s       Normal    Pulled              pod/devworkspace-webhook-server-5bb96f454b-64tb9                Successfully pulled image "gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1" in 696.422407ms (13.519760046s including waiting)
2m26s       Normal    Created             pod/devworkspace-webhook-server-5bb96f454b-64tb9                Created container kube-rbac-proxy
2m26s       Normal    Started             pod/devworkspace-webhook-server-5bb96f454b-64tb9                Started container kube-rbac-proxy
2m26s       Normal    Pulling             pod/devworkspace-webhook-server-5bb96f454b-64tb9                Pulling image "quay.io/devfile/devworkspace-controller:v0.21.2"
2m24s       Normal    Pulled              pod/devworkspace-webhook-server-5bb96f454b-64tb9                Successfully pulled image "quay.io/devfile/devworkspace-controller:v0.21.2" in 1.798828616s (1.798889736s including waiting)
2m24s       Normal    Created             pod/devworkspace-webhook-server-5bb96f454b-64tb9                Created container webhook-server
2m24s       Normal    Started             pod/devworkspace-webhook-server-5bb96f454b-64tb9                Started container webhook-server
2m41s       Normal    SuccessfulCreate    replicaset/devworkspace-webhook-server-5bb96f454b               Created pod: devworkspace-webhook-server-5bb96f454b-64tb9
2m41s       Normal    ScalingReplicaSet   deployment/devworkspace-webhook-server                          Scaled up replica set devworkspace-webhook-server-5bb96f454b to 1

```

**Comment by Deel96** [comment]
The deployment worked for me, if I use the dollowing command:

`chectl server:deploy --platform minikube --k8spoderrorrechecktimeout=600000 --k8spodreadytimeout=600000 --k8spodwaittimeout=600000`

I don't know which timeout has to be increased specifically, but that are the one I found in the GitHub Repo of chectl
