### ISSUE TITLE
Blank page instead of login page when open Dashboard

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22476]
### Describe the bug

There was blank page shown when open Dashboard page

### Che version

next (development version)

### Steps to reproduce

Deploy Eclipse Che Next to OpenShift using the link https://eclipse-che.apps.<ocp-host>/

### Expected behavior

Login page is opened

### Runtime

OpenShift OAuth login page is opened.

### Screenshots

![eclipse-che-next_2023-09-05](https://github.com/eclipse/che/assets/1197777/7973002d-31f9-454e-91f7-a7a76ba218ae)

### Installation method

chectl/next

### Environment

Eclipse Che was deployed to OCP v4.13

### Eclipse Che Logs

There was next error message in che-server log:
```
05-Sep-2023 18:34:32.026 FINE [main] com.google.inject.internal.aop.UnsafeClassDefiner.tryPrivileged Cannot bind Unsafe.defineAnonymousClass
	java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineAnonymousClass(java.lang.Class,[B,[Ljava.lang.Object;)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
		at com.google.inject.internal.aop.UnsafeClassDefiner.tryPrivileged(UnsafeClassDefiner.java:136)
		at com.google.inject.internal.aop.UnsafeClassDefiner.<clinit>(UnsafeClassDefiner.java:58)
		at com.google.inject.internal.aop.ClassDefining.bindClassDefiner(ClassDefining.java:63)
		at com.google.inject.internal.aop.ClassDefining$ClassDefinerHolder.<clinit>(ClassDefining.java:38)
		at com.google.inject.internal.aop.ClassDefining.hasPackageAccess(ClassDefining.java:49)
		at com.google.inject.internal.aop.ClassBuilding.canFastInvoke(ClassBuilding.java:227)
		at com.google.inject.internal.BytecodeGen.fastMethod(BytecodeGen.java:147)
		at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:68)
		at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:327)
		at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:136)
		at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:106)
		at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
		at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:418)
		at com.google.inject.AbstractModule.install(AbstractModule.java:106)
		at com.google.inject.servlet.ServletModule.configure(ServletModule.java:49)
		at com.google.inject.AbstractModule.configure(AbstractModule.java:64)
		at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
		at com.google.inject.spi.Elements.getElements(Elements.java:108)
		at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
		at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
		at com.google.inject.Guice.createInjector(Guice.java:87)
		at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:137)
		at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
		at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:81)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4453)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4885)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:713)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:975)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1949)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:776)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1656)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:898)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:846)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:871)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:241)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:912)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
	Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineAnonymousClass(java.lang.Class,[B,[Ljava.lang.Object;)
		at java.base/java.lang.Class.getMethod(Class.java:2227)
		at com.google.inject.internal.aop.UnsafeClassDefiner.bindAnonymousDefineMethod(UnsafeClassDefiner.java:131)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
		... 65 more
```
Che-server logs file: [test-jenkins-2-htwzb-jenkins.log](https://github.com/eclipse/che/files/12527679/test-jenkins-2-htwzb-jenkins.log)

Google Chrome .har file text: [eclipse-che.apps.ocp413-dnochev.crw-qe.com.har.txt](https://github.com/eclipse/che/files/12527711/eclipse-che.apps.ocp413-dnochev.crw-qe.com.har.txt)

### Additional context

Reproduced in Google Chrome and Mozilla Firefox

### Workaround
Add path `dashboard` to the link: https://eclipse-che.apps.<ocp-host>/dashboard/
(Thanks @AObuchow for finding)

**Comment by AObuchow** [comment]
I experienced this issue as well on the Dogfooding instance.  On the dogfooding instance, visiting the `<CHE-HOST>` URL wouldn't direct me to authenticate, however `<CHE-HOST>/dashboard/` did bring up the authentication page, which successfully redirected me to the Che dashboard. Afterwards, visiting the `<CHE-HOST>` URL properly redirected me to the dashboard.
