### ISSUE TITLE
Build command in nodejs-angular sample is failed

### ISSUE THREAD

**Issue by svor** [eclipse/che#22596]
### Describe the bug

After upgrading node to 18.x in UDI, it's not possible to build nodejs-angular sample using **Build application** command, it fails with an output:
```
 *  Executing task: devfile: Build application 

yarn run v1.22.17
$ ng build --prod  --base-href ./ && cp CNAME dist/CNAME
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
⠸ Generating browser application bundles (phase: building)...node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/projects/nodejs-angular/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/projects/nodejs-angular/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/projects/nodejs-angular/node_modules/webpack/lib/NormalModule.js:471:10)
    at /projects/nodejs-angular/node_modules/webpack/lib/NormalModule.js:503:5
    at /projects/nodejs-angular/node_modules/webpack/lib/NormalModule.js:358:12
    at /projects/nodejs-angular/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/projects/nodejs-angular/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/projects/nodejs-angular/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /projects/nodejs-angular/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/projects/nodejs-angular/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/projects/nodejs-angular/node_modules/css-loader/dist/index.js:183:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Che version

next (development version)

### Steps to reproduce

1. Create Node.Js Angular Web Applicatin worspace
2. Run **Install all required dependencies** command
3. Run **Build application** command
4. See the output

### Expected behavior

Application should biuld without errors

### Runtime

OpenShift

### Screenshots

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2023 10 11-12_44_48](https://github.com/eclipse/che/assets/1271546/3e5124cd-901f-47f2-bd7e-2adbfc4ea811)

### Installation method

chectl/next

### Environment

Linux

### Additional context

It should be possible to build the application after setting env variable `NODE_OPTIONS=--openssl-legacy-provider`

**Comment by svor** [comment]
Since the sample is not used anymore, the issue could be closed
