### ISSUE TITLE
verify all chectl commands work after migration to oclif

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#22635]
### Describe the bug

Some commands after moving to oclif no longer work.

For example:

```
$➔ chectl
Error: command . not found
    at Config.runCommand (/home/nboldt/.local/share/chectl/client/0.0.20231019-next.59da0a4/node_modules/@oclif/core/lib/config/config.js:499:19)
    at async run (/home/nboldt/.local/share/chectl/client/0.0.20231019-next.59da0a4/node_modules/@oclif/core/lib/main.js:90:16)
    at async /home/nboldt/.local/share/chectl/client/0.0.20231019-next.59da0a4/bin/run:6:3

$➔ dsc 
Error: command . not found
    at Config.runCommand (/home/nboldt/dsc/node_modules/@oclif/core/lib/config/config.js:499:19)
    at async run (/home/nboldt/dsc/node_modules/@oclif/core/lib/main.js:90:16)
    at async /home/nboldt/dsc/bin/run:6:3
```

### Che version

next (development version)

**Comment by hantuk** [comment]
Hi, is there any workaround for this issue?
