### ISSUE TITLE
failed Devfile Registry pod bootstrap

### ISSUE THREAD

**Issue by yuki-ohnaka-cv** [eclipse/che#22657]
### Describe the bug

Deploy of pod fails when trying to deploy with AWS EKS.

```
chectl server:deploy \
    --platform=k8s \
    --k8spodreadytimeout=120000 \
    --che-operator-cr-patch-yaml=che-operator-cr-patch.yaml \
    --domain=********
› Current Kubernetes context: '****@****.ap-northeast-1.eksctl.io'
  ✔ Verify Kubernetes API...[1.28+]
  ✔ Kubernetes preflight checklist
    ✔ Verify if kubectl is installed...[OK]
    ✔ Verify domain is set...[OK]
  ✔ Create Namespace eclipse-che...[Created]
  ✔ Install Cert Manager v1.8.2
    ✔ Apply resources...[Exists]
    ✔ Wait for Cert Manager pods ready...[OK]
  ✔ Start following Eclipse Che installation logs...[OK]
  ✔ Deploy Eclipse Che operator
    ✔ Install Dev Workspace operator
      ✔ Create Namespace devworkspace-controller...[Created]
      ✔ Create Dev Workspace operator resources...[Created]
      ✔ Wait for Dev Workspace operator ready...[OK]
    ✔ Create ServiceAccount che-operator...[Created]
    ✔ Create RBAC
      ✔ Create Role che-operator-leader-election...[Created]
      ✔ Create Role che-operator...[Created]
      ✔ Create RoleBinding che-operator-leader-election...[Created]
      ✔ Create RoleBinding che-operator...[Created]
      ✔ Create RoleBinding eclipse-che-che-operator...[Created]
      ✔ Create RoleBinding eclipse-che-che-operator...[Created]
    ✔ Wait for Cert Manager pods ready...[OK]
    ✔ Create Certificate che-operator-serving-cert...[Created]
    ✔ Create Issuer che-operator-selfsigned-issuer...[Created]
    ✔ Create Service che-operator-service...[Created]
    ✔ Create CRD checlusters.org.eclipse.che...[Created]
    ✔ Waiting...[OK]
    ✔ Create Deployment che-operator...[Created]
    ✔ Eclipse Che Operator pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ✔ Create ValidatingWebhookConfiguration org.eclipse.che...[Created]
    ✔ Create MutatingWebhookConfiguration org.eclipse.che...[Created]
    ✔ Create CheCluster Custom Resource...[Created]
  ❯ Wait for Eclipse Che ready
    ❯ Devfile Registry pod bootstrap
      ✖ Scheduling
        → connect ENETUNREACH 52.198.51.229:443
        Downloading images
        Starting
      Plugin Registry pod bootstrap
      Dashboard pod bootstrap
      Gateway pod bootstrap
      Eclipse Che Server pod bootstrap
      Wait Eclipse Che active
    Retrieving Eclipse Che self-signed CA certificate
    Prepare post installation output
Error: Command server:deploy failed with the error: connect ENETUNREACH 52.198.51.229:443 See details: /home/lima.linux/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1699336827878.
    at newError (/home/lima.linux/.local/share/chectl/client/7.76.0/lib/utils/utls.js:39:19)
    at wrapCommandError (/home/lima.linux/.local/share/chectl/client/7.76.0/lib/utils/command-utils.js:53:32)
    at Deploy.<anonymous> (/home/lima.linux/.local/share/chectl/client/7.76.0/lib/commands/server/deploy.js:82:65)
    at Generator.throw (<anonymous>)
    at rejected (/home/lima.linux/.local/share/chectl/client/7.76.0/node_modules/tslib/tslib.js:165:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Cause: Error: connect ENETUNREACH 52.198.51.229:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
```

### Che version

other (please specify in additional context)

### Steps to reproduce

Run the following command.

```
chectl server:deploy \
    --platform=k8s \
    --k8spodreadytimeout=120000 \
    --che-operator-cr-patch-yaml=che-operator-cr-patch.yaml \
    --domain=********
```

### Expected behavior

The command succeeds.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Amazon

### Additional context

```
$ chectl -v
chectl/7.76.0 linux-x64 node-v18.18.0
```

**Comment by tolusha** [comment]
I would recommend retrying deployment with the same command.

**Comment by yuki-ohnaka-cv** [comment]
@tolusha 
I have tried many times and get the same error.
(I have also tried many times to recreate the Cluster in EKS)

**Comment by tolusha** [comment]
@yuki-ohnaka-cv 
I am wondering, the error above should not prevent from Eclipse Che being deployed correctly.
Once command wail, could you check if there is a progress in deploying Eclipse Che?

`watch kubectl get pods -n eclipse-che`
