### ISSUE TITLE
Eclipse Che not being deployed with chectl utility

### ISSUE THREAD

**Issue by debkantap** [eclipse/che#22732]
### Describe the bug

Trying to redeploy the eclipse che in k8s with no change in environment, but che server is not getting up. I guess new version of chectl 7.78 has got some error. Below is the error it is throwing:

----------------------------------

    ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✖ Starting
        → Failed to start a pod, reason: CrashLoopBackOff, message: back-off 2m40s restarting failed container=oauth-proxy pod=che-gateway-58b8464889-n95rh_ecli
…
      Scale Eclipse Che Server Up
      Eclipse Che Server pod bootstrap
Error: Command server:start failed with the error: Failed to start a pod, reason: CrashLoopBackOff, message: back-off 2m40s restarting failed container=oauth-proxy pod=che-gateway-58b8464889-n95rh_eclipse-che(5b15c64b-1316-428d-8c5d-47adbb7d6bd9) See details: /home/chenewpoc/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1702308659495.
    at newError (/home/chenewpoc/.local/share/chectl/client/7.78.0/lib/utils/utls.js:39:19)
    at wrapCommandError (/home/chenewpoc/.local/share/chectl/client/7.78.0/lib/utils/command-utils.js:53:32)
    at Start.<anonymous> (/home/chenewpoc/.local/share/chectl/client/7.78.0/lib/commands/server/start.js:40:65)
    at Generator.throw (<anonymous>)
    at rejected (/home/chenewpoc/.local/share/chectl/client/7.78.0/node_modules/tslib/tslib.js:165:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Cause: Error: Failed to start a pod, reason: CrashLoopBackOff, message: back-off 2m40s restarting failed container=oauth-proxy pod=che-gateway-58b8464889-n95rh_eclipse-che(5b15c64b-1316-428d-8c5d-47adbb7d6bd9)
    at /home/chenewpoc/.local/share/chectl/client/7.78.0/lib/tasks/pod-tasks.js:193:39
    at Generator.next (<anonymous>)
    at fulfilled (/home/chenewpoc/.local/share/chectl/client/7.78.0/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

------

Any clue pls

### Che version

7.78@latest

### Steps to reproduce

try to deploy the using the command:

chectl server:deploy --platform k8s --che-operator-cr-patch-yaml che-operator-cr-patch.yaml --domain XX.XX.XY.XX.nip.io

### Expected behavior

Eclipse Che should be deployed

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✖ Starting
        → Failed to start a pod, reason: CrashLoopBackOff, message: back-off 2m40s restarting failed container=oauth-proxy pod=che-gateway-58b8464889-n95rh_ecli
…
      Scale Eclipse Che Server Up
      Eclipse Che Server pod bootstrap
Error: Command server:start failed with the error: Failed to start a pod, reason: CrashLoopBackOff, message: back-off 2m40s restarting failed container=oauth-proxy pod=che-gateway-58b8464889-n95rh_eclipse-che(5b15c64b-1316-428d-8c5d-47adbb7d6bd9) See details: /home/chenewpoc/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1702308659495.
    at newError (/home/chenewpoc/.local/share/chectl/client/7.78.0/lib/utils/utls.js:39:19)
    at wrapCommandError (/home/chenewpoc/.local/share/chectl/client/7.78.0/lib/utils/command-utils.js:53:32)
    at Start.<anonymous> (/home/chenewpoc/.local/share/chectl/client/7.78.0/lib/commands/server/start.js:40:65)
    at Generator.throw (<anonymous>)
    at rejected (/home/chenewpoc/.local/share/chectl/client/7.78.0/node_modules/tslib/tslib.js:165:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Cause: Error: Failed to start a pod, reason: CrashLoopBackOff, message: back-off 2m40s restarting failed container=oauth-proxy pod=che-gateway-58b8464889-n95rh_eclipse-che(5b15c64b-1316-428d-8c5d-47adbb7d6bd9)
    at /home/chenewpoc/.local/share/chectl/client/7.78.0/lib/tasks/pod-tasks.js:193:39
    at Generator.next (<anonymous>)
    at fulfilled (/home/chenewpoc/.local/share/chectl/client/7.78.0/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by debkantap** [comment]
It was not eclipse-che issue. The keycloak relam was somehow missing..Fixed it. Thanks
