### ISSUE TITLE
Unable to deploy Che on Apple Silicon

### ISSUE THREAD

**Issue by mkhubaibumer** [eclipse/che#22808]
chectl is unable to deploy Eclipse Che on MacBook Apple Silicon as the manifest for arm64 is not available for containers hosted at quay.io/eclipse/che-operator 

```
2024-02-01T13:38:11.345Z Error: Command server:deploy failed with the error: Failed to download image, reason: ErrImagePull, message: no matching manifest for linux/arm64/v8 in the manifest list entries. See details: /Users/khubaibumer/Library/Caches/chectl/error.log. Eclipse Che logs: /var/folders/8x/mp6hbgfs1d3dkkydlksr_cgc0000gn/T/chectl-logs/1706794529194.
2024-02-01T13:38:11.345Z     at newError (/usr/local/lib/chectl/lib/utils/utls.js:39:19)
2024-02-01T13:38:11.345Z     at wrapCommandError (/usr/local/lib/chectl/lib/utils/command-utils.js:54:32)
2024-02-01T13:38:11.345Z     at Deploy.<anonymous> (/usr/local/lib/chectl/lib/commands/server/deploy.js:82:65)
2024-02-01T13:38:11.345Z     at Generator.throw (<anonymous>)
2024-02-01T13:38:11.345Z     at rejected (/usr/local/lib/chectl/node_modules/tslib/tslib.js:167:69)
2024-02-01T13:38:11.345Z Cause: Error: Failed to download image, reason: ErrImagePull, message: no matching manifest for linux/arm64/v8 in the manifest list entries.
2024-02-01T13:38:11.345Z     at /usr/local/lib/chectl/lib/tasks/pod-tasks.js:149:39
2024-02-01T13:38:11.345Z     at Generator.next (<anonymous>)
2024-02-01T13:38:11.345Z     at fulfilled (/usr/local/lib/chectl/node_modules/tslib/tslib.js:166:62)
```

**Comment by tolusha** [comment]
Available architectures are:
* linux/amd64
* linux/ppc64le

**Comment by mkhubaibumer** [comment]
@tolusha is there any specific reason why this is not available for arm64?

**Comment by tolusha** [comment]
@mkhubaibumer 
There is no specific reason.
I think it just hasn't been added.

**Comment by monaka** [comment]
@mkhubaibumer
I suppose Rosetta2 will resolve the issue.

```
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```

And it may be required settings to your container engines.

**Comment by tolusha** [comment]
Closed in favor of https://github.com/eclipse-che/che/issues/23128
