### ISSUE TITLE
An extension installation fails for the Che-Code editor 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22982]
### Describe the bug

It's not possible to install a VS Code extension for the Che-Code editor after fetching last changes from the upstream.

### Che version

Editor image from the PR https://github.com/che-incubator/che-code/pull/357
The PR contains the latest changes from the upstream.

### Steps to reproduce

1. Go to the Extensions view 
2. Select an extension
3. Click `Install` button

### Expected behavior

Extensions installed successfully.

### Screenshots

<img width="467" alt="image" src="https://github.com/eclipse-che/che/assets/5676062/b0731d83-2e96-4170-8481-357543532de1">

<img width="1005" alt="image" src="https://github.com/eclipse-che/che/assets/5676062/28692644-92f0-4567-8755-5e686f552037">

### Environment

I'm able to reproduce the problem on the dogfooding instance using editor image from the PR https://github.com/che-incubator/che-code/pull/357
The PR contains the latest changes from the upstream.

**Comment by vitaliy-guliy** [comment]
There is additional output in `/checode/remote/data/logs/20240523T122056/remoteagent.log`

```
2024-05-23 12:27:10.567 [info] Getting Manifest... redhat.vscode-yaml
2024-05-23 12:27:10.974 [info] Installing extension: redhat.vscode-yaml file:///checode/remote/extensions/extensions.json
2024-05-23 12:27:12.070 [warning] Failed downloading sigzip. End of central directory record signature not found. Either not a zip file, or file is truncated.. Retry again... redhat.vscode-yaml
2024-05-23 12:27:12.214 [warning] Failed downloading sigzip. End of central directory record signature not found. Either not a zip file, or file is truncated.. Retry again... redhat.vscode-yaml
2024-05-23 12:27:12.356 [error] Error while installing the extension redhat.vscode-yaml End of central directory record signature not found. Either not a zip file, or file is truncated. file:///checode/remote/extensions/extensions.json
2024-05-23 12:27:13.357 [error] Error: End of central directory record signature not found. Either not a zip file, or file is truncated.
    at y (/checode/checode-linux-libc/ubi8/out/vs/server/node/server.main.js:105:25790)
    at /checode/checode-linux-libc/ubi8/out/vs/server/node/server.main.js:105:27228
    at /checode/checode-linux-libc/ubi8/node_modules/yauzl/index.js:40:7
    at /checode/checode-linux-libc/ubi8/node_modules/yauzl/index.js:190:5
    at /checode/checode-linux-libc/ubi8/node_modules/yauzl/index.js:712:5
    at /checode/checode-linux-libc/ubi8/node_modules/yauzl/fd-slicer.js:33:7
    at callback (/checode/checode-linux-libc/ubi8/node_modules/graceful-fs/polyfills.js:138:21)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:686:5)

```

**Comment by RomanNikitenko** [comment]
The upstream commit that brought breaking changes is: https://github.com/microsoft/vscode/commit/35c4fb4b9369e7c2024a4753d428187379be2243

Since that commit VS Code verifies extensions signature.
Extensions from the Open VSX registry doesn't pass that ^ check.

**Comment by RomanNikitenko** [comment]
Fixed on the Open VSX registry side
