### ISSUE TITLE
Deploy Che step is failing for the Smoke test of Che-Code

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#23029]
### Describe the bug

The error is:
```
[18:07:14] Wait for Dev Workspace operator ready [started]
[18:09:35] Wait for Dev Workspace operator ready [failed]
[18:09:35] → ERR_TIMEOUT: Timeout set to pod ready timeout 120000
[18:09:35] Install Dev Workspace operator [failed]
[18:09:35] → ERR_TIMEOUT: Timeout set to pod ready timeout 120000
[18:09:35] Deploy Eclipse Che operator [failed]
[18:09:35] → ERR_TIMEOUT: Timeout set to pod ready timeout 120000
Error: Command server:deploy failed with the error: ERR_TIMEOUT: Timeout set to pod ready timeout 120000 See details: /home/runner/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1720202774722.
    at newError (/usr/local/lib/chectl/lib/utils/utls.js:39:19)
    at wrapCommandError (/usr/local/lib/chectl/lib/utils/command-utils.js:54:32)
    at Deploy.<anonymous> (/usr/local/lib/chectl/lib/commands/server/deploy.js:82:65)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/chectl/node_modules/tslib/tslib.js:167:69)
Cause: Error: ERR_TIMEOUT: Timeout set to pod ready timeout 120000
    at KubeClient.<anonymous> (/usr/local/lib/chectl/lib/api/kube-client.js:826:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/chectl/node_modules/tslib/tslib.js:166:62)
Error: Process completed with exit code 2.
```

### Che version

7.88@latest

### Steps to reproduce

Please see https://github.com/che-incubator/che-code/actions/runs/9811560435/job/27093908922?pr=380

### Expected behavior

`Deploy Che` step is successful for the Smoke test of the Che-Code

**Comment by svor** [comment]
I have similar problem as a result of `chectl server:deploy -p openshift`
```
      ✖ Wait for Dev Workspace operator ready
        → ERR_TIMEOUT: Timeout set to pod ready timeout 60000
      Create Subscription eclipse-che
      Eclipse Che Operator pod bootstrap
      Fetch CheCluster sample from a CSV
      Create CheCluster Custom Resource
Error: Command server:deploy failed with the error: ERR_TIMEOUT: Timeout set to pod ready timeout 60000 See details: /home/vsvydenko/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1720444057431.
    at newError (/home/vsvydenko/.local/share/chectl/client/0.0.20240702-next.8e77812/lib/utils/utls.js:39:19)
    at wrapCommandError (/home/vsvydenko/.local/share/chectl/client/0.0.20240702-next.8e77812/lib/utils/command-utils.js:54:32)
    at Deploy.<anonymous> (/home/vsvydenko/.local/share/chectl/client/0.0.20240702-next.8e77812/lib/commands/server/deploy.js:82:65)
    at Generator.throw (<anonymous>)
    at rejected (/home/vsvydenko/.local/share/chectl/client/0.0.20240702-next.8e77812/node_modules/tslib/tslib.js:167:69)
Cause: Error: ERR_TIMEOUT: Timeout set to pod ready timeout 60000
    at KubeClient.<anonymous> (/home/vsvydenko/.local/share/chectl/client/0.0.20240702-next.8e77812/lib/api/kube-client.js:826:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsvydenko/.local/share/chectl/client/0.0.20240702-next.8e77812/node_modules/tslib/tslib.js:166:62)

```

**Comment by vitaliy-guliy** [comment]
> I have similar problem as a result of `chectl server:deploy -p openshift`
> 

Could you share `chectl` version?

**Comment by svor** [comment]
> > I have similar problem as a result of `chectl server:deploy -p openshift`
> 
> Could you share `chectl` version?

**chectl/0.0.20240702-next.8e77812 linux-x64 node-v18.18.0**

**Comment by RomanNikitenko** [comment]
I see that @svor can reproduce the problem locally on his machine https://github.com/eclipse-che/che/issues/23029#issuecomment-2214047597

So, probably it's not `smoke test` specific and the cause of the problem on the `chectl` or `Dev Workspace operator` side.

**Comment by dkwon17** [comment]
After investigation, it is a problem specific to chectl and DWO.

With this PR https://github.com/devfile/devworkspace-operator/pull/1281 the default number of pods for DWO webserver is 2. However, this check in chectl only expects one pod: https://github.com/che-incubator/chectl/blob/8e778128554f032331a6f3719b6fb6caba94a756/src/tasks/installers/dev-workspace/dev-workspace-tasks.ts#L136

**Comment by dkwon17** [comment]
I have an untested fix here: https://github.com/che-incubator/chectl/pull/2895
