### ISSUE TITLE
Increase DNS timeout for `dsc server:deploy`

### ISSUE THREAD

**Issue by imphil** [eclipse/che#23040]
### Describe the bug

When I run `dsc server:deploy` I am getting a DNS resolution failure in the "Plugin Registry pod bootstrap" step. The DNS records are created and the server is working, it's just the `dsc` script that's reporting a (needless) error.

Would it make sense to probe the DNS for a while longer before failing?

```
$ dsc server:deploy --platform openshift
› Current Kubernetes context: 'default/cluster-example-com:32028/user@example.com'
  ✔ Verify Kubernetes API...[1.25]
  ✔ OpenShift version...[4.x]
  ✔ Openshift preflight checklist
    ✔ Verify if oc is installed...[OK]
    ✔ Verify if openshift is running...[OK]
  ✔ Create Namespace openshift-devspaces...[Exists]
  ✔ Start following Red Hat OpenShift Dev Spaces installation logs...[OK]
  ✔ Deploy Red Hat OpenShift Dev Spaces
    ✔ Install Dev Workspace operator
      ✔ Create Subscription devworkspace-operator...[Created]
      ✔ Wait for Dev Workspace operator ready...[OK]
    ✔ Create Subscription devspaces-subscription...[Created]
    ✔ Red Hat OpenShift Dev Spaces Operator pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ✔ Fetch CheCluster sample from a CSV...[OK]
    ✔ Create CheCluster Custom Resource...[Created]
  ❯ Wait for Red Hat OpenShift Dev Spaces ready
    ✔ Devfile Registry pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ❯ Plugin Registry pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✖ Starting
        → getaddrinfo ENOTFOUND cluster.example.com
      Dashboard pod bootstrap
      Gateway pod bootstrap
      Red Hat OpenShift Dev Spaces Server pod bootstrap
      Wait Red Hat OpenShift Dev Spaces active
    Retrieving Red Hat OpenShift Dev Spaces self-signed CA certificate
    Prepare post installation output
Error: Command server:deploy failed with the error: getaddrinfo ENOTFOUND cluster.example.com See details: /home/philipp/.cache/dsc/error.log. Red Hat OpenShift Dev Spaces logs: /tmp/dsc-logs/1721031022113.
    at newError (/home/philipp/swinstall/dsc/lib/utils/utls.js:39:19)
    at wrapCommandError (/home/philipp/swinstall/dsc/lib/utils/command-utils.js:54:32)
    at Deploy.<anonymous> (/home/philipp/swinstall/dsc/lib/commands/server/deploy.js:82:65)
    at Generator.throw (<anonymous>)
    at rejected (/home/philipp/swinstall/dsc/node_modules/tslib/tslib.js:167:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Cause: Error: getaddrinfo ENOTFOUND cluster.example.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
```

### Che version

7.88@latest

### Steps to reproduce

 .

### Expected behavior

.

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

Linux

**Comment by ibuziuk** [comment]
@imphil thank you for the issue report. Would you be interested in contributing a fix to https://github.com/che-incubator/chectl ?

**Comment by tolusha** [comment]
@imphil 
Could you show plugin registry and operator pods logs as well?

**Comment by tolusha** [comment]
@imphil
Feel free to reopen the issue if you have additional details.
