### ISSUE TITLE
Deploy Che is failed

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#23125]
### Describe the bug

I have the following error when deploy Che:
```
Error: Command server:deploy failed with the error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/che-incubator/configbump:next".
```

Also, there is the same error for the `Smoke Test` of the Che-Code, see https://github.com/che-incubator/che-code/actions/runs/10640629098/job/29505180642

### Che version

7.90@latest

### Steps to reproduce

1. `minikube start --memory=16384 --cpus=4 --disk-size='50000mb'  --kubernetes-version=v1.25.0`
2. `minikube addons enable ingress`
3. `chectl server:deploy --platform=minikube --installer=operator`

### Expected behavior

Deploy Che is successful

### Runtime

minikube

### Screenshots

<img width="1248" alt="image" src="https://github.com/user-attachments/assets/ce808bcd-7a7e-47bb-bada-3474d37998d9">

### Installation method

chectl/next

### Environment

macOS

### Eclipse Che Logs

```
❯ Wait for Eclipse Che ready
    ✔ Dashboard pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ❯ Gateway pod bootstrap
      ✔ Scheduling...[OK]
      ✖ Downloading images
        → Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/che-incubator/configbump:next".
        Starting
      Eclipse Che Server pod bootstrap
      Wait Eclipse Che active
    Retrieving Eclipse Che self-signed CA certificate
    Prepare post installation output
Error: Command server:deploy failed with the error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/che-incubator/configbump:next". See details: /Users/rnikitenko/Library/Caches/chectl/error.log. Eclipse Che logs: /var/folders/q2/tbgbfg4s5mq5hw5czfdgjjkr0000gn/T/chectl-logs/1725091965844.
    at newError (/Users/rnikitenko/projects/chectl/lib/utils/utls.js:39:19)
    at wrapCommandError (/Users/rnikitenko/projects/chectl/lib/utils/command-utils.js:54:32)
    at Deploy.<anonymous> (/Users/rnikitenko/projects/chectl/lib/commands/server/deploy.js:82:65)
    at Generator.throw (<anonymous>)
    at rejected (/Users/rnikitenko/projects/chectl/node_modules/tslib/tslib.js:167:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Cause: Error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/che-incubator/configbump:next".
    at /Users/rnikitenko/projects/chectl/lib/tasks/pod-tasks.js:148:39
    at Generator.next (<anonymous>)
    at fulfilled (/Users/rnikitenko/projects/chectl/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional context

chectl/0.0.20240822-next.0a6b042 darwin-x64 node-v20.10.0

**Comment by tolusha** [comment]
I've rebuild the image.
Should be ok now.
