### ISSUE TITLE
Error login to github copilot

### ISSUE THREAD

**Issue by huonguyenlt** [eclipse/che#23227]
### Describe the bug

After install github copilot extension, I cannot sign in to github

### Che version

7.89

### Steps to reproduce

1. install github copilot from visx file. Version 1.243.0
2. sign in to github
3. error

### Expected behavior

sign in successfully

### Runtime

kubernetes

### Screenshots

![image](https://github.com/user-attachments/assets/5b314e17-93e3-49dd-ac6e-9056a270d90d)

### Installation method

other (please specify in additional context)

### Environment

EKS

### Eclipse Che Logs

```shell
2024-11-04 09:02:11.851 [warning] [certificates] Failed to parse certificate # ACCVRAIZ1
 Error: error:0909006C:PEM routines:get_name:no start line
    at new X509Certificate (node:internal/crypto/x509:119:21)
    at /checode/remote/extensions/github.copilot-1.243.0-universal/lib/src/network/certificateReaders.ts:79:36
    at Array.filter (<anonymous>)
    at Ene.removeExpiredCertificates (/checode/remote/extensions/github.copilot-1.243.0-universal/lib/src/network/certificateReaders.ts:77:32)
    at Ene.getAllRootCAs (/checode/remote/extensions/github.copilot-1.243.0-universal/lib/src/network/certificateReaders.ts:68:38)
    at sue.createSecureContext (/checode/remote/extensions/github.copilot-1.243.0-universal/lib/src/network/certificates.ts:46:23)
    at sue.applyToRequestOptions (/checode/remote/extensions/github.copilot-1.243.0-universal/lib/src/network/certificates.ts:61:23)
    at cue.fetch (/checode/remote/extensions/github.copilot-1.243.0-universal/lib/src/network/helix.ts:90:9)
    at xH.fetchExperiments (/checode/remote/extensions/github.copilot-1.243.0-universal/lib/src/experiments/fetchExperiments.ts:79:20) {
  opensslErrorStack: [
    'error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error',
    'error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header',
    'error:0D07209B:asn1 encoding routines:ASN1_get_object:too long'
  ],
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
2024-11-04 09:02:11.851 [info] [certificates] Removed 1 expired certificates
2024-11-04 09:02:51.484 [error] [auth] auth: Error: read ECONNRESET
    at d.createSession (/checode/checode-linux-libc/ubi8/extensions/che-github-authentication/dist/extension.js:2:2606657)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at c.$createSession (/checode/checode-linux-libc/ubi8/out/vs/workbench/api/node/extensionHostProcess.js:152:60665)
2024-11-04 09:02:51.484 [error] [auth] read ECONNRESET
2024-11-04 09:06:08.056 [error] [default] github.copilot.signIn: Error: read ECONNRESET
    at d.createSession (/checode/checode-linux-libc/ubi8/extensions/che-github-authentication/dist/extension.js:2:2606657)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at c.$createSession (/checode/checode-linux-libc/ubi8/out/vs/workbench/api/node/extensionHostProcess.js:152:60665)
```

**Comment by Longin-Yu** [comment]
I meet the same error. Have you solved it?

**Comment by huonguyenlt** [comment]
@Longin-Yu it just does not support github copilot
