### ISSUE TITLE
Add JetBrains Rider IDE integration

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#23228]
### Is your task related to a problem? Please describe

When running a workspace with the [JetBrains Rider IDE](https://gist.githubusercontent.com/azatsarynnyy/692c7f8b795cbc2adfc745f65a5939ff/raw/96bb5c8c291c00d6a99082c71e625ab0683ff219/che-idea-server.yaml), the Dashboard displays the following message:

![image](https://github.com/user-attachments/assets/353e1bb2-6f24-419c-af61-42b8fccbe335)

### Describe the solution you'd like

We need to figure out why the remote Rider IDE backend doesn't provide a connection link and the startup process is stopped on the stage:
```shell
2024-11-04 10:18:31,972 [   9535]   WARN - #c.i.u.n.IdeProxySelector - failed to configure proxy by pacUrl=null (null if autodetect)
2024-11-04 10:18:34,486 [  12049]   WARN - #com.github.weisj.jsvg.parser.NodeMap - unsupported RDF
2024-11-04 10:18:34,486 [  12049]   WARN - #com.github.weisj.jsvg.parser.NodeMap - unsupported namedview
```

It should output the links like other JetBrains IDEs do:
```shell
*********************************************************

Join link: tcp://127.0.0.1:5990#jt=98508eea-e3f3-4d63-bed4-877ecc20b451&p=CL&fp=15497311CE1A148221F87B0DF2BE2B4EC516604C621140DA878FA0164B5AB86B&cb=242.23726.125&newUi=true&jb=21.0.4b509.26

Http link: https://code-with-me.jetbrains.com/remoteDev#idePath=%2Fidea-server&projectPath=%2Fprojects%2Fdotnet60-example&host=workspace2622be1ccbd241c6-5c97d8f44f-2w856&port=22&user=1001270000&type=ssh&deploy=false&newUi=true

Gateway link: jetbrains-gateway://connect#idePath=%2Fidea-server&projectPath=%2Fprojects%2Fdotnet60-example&host=workspace2622be1ccbd241c6-5c97d8f44f-2w856&port=22&user=1001270000&type=ssh&deploy=false&newUi=true

*********************************************************
```

**Comment by azatsarynnyy** [comment]
_Note, I'm updating this comment while detecting more information about_
Below, I'm updating the results of testing [JetBrains Rider IDE](https://gist.githubusercontent.com/azatsarynnyy/692c7f8b795cbc2adfc745f65a5939ff/raw/6de4dbcdcaf7e488598944de2401ede4b126e3c4/che-idea-server.yaml)
with the .NET samples provided on the Che Dashboard:

| Sample | Workspace starts? |
|--------|--------|
| .NET 3.1 | -  [1] |
| .NET 5.0 | - [1] |
| .NET 6.0 | + |
| .NET 8.0 | + |

And with the images that are mostly used:

| Image | Workspace starts? |
|--------|--------|
| [devfile/base-developer-image:ubi9-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/base-ubi9) | - [2] |
| [devfile/universal-developer-image:ubi9-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/universal-ubi9) | + |
| [registry.access.redhat.com/ubi9](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9) | - [2] |
| [registry.access.redhat.com/ubi9-init](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9-init) | - [2] |
| [registry.access.redhat.com/ubi9-minimal](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9-minimal) | - [2] |

**Problem [1]**
```
/idea-server/status-app/node_modules/merge-descriptors/index.js:13
                if (!overwrite && Object.hasOwn(destination, name)) {
                                         ^

TypeError: Object.hasOwn is not a function
    at mergeDescriptors (/idea-server/status-app/node_modules/merge-descriptors/index.js:13:28)
    at createApplication (/idea-server/status-app/node_modules/express/lib/express.js:41:3)
    at Object.<anonymous> (/idea-server/status-app/index.js:44:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! idea-status@7.101.0-next start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the idea-status@7.101.0-next start script.
```

The solution is to update the Node.js version in the images for .NET 3.1 and .NET 5.0 samples.
To fix the error, a version >16.9.0 is required.
_As all the versions of Node.js <20.x are End-of-Life._
Taking into account that the .NET SDK versions <8 are no longer supported, I suggest removing the samples with 3.1, 5.0, and 6.0.

**Problem [2]**
`
2025-07-03 17:48:36,164 [   5237] SEVERE - #c.j.r.p.ReSharperProcess - IdeaLoggingEvent[message=Rider host (PID = 194) has unexpectedly exited with exit code 134., throwable=java.lang.Throwable
`

For this problem, I currently don't have a solution.
Continue investigating.

**Comment by azatsarynnyy** [comment]
With [Rider updated to 2025.2](https://github.com/che-incubator/jetbrains-ide-dev-server/commit/04a339c45290bf88162457f9b5eb46fea51736e3),
the previous results of testing it against different images are not relevant anymore.

The ReSharper Engine starts with no errors:
<img width="367" height="134" alt="Image" src="https://github.com/user-attachments/assets/e6fdac6b-6a7d-4df3-816a-189333bbd845" />

It looks like the problems have been fixed by the JetBrains team 🎉

**Comment by azatsarynnyy** [comment]
In this comment, below, I'm updating the testing results for 2025.2.


| Sample | Workspace starts? |
|--------|--------|
| .NET 6.0 | + |
| .NET 8.0 | + |

And with the images that are mostly used:

| Image | Workspace starts? |
|--------|--------|
| [devfile/base-developer-image:ubi9-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/base-ubi9) | - [1] |
| [devfile/universal-developer-image:ubi9-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/universal-ubi9) | + |
| [registry.access.redhat.com/ubi9](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9) | - [1] |
| [registry.access.redhat.com/ubi9-init](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9-init) | - [1] |
| [registry.access.redhat.com/ubi9-minimal](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9-minimal) | - [1] |


**Problem [1]**
<img width="644" height="191" alt="Image" src="https://github.com/user-attachments/assets/f5281fb4-d3f2-45d5-8b7c-740d01eaebb1" />

<img width="449" height="98" alt="Image" src="https://github.com/user-attachments/assets/d6967215-4d74-448a-ad56-dda42a635ace" />

`> cat /tmp/user/.cache/JetBrains/Rider2025.2/log/backend.2025-08-18_0553.173-err.log`

```
/idea-server/lib/ReSharperHost/linux-x64/Rider.Backend --runtimeconfig /idea-server/lib/ReSharperHost/Rider.Backend.netcore.runtimeconfig.json --Port=42669 --enablecpp
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.String.StartsWith(System.String, System.StringComparison)
   at JetBrains.HabitatDetector.Impl.Linux.LinuxHelper.ConvertToLibC(System.String)
   at JetBrains.HabitatDetector.Impl.Linux.LinuxHelper.GetElfInfo(System.IO.Stream)
   at JetBrains.HabitatDetector.Impl.Linux.LinuxHelper.GetElfInfo(System.String)
   at JetBrains.HabitatDetector.Impl.Helper..cctor()
   at JetBrains.HabitatDetector.HabitatInfo.get_ClrImplementation()
   at JetBrains.Util.PlatformUtil.get_IsRunningOnCore()
   at JetBrains.Util.PlatformUtil..cctor()
   at JetBrains.Util.PlatformUtil.get_IsRunningOnCore()
   at JetBrains.Util.ProcessorUtil.GetProcessorCountWithAffinityMask()
   at JetBrains.Util.Utils.StartupMeasurer..cctor()
   at JetBrains.Util.Utils.StartupMeasurer.StartRecording()
   at JetBrains.Rider.Backend.Product.RiderBackendProgram.Main()
```

**Comment by azatsarynnyy** [comment]
Updating the Rider version in https://github.com/che-incubator/jetbrains-ide-dev-server/commit/04a339c45290bf88162457f9b5eb46fea51736e3
and adding the patch https://github.com/che-incubator/jetbrains-ide-dev-server/pull/49/commits/354cc040c31e5b692476d1d04c5bb136b97ea042
fixed the Rider launch in the UBI/UDI 8/9 images 🎉 

| Image | Workspace starts? |
|--------|--------|
| [devfile/base-developer-image:ubi8-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/base-ubi8) | + |
| [devfile/base-developer-image:ubi9-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/base-ubi9) | + |
| [devfile/universal-developer-image:ubi8-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/universal-ubi8) | + |
| [devfile/universal-developer-image:ubi9-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/universal-ubi9) | + |
| [registry.access.redhat.com/ubi8](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi8) | + |
| [registry.access.redhat.com/ubi9](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9) | + |
| [registry.access.redhat.com/ubi8-init](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi8-init) | + |
| [registry.access.redhat.com/ubi9-init](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9-init) | + |
| [registry.access.redhat.com/ubi8-minimal](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi8-minimal) | + |
| [registry.access.redhat.com/ubi9-minimal](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9-minimal) | + |
