### ISSUE TITLE
Add JetBrains GoLand IDE integration

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#23229]
### Is your task related to a problem? Please describe

When running a workspace from the `Go Runtime` sample with the [JetBrains GoLand IDE](https://gist.githubusercontent.com/azatsarynnyy/692c7f8b795cbc2adfc745f65a5939ff/raw/9a9bc4ac24dcf33f449ddfab3b4659d45ecf6d02/che-idea-server.yaml), the Dashboard displays the following message:
![image](https://github.com/user-attachments/assets/49055a6e-5497-4710-86bb-1d5baf21379f)

### Describe the solution you'd like

We need to fix the problem reported by the GoLand IDE backend process when running from the `Go Runtime` sample:
```shell
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /opt/app-root/src/.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001270000:0 "/opt/app-root/src/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /opt/app-root/src/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
Status app is listening on port 3400

**Start Failed**

Internal error

java.nio.file.AccessDeniedException: /opt/app-root/src/.config
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
        at java.base/java.nio.file.Files.createDirectory(Files.java:699)
        at com.intellij.openapi.util.io.NioFiles.tryCreateDirectory(NioFiles.java:96)
        at com.intellij.openapi.util.io.NioFiles.createDirectories(NioFiles.java:89)
        at com.intellij.openapi.util.io.NioFiles.createDirectories(NioFiles.java:88)
        at com.intellij.openapi.util.io.NioFiles.createDirectories(NioFiles.java:88)
        at com.intellij.platform.ide.bootstrap.DirectoryLock.lockOrActivate(DirectoryLock.java:148)
        at com.intellij.platform.ide.bootstrap.StartupUtil$lockSystemDirs$result$1.invokeSuspend(startup.kt:500)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

-----
JRE: 21.0.4+13-b509.17 amd64 (JetBrains s.r.o.)
/idea-server/jbr
```

**Comment by AObuchow** [comment]
@azatsarynnyy FWIW, the `Go Runtime` sample has `$HOME` set to `/opt/app-root/src/` which is not writeable. We encountered something similar for [DWO](https://github.com/devfile/devworkspace-operator/issues/1337) but in our case, we are most likely just going to abort if $HOME is not writeable, which doesn't seem to be the correct solution for this issue (since then, the IDE won't start).

**Comment by azatsarynnyy** [comment]
The verification results.

Samples:

| Sample | Workspace starts? |
|--------|--------|
| Go (registry.redhat.io/devspaces/udi-rhel9:3.22) | + |
| Go Runtime (registry.access.redhat.com/ubi9/go-toolset:1.19.13) | -  [1] |

The images:

| Image | Workspace starts? |
|--------|--------|
| [devfile/base-developer-image:ubi9-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/base-ubi9) | + |
| [devfile/universal-developer-image:ubi9-latest](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/devfile/universal-ubi9) | + |
| [registry.access.redhat.com/ubi9](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9) | + |
| [registry.access.redhat.com/ubi8-init](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi8-init) | + |
| [registry.access.redhat.com/ubi9-init](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9-init) | + |
| [registry.access.redhat.com/ubi9-minimal](https://github.com/azatsarynnyy/ubi9-based-sample-public/tree/ubi9-minimal) | + |


**Problem [1]**
```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /opt/app-root/src/.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001270000:0 "/opt/app-root/src/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /opt/app-root/src/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
Status app is listening on port 3400

**Start Failed**

Internal error

java.nio.file.AccessDeniedException: /opt/app-root/src/.config
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
        at java.base/java.nio.file.Files.createDirectory(Files.java:699)
        at com.intellij.openapi.util.io.NioFiles.tryCreateDirectory(NioFiles.java:96)
        at com.intellij.openapi.util.io.NioFiles.createDirectories(NioFiles.java:89)
        at com.intellij.openapi.util.io.NioFiles.createDirectories(NioFiles.java:88)
        at com.intellij.openapi.util.io.NioFiles.createDirectories(NioFiles.java:88)
        at com.intellij.platform.ide.bootstrap.DirectoryLock.lockOrActivate(DirectoryLock.java:148)
        at com.intellij.platform.ide.bootstrap.StartupUtil$lockSystemDirs$result$1.invokeSuspend(startup.kt:500)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

-----
JRE: 21.0.4+13-b509.17 amd64 (JetBrains s.r.o.)
/idea-server/jbr
```

So, the `Go Runtime ` sample is **the only container** that we need to fix launching GoLand IDE in.

**Comment by adietish** [comment]
@azatsarynnyy when using the [fixed editor definition](https://gist.github.com/adietish/0f2da750abf249fe5e07c585c14fc172#file-gistfile1-txt-L33) there are no permission issues any more. The issue that you face is what is reported in https://github.com/eclipse-che/che/issues/23229#issuecomment-3174815088

**Comment by azatsarynnyy** [comment]
> [@azatsarynnyy](https://github.com/azatsarynnyy) when using the [fixed editor definition](https://gist.github.com/adietish/0f2da750abf249fe5e07c585c14fc172#file-gistfile1-txt-L33) there are no permission issues any more. The issue that you face is what is reported in [#23229 (comment)](https://github.com/eclipse-che/che/issues/23229#issuecomment-3174815088)

I see. Thanks @adietish.
The point is that the error is relevant to the Go Runtime sample only.

**Comment by azatsarynnyy** [comment]
@adietish 
Taking into account that GoLand IDE works with all images
except the Go Runtime sample,
to close this issue, it's enough just to add the editor definition to che-operator.

See an example for PhpStorm here https://github.com/eclipse-che/che-operator/tree/main/editors-definitions
(2 yaml files)

It will add a new editor tile to the Dashboard.

Fixing it for the Go Runtime sample can be continued within https://github.com/eclipse-che/che/issues/23520

**Comment by adietish** [comment]
`GoLand` IDE works except with the sample `Go Runtime`. We'll tackle it in https://github.com/eclipse-che/che/issues/23520. 
I'm therefore closing this issue.

**Comment by adietish** [comment]
Reopening to properly reflect the status of the support for GoLand IDE in [Red Hat OpenShift Dev Spaces and Web Terminal Priorities](https://github.com/orgs/eclipse-che/projects/8). We'll close this as soon as #23520 is closed.
